### ISSUE TITLE
Raw HTML Export

### ISSUE THREAD

**Issue by ChildishhAlbino** [KosmosisDire/obsidian-webpage-export#104]
**Is your feature request related to a problem? Please describe.**
Trying to export whole or parts of an Obisidian file to google docs for other people to use and cannot copy-paste without copying the CSS formatting of the page.

**Describe the solution you'd like**
A toggle to export raw HTML with only basic text formatting - no background colours etc.

**Describe alternatives you've considered**
Have tried the Pandoc plugin and that used to work but for some reason, I can no longer copy paste in those files - the document gets treated as a drag-and-drop.

Workaround, for now, is inspecting the HTML and deleting the `head` element to restore the default browser styles.

**Additional context**

**Comment by KosmosisDire** [comment]
This is not really an intended use of this plugin, have you tried this plugin: https://github.com/mvdkwast/obsidian-copy-as-html

**Comment by ChildishhAlbino** [comment]
No I haven't but I will - thanks for that!

**Comment by ChildishhAlbino** [comment]
That worked - thanks!

**Comment by KosmosisDire** [comment]
That's great, glad it worked :)
