### ISSUE TITLE
Multi-File website not working all of the sudden

### ISSUE THREAD

**Issue by thehirou** [KosmosisDire/obsidian-webpage-export#106]
Sorry for opening another issue, since this used to work in this exact same version a week ago (I believe), but now all of the sudden the images and audios aren't being exported as a separate file when exporting to multi-file website (Thus they don't appear in the page). I already tried multiple exports and opening and closing obsidian.

Any idea what might be causing this? self-contained documents option works but it goes way too slow for me and I want the files to be separate.

I'm not sure what should I attach so if you need more info about it let me know.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/82706798/26ecc225-1115-4f29-a9af-1dea29834e6d)

**Comment by KosmosisDire** [comment]
This is due to issue #98

**Comment by KosmosisDire** [comment]
Closing since this issue is already in #98. Thank you for the report, and don't hesitate to submit any other problems you find :)

**Comment by KosmosisDire** [comment]
This is fixed in update 1.6.0, let me know if you have any more problems! And thanks for the report :)
