### ISSUE TITLE
Fix default theme always light theme, and new files resetting back to light 

### ISSUE THREAD

**Issue by dgudim** [KosmosisDire/obsidian-webpage-export#107]
Currently if you are opening the export for the first time and have the browser set to dark theme, theme switches to a dark one as expected, but in a few seconds it switches back to light. 

And also, you can't switch the theme on mobile at all, you are stuck with light one

**Comment by KosmosisDire** [comment]
The theme switching is not based on browser theme but on the theme you exported with and there is no way around this flash because it has to start on some style. The reason it changes is likely because it is matching the system theme, which afaik is the only theme I can respect.

As far as changing theme on mobile, I will eventually add mobile support to the sidebars.

**Comment by KosmosisDire** [comment]
In the next update I will remove the feature that switches the theme to match the system theme because of this flashing. Instead it will just match the theme upon export by default.

**Comment by KosmosisDire** [comment]
> @hobojoe720  Under appearance > Base color scheme is set to dark for me, but it always exports with the default as light mode, assuming that is a bug then. As I was going to post a request to have the default here selectable

The webpage caches the state of the theme toggle, so if you switched the theme to light then even if you export in dark mode if will switch to light mode automatically until you manually switch it to dark mode. Then if will stay in dark mode. Is this what is happening or is it actually starting in light mode even during the page load?

**Comment by hobojoe720** [comment]
> > @hobojoe720  Under appearance > Base color scheme is set to dark for me, but it always exports with the default as light mode, assuming that is a bug then. As I was going to post a request to have the default here selectable
> 
> The webpage caches the state of the theme toggle, so if you switched the theme to light then even if you export in dark mode it will switch to light mode automatically until you manually switch it to dark mode. Then it will stay in dark mode. Is this what is happening or is it actually starting in light mode even during the page load?

Even on a fresh PC the export always come in light mode. It will remember for the file, but a new file will reset it back to light mode

**Comment by dgudim** [comment]
Yes, that's the same behavior I am observing

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!

**Comment by softyoda** [comment]
Hi, I'm still experiencing this in version 1.9.2. My setup:
  - Obsidian is set to light mode
  - I export a page
  - The exported HTML opens dark in the browser


I've disabled the theme toggle (themeToggleOptions.enabled = false) — this only removes the toggle button from the page, it doesn't lock the export to light mode. 

There is no option in the plugin settings to explicitly choose light or dark as a default; the only theme option is to override the theme entirely. It seems the exported page's JavaScript is still detecting the browser/OS color scheme preference at load time and overriding whatever Obsidian was set to at export time. The fix described in this issue (defaulting to the export's original theme) doesn't appear to be working. 

Requested feature: A simple setting to force the exported HTML to always render in light or dark mode, independent of the viewer's OS/browser preference. This is especially important when the theme toggle is disabled — right now disabling it with no default set seems to fall back to dark.



Edit/addition: To clarify what I actually need: not just a default color scheme, but a static light-only export — only the light CSS should be included in the output, with no dark mode CSS and no JavaScript theme detection. The goal is a lightweight, static page that is always light.
