### ISSUE TITLE
[Feature Request] Remove Specific part from generated html(by using regex)

### ISSUE THREAD

**Issue by Quorafind** [KosmosisDire/obsidian-webpage-export#109]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. 

I'm always frustrated when I want to export html from note that is using strange new world plugin, wikilinks are always followed by number like :

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/13215013/be1f7352-e83a-45b5-8a8b-6e0ce43b1897)

It is useful when I am using reading mode, but it should be removed when I wanted to generate html from current note. 

**Describe the solution you'd like**

Allow regex when I generate html to remove specific part of html?

**Describe alternatives you've considered**

Support strange new world plugin only.

**Additional context**

**Comment by KosmosisDire** [comment]
I'll consider this, thanks for the request!

**Comment by KosmosisDire** [comment]
Also consider that this could be solved by including a snippet in your exports (enable the snippet before exporting) that hides these.

I may actually add a feature to hide elements with a certain selector, since I think that is the main application of this.

**Comment by Quorafind** [comment]
Yes! You remind me of the snippet feature, thank a lot!

**Comment by KosmosisDire** [comment]
I am going to close this as this problem is solved by snippets, let me know if you have any feedback on this
