### ISSUE TITLE
Alters system clipboard on Plugin load to word "Hello"

### ISSUE THREAD

**Issue by aubreyz** [KosmosisDire/obsidian-webpage-export#111]
**Describe the bug**
At least on windows, when the plugin loads it replaces whatever is in the clipboard with the Word "Hello"

**Operating System**

Windows 11

**To Reproduce**
Error resolved when deactivate plugin (see also code which does this)

**Comment by KosmosisDire** [comment]
Yes, I am aware of this haha. It was a test line I accidentally left in in the last release, which I have removed for the next release. Thank you for the report :D

**Comment by KosmosisDire** [comment]
If you have having trouble with it replacing something important, for now you can turn on clipboard history in Windows using `Win + V`.

**Comment by KosmosisDire** [comment]
This is fixed in update 1.6.0, let me know if you have any more problems! And thanks for the report :)
