### ISSUE TITLE
Include dynamically generated headers to the table of contents

### ISSUE THREAD

**Issue by dgudim** [KosmosisDire/obsidian-webpage-export#117]
Basically a continuation of [issue 96](https://github.com/KosmosisDire/obsidian-webpage-export/issues/96#issuecomment-1568745993) as a separate feature request.

Old old: (3 version ago I think, without background renderer)
![Screenshot_20230530_190826](https://github.com/KosmosisDire/obsidian-webpage-export/assets/34401005/d6ca52b8-0cbf-4c5c-b0ad-afe04e1782f8)
New:
![Screenshot_20230530_190905](https://github.com/KosmosisDire/obsidian-webpage-export/assets/34401005/5c39982f-a2d4-43f3-ae27-cbfb234bbe5a)

**Comment by KosmosisDire** [comment]
Note for future: This should be implemented as a default-disabled option in the settings. The current behavior is intended.

**Comment by KosmosisDire** [comment]
This has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
