### ISSUE TITLE
Underlines in headers are not rendered correctly

### ISSUE THREAD

**Issue by dgudim** [KosmosisDire/obsidian-webpage-export#118]
Exported:
![Screenshot_20230530_192704](https://github.com/KosmosisDire/obsidian-webpage-export/assets/34401005/be3cccc5-460e-4cae-9a62-fdc7863b8392)

Exported (table of contents):
![Screenshot_20230530_192712](https://github.com/KosmosisDire/obsidian-webpage-export/assets/34401005/45ae32fa-0fcb-490c-8da9-05e3251ce827)

Obsidian:
![Screenshot_20230530_192721](https://github.com/KosmosisDire/obsidian-webpage-export/assets/34401005/e096b912-e5df-4de1-b309-6c8c5c2b4457)

**Comment by dgudim** [comment]
I have tested it in firefox and chrome, the behavior is identical

**Comment by KosmosisDire** [comment]
This is fixed in v1.7.1! Let me know if you have any problems with it
