### ISSUE TITLE
Export Vault  might not be working

### ISSUE THREAD

**Issue by mikeBehar** [KosmosisDire/obsidian-webpage-export#12]
Using either the Ribbon, the right-click menu, or the direct command to export the vault, the only thing that displays is the Export **Web page** form.  The only feature that does work is export to HTML.  This works for a single page.  Selecting multiple pages and then exporting also does no work -- that is, nothing is exported.

**Comment by KosmosisDire** [comment]
What platform are you on? And could you send me a screenshot of the developer console after exporting the vault (Ctrl + Shift + I), and a screenshot of your export settings? Then also could you try this in a completely new vault with no other plugins or themes. Thanks for the report!

**Comment by mikeBehar** [comment]
Hi Nathan,
To answer your questions:

I am running windows 10 Home, Build 19041.vb_release.191206-1406

2. The vault does not export -- so no screenshot.

3.  Export settings are in the screenshots below.

This is in a new vault with some stuff in it but no other community plugins
are enabled

I hope the gif gives you a clear view of what is happening.

Please let me know if there is anything else I can do to help you resolve
this,

Thanks for creating this very useful plugin.

Mike



[image: image.png]

[image: image.png]

**Comment by KosmosisDire** [comment]
Hello, I know it doesn't export. But I want a screenshot of the console so I can see what errors are being thrown when it fails. This will help me figure out what is wrong. Also Your images did not upload correctly because you send the message from your email. Try sending the images directly from GitHub so that they upload correctly thanks!

**Comment by mikeBehar** [comment]
OK, so this is a case of RFM -- I should have gone the next step -- after hitting export, I should have selected a vault or folder and then continued.  It DOES export both with some minor errors captured in the attached screenshots of the console.


Console before exporting the vault
![Obsidian Console Before vault 2023-01-16](https://user-images.githubusercontent.com/218642/212750450-dc42e90c-7ddb-4847-a5c2-6d3da5837fa7.png)

After exporting the VAULT
![Obsidian console After vault 2023-01-16](https://user-images.githubusercontent.com/218642/212751221-d3e445c8-c749-4a86-8071-0058ba678a24.png)

This is the console error after exporting s single folder

![Obsidian Console Folder After2023-01-16](https://user-images.githubusercontent.com/218642/212752398-37470ffa-99d8-49ba-b38c-2e55ccabb684.png)


This shows what I believe is an incorrect popup after selecting Web export **vault** it shows web export **Webpage**

![obsidia Web vault Export 1-16-2023 ](https://user-images.githubusercontent.com/218642/212751737-c47031d4-5ea4-4a16-83af-c28248786dcc.gif)

Question:  If I select multiple documents -- is there a way to export the batch or must they be exported one at a time?

**Comment by KosmosisDire** [comment]
The console says it has been successfully exported to your downloads folder, are you sure it isn't exporting? Does it show the file save dialog when you export (the one that lets you select a location to export to)?

Also that always says HTML Webpage Settings, it's reference to the name of the plugin rather than the fact that you are exporting a single file. 

You can export folders, but I don't yet support exporting a multi-selection. That's something I hadn't thought of, thanks!

**Comment by mikeBehar** [comment]
Yes it does work.  I think it was my error.  When exporting a page, I saw the name in the file save menu.  When exporting a vault, it was blank and I assumed noting would be exported so I did not select a folder. My Bad. Sorry.

As for the label for the popup "HTML Webpage Settings". may I suggest you modify it, perhaps to "Export Settings for HTML Webpage".

Also another feature request.  When exporting a page you create a "Table of Contents".  Perhaps you can create a TOC whenever you export a file or vault.

Thanks

**Comment by mikeBehar** [comment]
Again, sorry for my confusion.  I think the errors in the vault export might impact the quality of

**Comment by KosmosisDire** [comment]
> **mikeBehar:** Again, sorry for my confusion. I think the errors in the vault export might impact the quality of the exported pages. Can you replicate this issue? If not I can try it again.

Are there still issues? From your last message I assumed that all was working. The errors saying that the images are not found are unavoidable but are not actually an indication of a problem (unless the images are actually not exporting for you?).

As far as the vault-level table of contents, that is something that I plan to do in the future but it is a much larger undertaking than it might seem. But it's definitely in the plan!

I will definitely change the title on the settings, and probably reorganize the settings overall eventually. Unfortunately, I have just started school back up again and am pretty busy so it is also a future thing for now. 

Thanks for your input!

**Comment by mikeBehar** [comment]
No new issues.  All of the errors are from one document.  Here is the URL: https://cmap.ihmc.us/docs/theory-of-concept-maps
On inspection it looks like each of the images throw an error. It turns out, the images were not captured in Obsidian.  I just recaptured the file and the images are there and now there are no errors on export.  So all is well.

Good luck in school.

Thanks again for a very useful plugin.

Best,

Mike
