### ISSUE TITLE
Add file tree / vault search

### ISSUE THREAD

**Issue by KosmosisDire** [KosmosisDire/obsidian-webpage-export#120]
Add a search box to find files in the vault, simmilar to the one in obidian's publish:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/39423700/d1833b29-d52c-4f8f-a498-3a1df040bbaf)

This will likely start by only filtering the file tree, but I may add additional search functionality to it later.

**Comment by 7Mik** [comment]
IMHO this is priority issue. I will try to help.

https://github.com/nextapps-de/flexsearch
Seems to be a good library performance-wise and is also well maintained.

Would also solve #93 as you proposed: just make any "#tagname" redirect to "?q=#tagname" so that it generates a search

**Comment by KosmosisDire** [comment]
Thanks, that library looks great! The reason I don't have this as a priority is because it's a very large feature and I am focused on bux fixes, UX, and stability at this moment. Additionally, before you start work on this be aware that the 1.7.4 branch has many major changes that may make any large changes to the master branch hard to merge.

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
