### ISSUE TITLE
Problems if you try to print html page to pdf

### ISSUE THREAD

**Issue by Giovy27072** [KosmosisDire/obsidian-webpage-export#121]
**Describe the bug**
If I try to print the page using the Firefox (or any other browser) print function it detects only 1 page.

**Operating System**
OS: Windows11
Obsidian version: latest
Plugin version latest

**To Reproduce**
1. Export file in html
2. Click on "Print..." button in any browser

**Screenshots**

In this screenshot, the browser detects only a very small file part

![immagine](https://github.com/KosmosisDire/obsidian-webpage-export/assets/73668600/ec694be5-3394-456a-84be-1350853cc746)

### IMPORTANT: Error Log
SYSTEM INFO:
	Obsidian version: v1.3.4
	Installer version: v1.1.16
	Operating system: Windows 10 Pro 10.0.22621
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: Things v2.1.9
	Snippets enabled: 3
	Restricted mode: off
	Plugins installed: 15
	Plugins enabled: 15
		1: Admonition v9.3.1
		2: Outliner v4.7.1
		3: Copy button for code blocks v0.1.0
		4: Style Settings v1.0.6
		5: Editor Syntax Highlight v0.1.3
		6: Emoji Toolbar v0.4.1
		7: Excalidraw v1.9.2
		8: BBCode Convertor v1.0.0
		9: Recent Files v1.3.6
		10: Dictionary v2.22.0
		11: Various Complements v8.3.1
		12: List Callouts v1.1.4
		13: Obsidian Git v2.20.0
		14: Advanced Tables v0.18.1
		15: Webpage HTML Export v1.6.0

**Comment by KosmosisDire** [comment]
Thanks, I'll check this out!

**Comment by Giovy27072** [comment]
Hi, news about fix for this bug?

**Comment by KosmosisDire** [comment]
It's definetly something I am going to fix, but there are a lot of things to work on. I want to fix this soon though!

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
