### ISSUE TITLE
Export multi-file selections

### ISSUE THREAD

**Issue by KosmosisDire** [KosmosisDire/obsidian-webpage-export#13]
Support selecting multiple files or folders and exporting those.

**Comment by XinYaanZyoy** [comment]
**Feature Request**: an ability to ignore specific files or directories (while exporting with the `multi-file website` option).

**Comment by KosmosisDire** [comment]
> **Feature Request**: an ability to ignore specific files or directories (while exporting with the `multi-file website` option).

Hi, thanks. If you could make a new issue for this instead of leaving a comment that would be great!

**Comment by KosmosisDire** [comment]
Closing in favor of #157
