### ISSUE TITLE
Show note title despite H1 header

### ISSUE THREAD

**Issue by rubslopes** [KosmosisDire/obsidian-webpage-export#132]
There's a toggle for including the note title in the export IF the note doesn't start with an H1 header. I know many people use H1 for note title and start topics with H2, but in my notes I start topics with H1. I'd like the option to include the title nevertheless. 

Currently, I am temporarily copying the note title as the first H1 as a workaround just for the export, and then I delete it.

Thank you for the awesome plugin! I just contributed to it.

**Comment by KosmosisDire** [comment]
Thank you! :)

I don't really want to add a second option to force adding the title, just because that makes the settings messy. And I can't remove the check to see if it already has a title because some people may have some notes with a title already while other notes don't. 

I would like to support this though, so I will try and think of a solution for this.

**Comment by rubslopes** [comment]
Understood. Thank you for taking the time to reply!

Em qua., 7 de jun. de 2023 18:07, Nathan George ***@***.***>
escreveu:

**Comment by elkalt** [comment]
Could be a dropdown ie. "Include note title in export" with options "Always", "Never", and "If H1 header doesn't exist"?  Shouldn't make the options too messy like that, it still only takes up one line until the dropdown is opened.

**Comment by KosmosisDire** [comment]
> Could be a dropdown ie. "Include note title in export" with options "Always", "Never", and "If H1 header doesn't exist"? Shouldn't make the options too messy like that, it still only takes up one line until the dropdown is opened.

Thank you, this is a good idea!

**Comment by KosmosisDire** [comment]
> This class is always hidden, regardless of the configuration. Please, fix it!
> 
> ```css
> .mod-header {
>     display: none!important;
> }
> ```

This is already changed in the next version. You can try the beta in the github releases, or wait until the next release. However I am not sure why you would want to show the mod-header?

**Comment by rafageist** [comment]
@KosmosisDire As the configuration option says, I need to show the filenames as the page header if the page does not have a header. I don't want the first paragraph to appear without a header and I don't want to repeat the name of each file as a header. I have checked that option and it doesn't work. I realized that they always hide.

**Comment by rafageist** [comment]
@KosmosisDire I confirm that the beta version solves this problem and has many other improvements. Thanks.

**Comment by KosmosisDire** [comment]
Okay great, glad the beta solved it! :)

**Comment by KosmosisDire** [comment]
This problem this feature would have addressed has been solved in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
