### ISSUE TITLE
Accented URL name

### ISSUE THREAD

**Issue by ThomasLudwig** [KosmosisDire/obsidian-webpage-export#133]
Hi, 

the latest version of the plug-in is a real improvement for me (it's super fast !!) but it behaves a bit differently from the previous version I used :

My page being in French, I sometimes have accented characters (é è à ê ù ...) in my **H1** and the url/file names aren't well handled on Linux (it work well in Win11's explorer) 

This leads to a 404. For example if my page has a 
- H1 "vis-à-vis"
- the url is "vis-à-vis.html"
- the filename is 'vis-'$'\340''-vis.html'
- when I click the link --> 404

It works however after I do `mv 'vis-'$'\340''-vis.html' "vis-à-vis.html"`

---

So I think there's a mismatch between the encoding of the character in the filename and the url. 
For me (apache2/Ubuntu 22.04) it would work if the accented character was used  directly in the filename, but it might not work on every server.

The same page was handled without issue on the previous version of the plugin I used (but I can't remember which one it was)

**Comment by KosmosisDire** [comment]
Hmm okay thanks, I will certainly check this out. This has been a repeated problem that I have to keep fixing, so I am not surprised it is back haha.

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
