### ISSUE TITLE
Export note with SVG as self-contained documents

### ISSUE THREAD

**Issue by zhyma** [KosmosisDire/obsidian-webpage-export#138]
**Describe the bug**
This might relate to #45 and #55. Files with SVG as self-contained documents are not exported correctly (not sure if "inline" means the same thing).

**Operating System**
Windows 10, Obsidian v1.3.4, Webpage HTML Export version 1.6.0

**To Reproduce**
- The SVG files are created by using Draw.io. I tried to use Powerpoint, which gives me the same result.
- A Obsidian note with SVG images. Export to HTML. Export presets set as "Self-contained Documents".
- Plugin setting: All embedding options are on. Files are completely self-contained.

**Screenshots**

![svg](https://github.com/KosmosisDire/obsidian-webpage-export/assets/2032749/56f3afd4-e1ff-45f0-a281-b6039c75141f)
And here is one of the SVG files that I'm testing.
![w_img](https://github.com/KosmosisDire/obsidian-webpage-export/assets/2032749/6c96dcae-89cb-43bd-9a6a-35302a182669)

**Comment by KosmosisDire** [comment]
This was recently fixed in a pull request and will be fixed in the next release. Thanks!

**Comment by KosmosisDire** [comment]
This should be fixed in v1.7.1! Let me know if you have any problems with it
