### ISSUE TITLE
Support rendering markdown in table of contents titles

### ISSUE THREAD

**Issue by xFrah** [KosmosisDire/obsidian-webpage-export#141]
**Describe the bug**
The latex code i use in my titles is not being rendered in the entries of the table of contents.

**Operating System**
Windows 11

**To Reproduce**
Just make a title and put a latex block in it

**Screenshots**
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/37962249/085b747f-75bf-4470-972d-f6a6f8a7e825)

**Comment by KosmosisDire** [comment]
Thanks, yes the titles do not go through any processing to render mardkown as of right now. I will look into adding this in the future.

**Comment by KosmosisDire** [comment]
This is coming in the next update!
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/39423700/dbaabefd-12e7-42e9-92f6-6d26f27ae593)

You can see that all markdown in headers is now rendered properly including latex

**Comment by xFrah** [comment]
This is so great man, keep up the good work! My friends can enjoy my notes thanks to you <3

**Comment by KosmosisDire** [comment]
This is implemented in v1.7.1! :) Let me know if you have any problems with it
