### ISSUE TITLE
Missing interactive graph in right sidebar.

### ISSUE THREAD

**Issue by RiverOmega** [KosmosisDire/obsidian-webpage-export#143]
**Describe the bug**
After generating self-contained documents with these settings:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/15626786/77ce3db8-e21c-4080-9cf4-ce82b8d3ab9e)

The resulting page is missing the interactive graph in the right sidebar:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/15626786/1bca05fa-e90b-493e-b50c-9ed9664cc364)

If I switch files using the file tree to the left, I can glimpse the graph for a couple of milliseconds before it disappears and all I see is the document outline.

**Comment by KosmosisDire** [comment]
That's because you are probably using the file protocol (aka opening the file locally instead of it being on a server). It says in the description of the graph view that this is not supported. This is because I cannot load web assembly from the local file system, it has to be on a server.

**Comment by RiverOmega** [comment]
Ah, you're right. I thought this only applied for the experimental global graph! I'll close the issue promptly. 

Thanks for answering!
