### ISSUE TITLE
Automatic light/dark theme

### ISSUE THREAD

**Issue by ZepDonald** [KosmosisDire/obsidian-webpage-export#145]
**Is your feature request related to a problem? Please describe.**
I don't like it, when I have to manually change between light and dark theme.

**Describe the solution you'd like**
It would be great to have the option to make switching between light and dark theme automatic, depending on the system settings (information provided by the browser).

**Describe alternatives you've considered**
There is no other alternative.

**Additional context**
No additional context.

**Comment by KosmosisDire** [comment]
This used to be a feature that I have temporarily removed. It will return in the future, but there is more talk about this issue here: #107

**Comment by ZepDonald** [comment]
Thanks for the info. I saw the issue but didn't read all of the comments, sorry about that.

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
