### ISSUE TITLE
Blacklist for Unwanted Exports

### ISSUE THREAD

**Issue by protodrew** [KosmosisDire/obsidian-webpage-export#146]
It would be nice to be able to have a blacklist of notes or folders that wont be included in the export. I want to be able to export the majority of my vault, but don't want to export everything.

**Comment by KosmosisDire** [comment]
Thanks for the suggestion, I do hope to add this in the future!

**Comment by KosmosisDire** [comment]
I am closing this in favor of #157 thanks for the suggestion :)
