### ISSUE TITLE
carets still display next to headings when fold headings is disabled

### ISSUE THREAD

**Issue by protodrew** [KosmosisDire/obsidian-webpage-export#147]
not sure if this should be a bug or feature request, but title explains it all. Not strictly an error, but the caret being there and highlighting on hover makes it look like it will fold even if it is disabled

**Comment by KosmosisDire** [comment]
Interesting, I didn't notice this but I will certainly check it out and fix it. It should be a simple fix

**Comment by KosmosisDire** [comment]
This should be fixed in v1.7.1! :) Let me know if you have any problems with it
