### ISSUE TITLE
MathJax Rendering weirdly or not rendering at all in Safari

### ISSUE THREAD

**Issue by benjitusk** [KosmosisDire/obsidian-webpage-export#148]
**Describe the bug**
MathJax displays weirdly in the produced html files. Sometimes it's not aligned, sometimes it's cut off on top, and sometimes when I scroll really slowly at the bottom of the screen, the MathJax... jiggles? It's pretty weird.

**Operating System**
MacOS 13.4, using Safari
This issue seems specific to safari, as it worked on Chrome.

**To Reproduce**
1. Write MathJax 
2. Export to HTML
3. Open in Safari
4. Weep uncontrollably

**Screenshots**
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/35320919/cf3541f5-3f93-41c7-8b3e-3544993dbfad)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/35320919/5ed54dd3-468a-4016-8905-098e48d711e5)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/35320919/29cbd473-2528-4686-b041-65075a2a67ad)

Sometimes the mathjax entirely fails to render at all:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/35320919/59bfb7f2-7505-4766-be25-2cde98852e81)

**What they look like in Obsidian**
<img width="533" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/35320919/8ad976ca-1aa9-4287-b341-1c926648e08a">
<img width="185" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/35320919/68d2128f-a44b-41f0-84db-4746f2e7e624">
<img width="254" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/35320919/4cd385b4-9f07-4314-8087-f0c007309dfc">

### IMPORTANT: Error Log
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/35320919/c489010a-06ba-432e-8d35-590d12ff7c78)

**Comment by benjitusk** [comment]
When visiting the website on Chrome, these errors show up, and the corresponding network request is blocked. If you want, you can check it out for yourself [here](https://benjitusk.github.io/Computer-Science-Notes/year-i/semester-ii/linear-algebra-i/matrices.html).
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/35320919/2497baa0-b490-4c2e-9789-3dffbdefe083)

**Comment by benjitusk** [comment]
after further testing, the issue where no MathJax renders at all now shows up on chrome. This is the raw .md file.
[Vector Spaces.md](https://github.com/KosmosisDire/obsidian-webpage-export/files/11807768/Vector.Spaces.md)

**Comment by KosmosisDire** [comment]
Thank you for the detailed information! It is hard for me to test on Safari as that requires having a Mac, and MacOS cannot be easily virtualized.

I am curious to see if the math on this page works for you in Safari (go to the Latex header):
 https://nathang.dev/fileshare/misc/graph_view_demo/test/ultimate-test-document.html

I tested this on a friend's iPhone and it seems to work without problem on Safari. Let me know what you see.

I will look into all the info you sent me and see if I can fix this. Thanks!

**Comment by benjitusk** [comment]
It's still unhappy. You can tell if you look closely at the "exp" in the math expression. Also, the graph is broken, but that's a separate issue.

<img width="1826" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/35320919/5bff6e22-53c5-4ad4-b19a-975352e63a95">

**Comment by KosmosisDire** [comment]
> @benjitusk By the way, do you know where I can get the source markdown for this website? There are some neat things in here I want to check out.

It is from the vault I am using to test the plugin. I can upload it somewhere and drop a link here.

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
