### ISSUE TITLE
Only export changed files (incremental build)

### ISSUE THREAD

**Issue by BoyanXu** [KosmosisDire/obsidian-webpage-export#152]
**Is your feature request related to a problem? Please describe.**
[Incremental build](https://www.wikiwand.com/en/Incremental_build_model).

**Describe the solution you'd like**
Use metadata from frontmatter.

**Describe alternatives you've considered**
Use metadata from file itself like [Ninja](https://ninja-build.org/) or other build tools.

**Additional context**
It takes too long to export a huge vault.

**Comment by KosmosisDire** [comment]
This is something I have considered and hope to implement in the future. Thanks!
