### ISSUE TITLE
Export or ignore specific files or directories

### ISSUE THREAD

**Issue by XinYaanZyoy** [KosmosisDire/obsidian-webpage-export#157]
In order to have some other directories and files that are important for the vault but not for the generated site, the user should be able to select which files to export or not export.

I feel like git can be used for making this automatic. `.gitignore` file for the 1st and `git status` for the 2nd. or perhaps some JavaScript function emulating the two.

**Comment by KosmosisDire** [comment]
Thanks, I do plan to address this issue. Likely I will create a single dedicated way to specify which files to export through GUI instead of creating multiple different systems, but using a gitignore could be interesting.

Your second idea is actually more simmilar to #152 if I understand you correctly.

Thanks for the ideas.

**Comment by kaosweaver** [comment]
I would also like to my voice to the ask here. Being able to stop the export of a folder/files would be helpful. (now I manually delete them, but they still exist in the menu system which looks like I have missing pages)

**Comment by KosmosisDire** [comment]
Hey everyone following this issue, work has been started. Here is my prototype so far, let me know if you have feedback on the design here:

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/39423700/b397f295-33ed-4cb3-9fba-aef88bc5e89c)

**Comment by marvinvr** [comment]
@KosmosisDire the design looks great! One thing I'd make sure is that this setting stays persistent, though, so you don't have to select what to export every time you do it. Looks amazing! 💪

**Comment by KosmosisDire** [comment]
@marvinvr Hi thanks, yes this will definitely be persistent. I have also thought about adding presets, so if you have multiple different configurations you can save and load them easily.

**Comment by KosmosisDire** [comment]
@DominikRoB > On the file level: How about doing it using meta data a la "publish: true" and "publish: false" as Obsidian Publish does it?

This is something I am planning on, however I will likely make a different issue for it and implement it in a separate update. But we'll see. Thanks for the idea :)

**Comment by elkalt** [comment]
Would it be possible to do this using a file of regex expressions as well?  For example, I would have a file that I can point to in the export page that looks like this:
```
\d{4} Essays\/.+_final
Notes\/
```
Where each line is a regex expression that matches a path, and just giving a directory exports everything in the directory.

**Comment by KosmosisDire** [comment]
This has been implemented in v1.7.0

**Comment by XinYaanZyoy** [comment]
> Hey everyone following this issue, work has been started. Here is my prototype so far, let me know if you have feedback on the design here:
> 
> ![image](https://user-images.githubusercontent.com/39423700/264194452-b397f295-33ed-4cb3-9fba-aef88bc5e89c.png)

I apologize for the late reply, but can you add the 'select all' button, please?

**Comment by KosmosisDire** [comment]
> I apologize for the late reply, can you add the 'select all' button, please?

I will add this, if you want you can open a new issue for it but it's definetly on my list :)
