### ISSUE TITLE
Files are not exporting due to "Fatal Error"

### ISSUE THREAD

**Issue by thereisnoname18** [KosmosisDire/obsidian-webpage-export#158]
**Describe the bug**
When I try Exporting a file it gives an error. I tried to export other notes but it still gives the same error
**Operating System**
macOS version: 10.15.7

**Screenshots**
my settings page (if required):
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/90173338/4f7145df-f198-424d-b1a6-3105c49bc6fa)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/90173338/2e1dc30f-b3eb-44b1-85b8-7eb5e577e494)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/90173338/ef56312a-fc0b-4299-86f2-e0e740e27b26)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/90173338/e0d8ccf9-6e4f-4d7a-9214-09640afe4655)

**Comment by KosmosisDire** [comment]
You have to update obsidian by downloading the new installer from obsidian's website
