### ISSUE TITLE
Collapsible Callouts don't work on mobile

### ISSUE THREAD

**Issue by shmuelisrl** [KosmosisDire/obsidian-webpage-export#159]
**Describe the bug**
The Collapsible Callouts (drop downs) don't expand while viewing on mobile (or are extremely buggy).
When you try on mobile even when enabling "desktop site" it is still instantly buggy. As well as when you use the Chrome dev tools to simulate a mobile device it doesn't work.

**Operating System**
Export on **windows**

**To Reproduce**
1. Create a Collapsible Callouts 
[with this Syntax:]
``` 
>[!example]- example
>text 
```
3. Then export as html webpage
4. Open up on mobile or emulate mobile 
5. See it's either glichy or not working (worst on actual mobile)

**Comment by KosmosisDire** [comment]
This should be fixed in v1.7.0
