### ISSUE TITLE
Keep checked or unchecked status when export page

### ISSUE THREAD

**Issue by Quorafind** [KosmosisDire/obsidian-webpage-export#16]
Now all the files with checkbox would be exported to page with unchecked checkbox.

**Comment by Quorafind** [comment]
Btw, I found code here: https://github.com/KosmosisDire/obsidian-webpage-export/blob/8379118490acd33f60de326382e608a055460884/assets/webpage.js#L248-L257

will reload checkbox so the `::after` presudo element would be removed
![image](https://user-images.githubusercontent.com/13215013/213102254-9922a8bd-fe6e-4105-8f06-768ec982d827.png)

**Comment by KosmosisDire** [comment]
Yes I have has a lot of trouble with this. Because whenever I get the default checkboxes working it breaks any custom checkboxes that come from other plugins, like kanban or the tasks plugin. It's something I am planning to fix in the next release.

**Comment by KosmosisDire** [comment]
I have now fixed this. Let me know if there are any other problems!

Thanks! :)
