### ISSUE TITLE
Filename is rendered (and editable) inside HTML, even if it is turned off in the settings

### ISSUE THREAD

**Issue by struffel** [KosmosisDire/obsidian-webpage-export#161]
**Describe the bug**
When exporting pages the filename will sometimes get rendered into the page, even if this option is disabled in the settings.
I believe the issue is related to which file was opened most recently, but I haven't been able to nail down the issue.

**Operating System**
Win10 Pro

**To Reproduce**
Create an empty vault with two pages:
A-Page
```
# Header A
Some text.
```
B-Page
```
# Header B
Some text.
```

Export this vault as a website. You will notice that the A-Page has the filename listed at the top, but the B-Page doesn't:

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/31403260/344a94e3-ce3f-45b9-aa0e-86e9ae99c343)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/31403260/f8cacf2d-179d-4f0a-a41b-a22db19a7377)

In addition, the text on the A-Page is somehow marked as editable:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/31403260/efda6e70-12e2-4413-96fc-c8974bd05773)

**Screenshots**
(see above)

### IMPORTANT: Error Log
Nothing to see here really:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/31403260/11de17da-7916-4729-a992-8afd56004653)

**Comment by KosmosisDire** [comment]
Thanks for the report, I'll look into it!

**Comment by KosmosisDire** [comment]
This is fixed, but is replaced by a new bug #202 so I will close this in favor of the new issue
