### ISSUE TITLE
Not exporting attached files such as pdfs, draw.io files, excalidraw files,etc

### ISSUE THREAD

**Issue by Ravindu-Ishan** [KosmosisDire/obsidian-webpage-export#169]
The plugin does not seem to export other attachments such as draw.io files and excalidraw files. Other files such as images seem to be getting exported into the media folder.

Special note - all attachments are in a separate specific folder.

**Comment by KosmosisDire** [comment]
This is related to #95 and #108, excalidraw files and draw.io files would likely need dedicated support which isn't something I plan on adding soon. However, if you embed those files into a note they should show up!

**Comment by KosmosisDire** [comment]
Since this issue is mostly covered by the other two I will close this for now
