### ISSUE TITLE
Alternative Themes: Header underline not under Text

### ISSUE THREAD

**Issue by SuperSchnitzel44** [KosmosisDire/obsidian-webpage-export#181]
**Describe the bug**
When using the ITS theme (and probably any other theme that adds an underline to headers), for any that are not H1 headers, the line appears to the right of the text and not under.

**Operating System**
Windows 11
Obsidian 1.3.7
Theme: ITS-pathfinder

**Screenshots**
orange: H1, blue: H2, red: H3
<img width="407" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/51969065/f727e024-5811-46b9-8056-813dd25cdc16">

With *fixed* html:
<img width="398" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/51969065/7f28f379-a033-418d-8706-01df7912abae">

*I know that this a very specific issue, and not very important, but having found the origin I wanted to share it anyway.*
The shift of underline seems to come from the ```style="display: flex;"``` contained in every `div h2` to `div h6`.
Removing it manually, or within the code *fixes* it.

Is there a specific reason for them to have this style, or am I overlooking something?

**Comment by KosmosisDire** [comment]
Hi, thanks, I beleive I have run into this issue as well with #118. In the case of #118 only part of the header is underlined, and changing the display style to something other than flex causes there to be line breaks when only part of a header is underlined (this is also undesirable). I might have some ways to fix this, but I want to fix both of the problems with one solution.

Thanks for the report though, I wasn't aware that this was also a problem.

**Comment by SuperSchnitzel44** [comment]
Thanks,
I've notices the offset collapse icon with some configuration of "Collapsible Headers" on in Obsidian and "Allow folding heading Disabled" withing the Plugin. (With flex, so no changes) Might look into it a bit later.

**Comment by KosmosisDire** [comment]
This is fixed in v1.7.0!
