### ISSUE TITLE
Error: Failed to execute 'querySelectorAll' on 'Element': 'p:has(div)' is not a valid selector.

### ISSUE THREAD

**Issue by bdwn2215** [KosmosisDire/obsidian-webpage-export#185]
**Describe the bug**
This is a clear and concise description of what the bug is.

Failed to export single file, folder, or vault

**Operating System**
This is my operating system's name.

xubuntu 22.04
Obsidian version 1.4.5

**To Reproduce**
1. right-click file in file tree, select "export to html'
2. Click on click export (doesn't matter which options I use for 'export presets' or 'open after export')
3. save file to where ever, home/documents or same partition as vault

**Screenshots**
If applicable, add screenshots here to help explain your problem (just copy paste)

![Screenshot_2023-09-07_14-10-34](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144389932/433405f4-3522-4ef3-b934-5e97aecddbbb)

### IMPORTANT: Error Log
1. Please open the developer console using (Ctrl + Shift + I), and clear the console using the button at the top left corner.
2. Reproduce the bug
3. Take a screenshot orcopy the error from the console if it has any output and paste it here

[Error] Could not export file: home.md
```
Error: Failed to execute 'querySelectorAll' on 'Element': 'p:has(div)' is not a valid selector.
    at postProcessHTML (plugin:webpage-html-export:10116:10)
    at Object.renderMarkdown (plugin:webpage-html-export:10106:7)
    at async Function.getDocumentHTML (plugin:webpage-html-export:11239:19)
    at async Function.generateWebpage (plugin:webpage-html-export:11179:5)
    at async HTMLExportPlugin.exportFile (plugin:webpage-html-export:11816:7)
    at async HTMLExportPlugin.exportFolder (plugin:webpage-html-export:11856:28)
```

**Comment by KosmosisDire** [comment]
Hi, thanks for reporting this, this is actually answered in the FAQ in the readme:

Q: Why am I getting a fatal error that ":has" is not a valid selector?
A: You need to update obsidian to the latest version by downloading the new installed from obsidian's website.

**Comment by bdwn2215** [comment]
thank you for the quick reply. 

I was updated to the latest version (at this time v1.4.5) and the plugin was still not working... (but I fixed it and here's how)

I noticed my installer version was still 15.9, so I had to uninstall obsidian and reinstall it with the latest installer and everything is working. 

![Screenshot_2023-09-07_14-27-24](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144389932/698b2a68-6bba-4e7f-adf6-63927f3c0ad5)

![Screenshot_2023-09-07_14-29-56](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144389932/d273763e-ee7d-4c36-968a-3c479e11687c)

This article explains to download the latest installer instead of using the auto-update feature which I was using to update. [Update Obsidian Installer Version](https://forum.obsidian.md/t/update-installer/6015)

Maybe modify the FAQ to say:

A: You need to update obsidian 'Current version' and 'Installer version' to the latest version. If 'Installer version' is still out-of-date, you need to uninstall obsidian then reinstall with the latest version from obsidian's website.

Thanks again for the quick reply and for managing this plugin.

**Comment by KosmosisDire** [comment]
Hey, thanks it does say: "You need to update obsidian to the latest version by downloading the new installer from obsidian's website." which is pretty explicit that you need to download the new installer. But I will try and make it more clear! Also, be aware that there is currently a breaking bug on the latest version of obsidian, see #183

**Comment by bdwn2215** [comment]
Sounds good and thx for letting know about the bug.

To give more context for the FAQ suggestion, I did read about installing the latest version of obsidian in the FAQ before using the plugin and made sure my obsidian was running the latest version. For that reason I openned up a ticket because technically I was updated to the latest version. 

Anyway, sorry if I'm taking up too much of your time. Here's another way to phrase the FAQ or include in the installation instructions (last post I swear lol)

A: **You need to make sure BOTH obsidian 'Current version' and 'Installer version' is up-to-date** under Settings > About. If not, then you need to uninstall obsidian then reinstall with the latest version downloaded from obsidian's website.

**Comment by KosmosisDire** [comment]
Haha no worries! 

You don't actually have to uninstall it for it to work btw, you can just install it directly. This error also **always** means that your installer version is out of date so there is really no reason to check.

I have updated the readme making it more clear.
