### ISSUE TITLE
Support to export canvas

### ISSUE THREAD

**Issue by I2rys** [KosmosisDire/obsidian-webpage-export#187]
**Is your feature request related to a problem? Please describe.**
Not really but it would be useful and great if canvas could be exported too. Because a lot of people now use it to organize their ideas and thoughts.

**Describe the solution you'd like**
You will be able to export your vault canvas as well as your notes.

**Comment by KosmosisDire** [comment]
This is coming in the next update along with the fix for the obsidian update :)

**Comment by joeymichalik** [comment]
Are you already able to tell more about when the update + fix comes and whats going to be included - just me being a little bit hyped ^^

**Comment by KosmosisDire** [comment]
> Are you already able to tell more about when the update + fix comes and whats going to be included - just me being a little bit hyped ^^

Full mobile support, collapsible sidebars, excalidraw support, and the ability to select exactly which files get exported, and even more than that! :P

**Comment by I2rys** [comment]
> > Are you already able to tell more about when the update + fix comes and whats going to be included - just me being a little bit hyped ^^
> 
> Full mobile support, collapsible sidebars, excalidraw support, and the ability to select exactly which files get exported, and even more than that! :P

Damn that's amazing. I can't wait for the next update! XD

**Comment by KosmosisDire** [comment]
This is now implemented in v1.7.0!
