### ISSUE TITLE
Add mobile support to the sidebars (file tree / table of contents)

### ISSUE THREAD

**Issue by KosmosisDire** [KosmosisDire/obsidian-webpage-export#19]
Add mobile support to the file tree and table of contents.

**Comment by himanshurajora** [comment]
It should be considered, right now both left and right sidebar just disappear in mobile view.

**Comment by KosmosisDire** [comment]
> It should be considered, right now both left and right sidebar just disappear in mobile view.
This is already planned

**Comment by KosmosisDire** [comment]
This is implemented in v1.7..0
