### ISSUE TITLE
Inline title always hidden

### ISSUE THREAD

**Issue by javitab** [KosmosisDire/obsidian-webpage-export#202]
**Describe the bug**
I see the property data appearing in screenshots demo-ing the plugin, but I don't see them in the site that I generate with the plugin.

**Operating System**
macOS

**To Reproduce**
1. Create note with YAML frontmatter
2. Export site
3. Properties do not appear
4. Title is also missing

Actual .md file attached below screenshots.

**Screenshots**
Note in Obsidian
![CleanShot 2023-09-11 at 20 54 26](https://github.com/KosmosisDire/obsidian-webpage-export/assets/14875989/bf24b6d8-e298-47bc-8c96-eeede83b10a1)
Note in exported site
![CleanShot 2023-09-11 at 20 53 44](https://github.com/KosmosisDire/obsidian-webpage-export/assets/14875989/2ed57ec5-11f5-4496-9481-25ea65265a83)
[a_demographics.md](https://github.com/KosmosisDire/obsidian-webpage-export/files/12581340/a_demographics.md)

**Comment by KosmosisDire** [comment]
Also I don't believe there are any demo screenshots that include the properties, where did you see that?

**Comment by javitab** [comment]
File name as title:
![CleanShot 2023-09-11 at 21 08 49](https://github.com/KosmosisDire/obsidian-webpage-export/assets/14875989/bfd2a39e-1efd-4ea5-934d-f8211f6ec6d3)

I could well be mistaken obviously, but [this](https://user-images.githubusercontent.com/39423700/241836412-06d37659-df82-415e-9244-99877ce1924e.png) gave me the impression of properties data.

**Comment by KosmosisDire** [comment]
Ah the 'author' thing is a dataview property, and the tag is just what a tag looks like when you write it inline

**Comment by KosmosisDire** [comment]
Okay, I will look into the title thing, I think I may have accidentally hidden both the properties and the inline title instead of just the properties 😅

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
