### ISSUE TITLE
HTML cannot be exported

### ISSUE THREAD

**Issue by NewTypo** [KosmosisDire/obsidian-webpage-export#205]
**Describe the bug**
HTML cannot be exported

**Operating System**
Windows11

**To Reproduce**
Export any file or ask for quotation folder as html, export fails

**Screenshots**

![Obsidian_Z9OLmZkJKY](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17538796/97e4a8bd-3b0d-4fed-b94c-ef436bcd47ac)
![Obsidian_G6FYIk8mvP](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17538796/087a5eda-9bde-40d3-b139-273f408fae8e)
![explorer_UIq2aPqM4p](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17538796/dd05eff0-cab4-4684-8ab9-b72ddf3c0039)
![Obsidian_pLGwB9FGlu](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17538796/1dd0ba1a-aba8-4afd-accb-9b4b452dec32)
![Obsidian_zvJcO2NYT0](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17538796/571ca1d4-1761-4872-9c8c-19518c375b5d)
![Obsidian_n5GztBU5mP](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17538796/6eb55c3f-b404-4c8b-8e4b-9042df79a35b)

**Comment by KosmosisDire** [comment]
This bug was already reported, it was the latest one before this one haha. See #204 
I am looking into this but I will not be able to fix it immediately.
