### ISSUE TITLE
Embedded pages / transclusions are not exported correctly

### ISSUE THREAD

**Issue by zhoulonghao520** [KosmosisDire/obsidian-webpage-export#207]
Exporting embedded pages cannot be displayed。

**Comment by zhoulonghao520** [comment]
<img width="935" alt="图片" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/bcf3498b-50c5-4dd7-b610-9a021e2ac697">
![图片](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/eda1da0b-7fd1-480f-8cff-6ba30a78d54e)

**Comment by KosmosisDire** [comment]
Yes this is a transclusion, they are broken now because of the internal changed obsidian made in their latest update. I will try to fix it soon, but for now they will not be exported.

**Comment by zhoulonghao520** [comment]
V1.6.0 testing   is ok  ,  I can see anything after exporting (Embed context).
V1.7.1  testing is bug ....

**Comment by KosmosisDire** [comment]
Yes, I understand, no worries. This update (1.7.0) was made to fix changes made in obsidian 1.4.5, so although it worked in version 1.6.0 of this plugin, version 1.6.0 of this plugin does not work in obsidian 1.4.5.

**Comment by KosmosisDire** [comment]
So in other words, I had to rewrite the way that documents are rendered in v1.7.1 to be different than in 1.6.0. This new method does not work with transclusions yet. I had to rewrite it because of the changes obsidian made in v1.4.5

**Comment by zhoulonghao520** [comment]
Okay, I understand. Thank you for your reply. I am currently using the Obstian V1.3.5 and plugin version 1.6.0, which is great!

**Comment by KosmosisDire** [comment]
Okay great! Glad you got a working solution :)

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
