### ISSUE TITLE
Numbered items duplicated and won't load pages

### ISSUE THREAD

**Issue by scottyha** [KosmosisDire/obsidian-webpage-export#208]
My document structure is like this:

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17395837/f5695d06-248b-4aed-b4df-c926f65ef368)

When I export, it looks like this in the HTML structure (note the double "job proposal" pages):

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17395837/9b785419-6a64-466b-9d8c-df72d5c250a0)

But when clicking on any of the links, the name of the page, which includes a number and a "." is included in the HTML filename, so the page doesn't load:

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/17395837/497c8e0c-cb72-4b52-8051-e770c8ca95ab)

It appears this is a new issue, as it seemed to have worked fine in the previous issue.

Keep up the great work!!

**Comment by KosmosisDire** [comment]
Thanks, I will look into this, there were a number of changes that could be causing this behaviour

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
