### ISSUE TITLE
rootPath incorrectly detected as non-absolute

### ISSUE THREAD

**Issue by winterbeef** [KosmosisDire/obsidian-webpage-export#215]
Hello!  I love the plugin.  I appreciate all the work that must go into managing this.

I just installed the newest version and I *still* get an error that seems to stem from `rootPath.isAbsolute` evaluating (incorrectly) to False. 

This prevents any export.

Description:
Invoking the export, I receive the "Generating HTML" and nothing more.

OS
Windows 10, though similar on MacOS

Details:
I open the dev console and see the error is on line #56841.  I set a breakpoint and watch the variable `rootPath`; then run an export again to catch the value of `rootPath`.

I have even simplified matters by creating a new vault in "C:\temp" (very absolute!) and the error persists.

Screenshots and Logs:

<img width="838" alt="console" src="https://user-images.githubusercontent.com/1406941/267480047-b044c18c-10af-4fc0-bd85-daf86ecb9183.png">

<img width="828" alt="rootPath isAbsolute" src="https://user-images.githubusercontent.com/1406941/267480170-79a66569-8b83-4ceb-8449-119d8086cc68.png">

Thank you!

  

```
plugin:webpage-html-export:56844 Uncaught (in promise) Error: folderPath must be absolute: .
    at Utils.downloadFiles (plugin:webpage-html-export:56844:13)
    at HTMLExporter.saveExports (plugin:webpage-html-export:57288:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async HTMLExporter.exportFiles (plugin:webpage-html-export:57261:7)
    at async Object.callback (plugin:webpage-html-export:57382:23)
downloadFiles @ plugin:webpage-html-export:56844
saveExports @ plugin:webpage-html-export:57288
processTicksAndRejections @ node:internal/process/task_queues:96
await in processTicksAndRejections (async)
o_ @ app.js:1
t.onChooseItem @ app.js:1
t.onChooseSuggestion @ app.js:1
t.selectSuggestion @ app.js:1
e.useSelectedItem @ app.js:1
e.onSuggestionClick @ app.js:1
s @ enhance.js:1
plugin:webpage-html-export:56570 failed to find render leaf
```

Indeed, near webpage-html-export:56844:
```
  static async downloadFiles(files, rootPath) {
    if (!rootPath.isAbsolute)
      throw new Error("folderPath must be absolute: " + rootPath.asString);
```

_Originally posted by @winterbeef in https://github.com/KosmosisDire/obsidian-webpage-export/issues/209#issuecomment-1715939094_

**Comment by KosmosisDire** [comment]
Hello! Thank you for this detailed report. What are you setting as the export path originally? Like what text is typed into the box? Are you using forward or backward slashes and are you using double slashes after the disk label? Thanks!

**Comment by winterbeef** [comment]
> What are you setting as the export path originally? Like what text is typed into the box?

I no longer have a textbox to type into; I do not see anywhere in the plugin settings.

<img width="516" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/1406941/493bf1e4-312f-466b-b100-579575277346">

<img width="498" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/1406941/65913a9d-7455-44ae-adf8-c64d951e17d9">

<img width="473" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/1406941/96cfaa58-fbc7-44e6-b5de-a221f726b633">

**Comment by KosmosisDire** [comment]
Ummm, how are you exporting your files then? It is in the main export modal

**Comment by KosmosisDire** [comment]
Oh I guess you are using the export command without actually setting an export path first which causes this error. I should make sure that if the user tries to export with the command before setting anything up it will open the export modal. Or I should add a command to open the export modal. Or both.

**Comment by winterbeef** [comment]
Hello Nathan!

You are correct; I just discovered the webpage export button on the
ribbon.  I have been invoking the export solely via the command palette
previously.

Now that I have added a path in that dialog box, it works!

There are some other wee little things, edge cases, but I will file new
tickets to help keep things tidy.

Thanks so much!

**Comment by KosmosisDire** [comment]
Okay sounds good! Glad it is working, I should modify it so that other's do not make the ssame mistake and trigger the error. I'll look for those new issues
