### ISSUE TITLE
No html is generated

### ISSUE THREAD

**Issue by xsi-dbachmann** [KosmosisDire/obsidian-webpage-export#218]
Exporting multipage or single file does not generate the .html file in the export folder.

**Operating System**
Windows 10
Obsidian 1.4.12
Web HTML Export 1.7.2

**To Reproduce**
1. Export HTML
2. Define output folder
3. Single Page or multipage
4. Export

Single page -> the folder is empty
Multipage -> the folder contains the lib folder but no html

### IMPORTANT: Error Log
loading markdown-table-editor plugin
Error with Permissions-Policy header: Unrecognized feature: 'ch-ua-form-factor'.
plugin:webpage-html-export:57355 loading webpage-html-export plugin
plugin:webpage-html-export:56603 Uncaught (in promise) TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.
    at Object._reportProgress (plugin:webpage-html-export:56603:25)
4plugin:webpage-html-export:56567 failed to find render leaf

**Comment by xsi-dbachmann** [comment]
plugin:webpage-html-export:56567 failed to find render leaf
plugin:webpage-html-export:56603 Uncaught (in promise) TypeError: Failed to set the 'value' property on 'HTMLProgressElement': The provided double value is non-finite.
    at Object._reportProgress (plugin:webpage-html-export:56603:25)
_reportProgress @ plugin:webpage-html-export:56603
await in _reportProgress (async)
progress @ plugin:webpage-html-export:56725
createWithFiles @ plugin:webpage-html-export:55691
await in createWithFiles (async)
processTicksAndRejections @ node:internal/process/task_queues:95
await in processTicksAndRejections (async)
exportFiles @ plugin:webpage-html-export:57250
eval @ plugin:webpage-html-export:57396
await in eval (async)
e.handleEvent @ app.js:1
plugin:webpage-html-export:57324 (12) [_Path, _Path, _Path, _Path, _Path, _Path, _Path, _Path, _Path, _Path, _Path, _Path]
33plugin:webpage-html-export:56567 failed to find render leaf

**Comment by aubreyz** [comment]
This issue is closed but I still have this exact problem with 1.7.3 (Obsidian 1.4.14) - see https://github.com/KosmosisDire/obsidian-webpage-export/issues/204#issuecomment-1751993629
