### ISSUE TITLE
3 dots under headings and unclickable links

### ISSUE THREAD

**Issue by ThomasLudwig** [KosmosisDire/obsidian-webpage-export#220]
Hi,

I have several issues at once

- with the latest version. If there is a blank line after a heading, it is replaced with 3 dots in the same style as the heading.
- Also, the links cannot be (single-left) clicked. Ctrl-Click will open in a new tab, but just a click has no effect.
- The graph and TOC are not up-to-date

**THIS BEHAVIOUR HAPPENS ONLY WITH A FULL SITE EXPORT**, when a single page is exported, everything is generated as expected.

For example:

```
## level 2.a

### level 3

line

- this
- is
- a
- list

## level 2.b

### level 3.b

hello

[[Referents SI INSERM Grand Ouest]]
```

Returns this result

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/14310160/d26616a6-02c2-43b0-82b2-220a9201f6ee)

**Comment by ThomasLudwig** [comment]
Ok, so more precisely, the issue happens when including the vault's "lib" directory in the export

**Comment by KosmosisDire** [comment]
So you have a folder named lib in your vault?

**Comment by ThomasLudwig** [comment]
hmm OK, so I deduce from your question that I shouldn't :D
I guess that at some point the pages where exported (with this directory) inside the vault....

I'll remove it and I guess you can close this non-issue.

Sorry, my bad
