### ISSUE TITLE
Incremental export does not always update file tree correctly

### ISSUE THREAD

**Issue by KosmosisDire** [KosmosisDire/obsidian-webpage-export#223]
The incremental export (only export modified) is supposed to update the file tree of all the unmodified files to match the new one (if files were added or removed). This does not always work.

**Comment by hellpe** [comment]
Not sure if this the right place to ask, but about this specific feature, I noticed that although I have enabled it on my setup, in practice, all of my vault's HTML files are modified and thus appear as updated by my syncing apps, which slows down the syncing process. Is that an intended behavior? How should I update my workflow in that case?

**Comment by KosmosisDire** [comment]
This is probably due to this issue here. Basically if you change any global data it has to update that global data in all the files (I am working on making this not have to be the case) but right now there is a bug that makes it always think global data has changed and so it always updates all files.

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
