### ISSUE TITLE
Icon of callout are not displayed

### ISSUE THREAD

**Issue by WendelinH** [KosmosisDire/obsidian-webpage-export#229]
**To Reproduce**
Create a callout like this:
```md
> [!info] 
> I am a info Callout.
```
And export it. 

**Screenshots** 
![IMG_20230914_124215.jpg](https://github.com/KosmosisDire/obsidian-webpage-export/assets/94523690/11a95f9d-15ec-49b3-9ac2-9852f3cb66f9)

![IMG_20230914_124204.jpg](https://github.com/KosmosisDire/obsidian-webpage-export/assets/94523690/a3e155ff-f07a-4a7b-96b6-0612d417b7d9)

**Comment by KosmosisDire** [comment]
Thanks, I can reproduce this and I will look into it

**Comment by RafaDarque** [comment]
Hello! Any update? Thanks!

**Comment by KosmosisDire** [comment]
Hi, I have a lot of stuff going on and there are lots of bugs to fix. I'll update this issue once progress has been made. Thanks! :)

**Comment by ryran** [comment]
Especially weird: in my experience sometimes some of icons are displayed and other times none of them are.

**Comment by KosmosisDire** [comment]
This issue is fixed in the beta, and will be fixed in the next stable release as well

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
