### ISSUE TITLE
Cannot specify settings when exporting

### ISSUE THREAD

**Issue by elkalt** [KosmosisDire/obsidian-webpage-export#231]
**Describe the bug**
Ever since 1.7 released, I have been missing the option in the command palette to export using new settings:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/44716003/0b464892-e15c-4d87-8844-27f2d4152f3e)

Since I never got the chance to specify files to export, it just hangs forever.
Reinstalling does not resolve the issue.

**Operating System**
Both Debian Sid/Trixie and Windows 10

### IMPORTANT: Error Log
When trying to export using the only option:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/44716003/a39428e9-b3eb-4f27-88b7-2e377c5dfdcc)

**Comment by KosmosisDire** [comment]
Hi thanks, this has been reported a couple times. The solution is to open the ribbon menu or right click on a file and select export. I will make sure to include a command to set the settings, and open the settings if the user hasn't set it before in the next update.

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
