### ISSUE TITLE
Add support for external images in themes

### ISSUE THREAD

**Issue by Pro-methius** [KosmosisDire/obsidian-webpage-export#232]
I am experiencing a recurring problem where the custom background image does not appear in the exported files. Interestingly, if I use an image included in the theme, such as the default blue topaz backgrounds, they work perfectly fine. However, when I attempt to add an external image link to themes like blue topaz or anupuccin, the exported background turns into a solid color based on the preset color.

**Comment by KosmosisDire** [comment]
Hi, thanks, external images on themes are not exported, I would have to add specific support for this scenario and I have not.

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
