### ISSUE TITLE
Can't export file : TypeError null / Metatable plugin

### ISSUE THREAD

**Issue by matclab** [KosmosisDire/obsidian-webpage-export#233]
**Describe the bug**
Exporting a file or a directory fails with the error `TypeError: Cannot read properties of null (reading 'style')`

**Operating System**
Arch Linux

**To Reproduce**
1. Export file as HTML
2. see error in the new window

**Error Log**
The problem Log says :
```
##### [Error] Could not export file: Conformité ISO27001.md
TypeError: Cannot read properties of null (reading 'style')
```

And the console :
![2023-09-18T10:01:48+02:00](https://github.com/KosmosisDire/obsidian-webpage-export/assets/985910/0ef8d0cc-2e0a-4865-a792-ec3001be2968)

**Comment by KosmosisDire** [comment]
Could you try exporting this with the metatable plugin disabled? Or try exporting in a sandbox vault? Thanks

**Comment by matclab** [comment]
Yes, good catch (I wonder how I didn't see this myself… Must be a bit tired).
I can live without this plugin (and then do not hesitate to close the bug), but if you need some more information, debugging or testing in order to make it compatible I can try to provide some help.

Thank you for this nice and useful plugin, and for your help.

**Comment by KosmosisDire** [comment]
I think I'll leave it open for now in case it helps others, I don't feel like it is worth it to try and track down the error at this moment though. Thank you for the report though!

**Comment by KosmosisDire** [comment]
I will go ahead and close this since it has been resolved
