### ISSUE TITLE
"Add filename as title" does not seem to do anything

### ISSUE THREAD

**Issue by hellpe** [KosmosisDire/obsidian-webpage-export#234]
**Describe the bug**
Regardless of the state of the "Add filename as title" toggle in the plugin settings, my rendered pages  (uploaded here: https://carnet.pointecouteau.com/) don't display the filename as the page title, although my Markdown files do not have any h1 title.

**Operating System**
Fedora Silverblue 38

**Screenshots**
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1238320/c69506b8-c8ba-4df1-b267-72c543c16432)

**Comment by KosmosisDire** [comment]
Hi this is related to #202, it will be fixed in the next release.

**Comment by XinYaanZyoy** [comment]
Hi, @KosmosisDire, just a quick question: I just discovered this issue in my instance (using it after a long time though). previously titles worked fine for me (file names as titles), but they're not appearing now at all! I hope it's coming out in .4?

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
