### ISSUE TITLE
select all button for the export selection

### ISSUE THREAD

**Issue by XinYaanZyoy** [KosmosisDire/obsidian-webpage-export#236]
**Is your feature request related to a problem? Please describe.**
If I install the plugin on a vault of hundreds of notes, it seems hopeless to use the plugin without the 'select all button'. 

**Describe the solution you'd like**
select all and deselect all buttons

**Additional context**
it'd be [personally] a great help if a minor version(1.7.4?) is released soon.

**Comment by KosmosisDire** [comment]
Thanks, I will implement this. I do have bad habit of clumping everything into major version releases 😅 but I will try and get this (as well as other fixes) out as minor versions.

**Comment by KosmosisDire** [comment]
Hi this is implemented on the 1.7.4 branch, but I would rather not release 1.7.4 yet as there are still some bugs to work out. If you'd like the feature now you can build that version. Or would it be helpful if I was to release a beta version?

**Comment by XinYaanZyoy** [comment]
hey hi! it's fine, take your time! I've managed my case for now. official build/version would be better for everyone, so just do that if you have to ask me, which I hope will be released in the next couple of months, ya?

**Comment by KosmosisDire** [comment]
Yeah should be released in the next couple months. I like to keep issues open until they are on the official release sso I don't get duplicates. Hence the "implemented" tag :)

**Comment by deeplook** [comment]
This is only to upvote this. I have around 70 pages now and am planning for many more, and checking all of them manually each time is not an option, but makes me look for alternatives.

**Comment by KosmosisDire** [comment]
@deeplook 

If you want to try the beta this feature is already implemented there :)
Otherwise it will be available in the next release

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
