### ISSUE TITLE
export local graph instead of global graph

### ISSUE THREAD

**Issue by luckyHarry** [KosmosisDire/obsidian-webpage-export#238]
my vault is pretty big , so a global graph is huge  ,baisclly we have a left sidebar to show all the file , thats enough for navigation , on the right up corner , it will be super usefull  to have just a local graph (if can custom link depth would be great ). this local graph is a concise outline of the article itself.
i found in many case , a global graph is not much use if they are too big .

**Comment by KosmosisDire** [comment]
Thanks, this is a duplicate of #77
