### ISSUE TITLE
Custom head content

### ISSUE THREAD

**Issue by I2rys** [KosmosisDire/obsidian-webpage-export#241]
**Is your feature request related to a problem? Please describe.**
Every time I install webpage export I have to change the meta in the head in the plugin code to a code I want because the default one isn't exactly what I want. The point is that it would be nice if we had control over the head content so we could change the title, icon, color, and etc with what we like.

**Describe the solution you'd like**
Uses custom header code provided by the user and a save button. Thank you!

**Comment by KosmosisDire** [comment]
As far as colors though, snippets are included in the export so you can modify the styles any way you want with snippets
