### ISSUE TITLE
Why does a white area appear at the top. V1.6.0

### ISSUE THREAD

**Issue by zhoulonghao520** [KosmosisDire/obsidian-webpage-export#243]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/9523e4a6-fe1c-46b2-9082-e105c6b3c503)

Why does a white area appear at the top. V1.6.0, is this area considered for other purposes? May I ask how to adjust CSS to remove it

**Comment by KosmosisDire** [comment]
Hi, is this always here? Or only on this specific note? Is it possible for you to send me the html file? Thanks

**Comment by zhoulonghao520** [comment]
[AnyBLOCK.html.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/12744903/AnyBLOCK.html.zip)

**Comment by KosmosisDire** [comment]
Hi I beleive this would be fixed in the latest update. Can you not use the latest version of the plugin?

If you can not you should be able to include the following css snippet in your export:

```
body
{
    padding: 0 !important;
}
```

**Comment by zhoulonghao520** [comment]
<img width="1001" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/071490cc-b0fa-46b5-9f4f-96f8588756a8">
<img width="296" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/652dded5-46dd-4323-b8ab-f1fa20d1f380">


I tried the V1.7.3 plugin. I feel like he doesn't have as good a user experience as V1.6.0. The main points are as follows:

1. Incompatible dataview style (table border spacing issue)

2. As long as the folding panel function switch is turned on once, there is always a folding effect after exporting, even if I set it to off, it still has no effect

3. When exporting, the folder on the left displays images and other information (I don't actually need them, but I need to check and remove them from the selection file, which is time-consuming, although checking can save)

**Comment by KosmosisDire** [comment]
Hi thanks, could you elaborate on points 1 and 2? What **should** the dataview look like vs. how it looks in the export? What is the folding panel switch? Do you mean the collapsible sidebars? Or do you mean the file explorer's "collapse all" button? Could you descibe the behavior that you are getting more or send a video of it occuring?

As far as the third point that is something I am looking into improving. Thanks :)

**Comment by KosmosisDire** [comment]
Also let me know if the solution with the snippet works, thanks

**Comment by zhoulonghao520** [comment]
<img width="1008" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/f78fea13-c331-4e4e-bac2-c030a155ffac">

dataview style 

V1.6.0 style
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/0f564f1d-3077-4416-84c6-675d1ebd7247)

**Comment by zhoulonghao520** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/a36757d3-3393-4d38-b2d2-08df6eca68e6)

**Comment by KosmosisDire** [comment]
You have to do a full export for many settings to take effect (by turning off the only export modified option). That includes the sidebar always collapsing. I am working on improving this, but for now when you change settings it's a good idea to do a full export.

**Comment by KosmosisDire** [comment]
You have reinstalled the plugin and what is gone?

**Comment by zhoulonghao520** [comment]
I uninstalled the v1.7.3 plugin; After reinstallation,



Selecting the entire folder to fully export the side bar folding settings is valid,



If the media folder is checked and removed, the side bar folding function will appear, even if it is turned off.

**Comment by zhoulonghao520** [comment]
I use [obsidian-custom-classes](https://github.com/LilaRest/obsidian-custom-classes)

The style disappeared when exporting in version 1.7.3

`.pagename-auto-title`xxxxx-需求规格说明书<br/>[[01_xx增加xx字段]]

**Comment by KosmosisDire** [comment]
I am not 100% sure I follow. You're saying that if you:

1. Export your vault with the "Media" folder selected the sidebars are not collapsible.
2. Deselect the media folder and export again

Then the sidebars are always collapsible?

The sidebars will make themselves collapsible when the sceen size is too small no matter what that setting is set to, is it possible that you are resizing the window to be small so that the sidebars allow themselves to be collapsed?

**Comment by KosmosisDire** [comment]
> I use [obsidian-custom-classes](https://github.com/LilaRest/obsidian-custom-classes)
> 
> The style disappeared when exporting in version 1.7.3
> 
> `.pagename-auto-title`xxxxx-需求规格说明书[[01_xx增加xx字段]]

I don't have official support for this plugin so I am not sure what changes may have effected this. There is a good chance that the next update will fix this however. (The next update will also fix your other issue #207)

**Comment by zhoulonghao520** [comment]
width=2000

<img width="832" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/fc88b8b5-1c3c-4fb0-86a2-751db0be64bd">


Do you mean that when the window width exceeds, a sidebar will automatically appear. Even if I turn off the settings

**Comment by KosmosisDire** [comment]
Are you trying to avoid the sidebars appearing? Or are you trying to avoid the sidebars being able to collapse? 
When the window gets thin enought that there is no longer space for both the sidebars and the document the sidebars will allow themselves to be collapsed.

**Comment by zhoulonghao520** [comment]
I set the width to 1700, and this issue is resolved. Thank you very much.

**Comment by KosmosisDire** [comment]
Okay great!

**Comment by zhoulonghao520** [comment]
> > I use [obsidian-custom-classes](https://github.com/LilaRest/obsidian-custom-classes)
> > The style disappeared when exporting in version 1.7.3
> > `.pagename-auto-title`xxxxx-需求规格说明书[[01_xx增加xx字段]]
> 
> I don't have official support for this plugin so I am not sure what changes may have effected this. There is a good chance that the next update will fix this however. (The next update will also fix your other issue #207)

I did not find this issue in the use of V1.6.0

**Comment by KosmosisDire** [comment]
Yeah, there were a lot of changes between 1.6 and 1.7 that may have caused this to break. I cannot go back to the way that 1.6 worked though because of the changes that obsidian made.

But I mean that I have fixed a number of bugs that are not yet released that are likely to fix that issue. But that will be in the next release that is not out yet.

**Comment by zhoulonghao520** [comment]
I understand your point. I plan to temporarily use the old version and wait until it is relatively mature before using the new version. The V1.7.3 version is as simple to operate as V1.6.0. V1.6.0 has better compatibility with my current document CSS.

Your plugin is really excellent and has helped me a lot in my work. I no longer use OFFICE

**Comment by KosmosisDire** [comment]
Yeah that is probably reasonable, I am considering releasing betas for future major updates instad of releasing them outright. I am glad you are finding the plugin useful :)

It should get more stable with each new release (and I will hopefully be able to improve the convenience of the newer versions). It is difficult to balance simplicity with number of features!

Thanks! :)

**Comment by zhoulonghao520** [comment]
> body
> {
>     padding: 0 !important;
> }

<img width="1790" alt="图片" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/a42fbdd4-a1bb-4f22-ba30-bdb3c20dec9b">

 is OK  but....
 
![图片](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/aaac5f21-f0d6-4071-8290-285810668456)

**Comment by KosmosisDire** [comment]
You could try:

```css
body:has(.webpage-container)
{
    padding: 0 !important;
}
```

**Comment by zhoulonghao520** [comment]
great! The problem has been resolved。Thank you very much！

**Comment by zhoulonghao520** [comment]
I just upgraded my observer to the latest version and tried using v1.7.3 export related functions. However, I found the operation quite complicated, so I reinstalled it back to v1.3.5。

V1.6.0 feels very good to use. There will be time for testing V1.7.3 and subsequent versions later.

**Comment by KosmosisDire** [comment]
I will go ahead and close this since I am no longer maintaining the system pre 1.7
