### ISSUE TITLE
Markdown referenced file can not be displayer 

### ISSUE THREAD

**Issue by neurusuv** [KosmosisDire/obsidian-webpage-export#244]
**Is your feature request related to a problem? Please describe.**

For exaple , in the examle.md, I added 

```
![name](name.md)
```
In obsidian, the content of name.md is displaced inside example.md.

But in generarted HTML, they are disapeared.

**Comment by zhoulonghao520** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> For exaple , in the examle.md, I added
> 
> ```
> ![name](name.md)
> ```
> 
> In obsidian, the content of name.md is displaced inside example.md.
> 
> But in generarted HTML, they are disapeared.


https://github.com/KosmosisDire/obsidian-webpage-export/issues/207

I feel like it's the same problem。

**Comment by KosmosisDire** [comment]
Yes this is a duplicate so I will close it. This issue will be fixed in the next update
