### ISSUE TITLE
MacOS Sonoma - export broken

### ISSUE THREAD

**Issue by maxswisher** [KosmosisDire/obsidian-webpage-export#247]
**Describe the bug**
Export is not providing progress bar, says completed but only lib directory created at target. screenshot of success notification included. 

**Operating System**
Mac OS Sonoma 14.0

**To Reproduce**
1. Export using right click menu, or commands menu
2. Loading screen does not display, notification of success appears, only lib directory is at target

**Screenshots**
If applicable, add screenshots here to help explain your problem (just copy paste)
![Screenshot 2023-10-02 at 5 14 26 PM](https://github.com/KosmosisDire/obsidian-webpage-export/assets/126510846/7338ee27-8e97-4993-af60-91b62219622e)

### IMPORTANT: Error Log
Screenshot below, saved to attached log file. 
![Screenshot 2023-10-02 at 5 16 15 PM](https://github.com/KosmosisDire/obsidian-webpage-export/assets/126510846/416ed0b6-f2e3-469e-ae9c-cb5d034de707)
[htmlexport.log](https://github.com/KosmosisDire/obsidian-webpage-export/files/12786538/htmlexport.log)

**Comment by KosmosisDire** [comment]
Thanks, it is hard for me to reproduce bugs on mac since I do not own a mac and there isn't much to go off of here. Can you try installing just this plugin into an empty vault and exporting a simple file to see if it is still reproduced there? Thanks!

**Comment by maxswisher** [comment]
Great suggestion - looks like I have some other plugin or other confounding issue in my main vault. 

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/126510846/dfb88ec9-a5e4-4960-897a-13961a2c1dcc)

The check list which appears to the left was not appearing in my main vault. Once I check a box and hit export, it does work. _however _ there is a different issue - Obsidian itself (including the developer console) is completely frozen once the export completes. 
This is what I see when it's completely frozen. I did change log setting to verbose - does that log go somewhere other than the console?
![Screenshot 2023-10-02 at 5 30 48 PM](https://github.com/KosmosisDire/obsidian-webpage-export/assets/126510846/4289f49e-1073-48ec-910b-f30914d53ff6)

I'll go ahead and flip some switches on other plugins in my main vault to see if I can determine if one of them is the culprit, will let you know. Thanks for your help.

**Comment by KosmosisDire** [comment]
Yes I have encountered the freezing issue and I am trying to find a fix for it, it only seems to happen sometimes and it is quite random. But the freexing doesn't stop the export from working it just forces you to restart obsidian. I hope to fix that issue int he next update because it is quite a serious problem haha.

Glad you've got it working though and let me know if you figure out which plugin was conflicting!

**Comment by maxswisher** [comment]
I'm having a hard time replicating *both* of the issues above. I turned all of my plugins off and back on one by one, and it seems that the list w checkboxes is presenting each time. (The initial bug was simply that I was unable to select any of the checkboxes). And as you just mentioned, the freezing is totally intermittent. 

I'll let you know if I ever figure out if it was a plugin, or some other intermittent issue. Best of luck chasing down the freezing issue. Really appreciate you jumping on this - and if you would ever like someone with a Mac to test things on, I am happy to play around. Fantastic plugin you've created & are maintaining!

**Comment by KosmosisDire** [comment]
Thank you! :) 
I'll certainly let you know if I need something tested. Also I'll be releasing a beta soon with a bunch of fixes, so if you want to try the beta to see if it fixes anything you can use the BRAT obsidian plugin to add the beta version once it is out.
