### ISSUE TITLE
Link jump failed

### ISSUE THREAD

**Issue by mmkxyu** [KosmosisDire/obsidian-webpage-export#25]
When the publishing folder contains multiple md files, multiple html will be generated. At this time, open the html with double links and click jump. The jump url has an md before the html prefix. This md should be removed, otherwise the link jump fails

**Comment by mmkxyu** [comment]
I use the latest package. With this problem, I edit the generated html file, remove the .md in the link url, and the link can jump successfully

**Comment by KosmosisDire** [comment]
Thanks for this report

**Comment by KosmosisDire** [comment]
This has been fixed in the latest update. Thanks for letting me know about this!
