### ISSUE TITLE
Canva files label

### ISSUE THREAD

**Issue by I2rys** [KosmosisDire/obsidian-webpage-export#250]
**Is your feature request related to a problem? Please describe.**
Yes because It's hard to identify which file is a canvas and not.

**Describe the solution you'd like**
Just add a little label near the canvas file so we can Identify that It's a canvas file.

**Comment by KosmosisDire** [comment]
Hi, thanks I plan on adding this  :)

**Comment by I2rys** [comment]
> Hi, thanks I plan on adding this :)

No probs. :D

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
