### ISSUE TITLE
The export process block with a blank page V1.7.3

### ISSUE THREAD

**Issue by EasterFan** [KosmosisDire/obsidian-webpage-export#251]
**Describe the bug**
obsidian version：v1.4.14
webpage-html-export version：1.7.3
machine: macOS Ventura 13.2.1

When plugin upgrade to version 1.7.3, this bug shows all the time. The export process block with a blank page for a several minutes and finally failed.

- Tried to reinstall the plugin - didn't work
- Tried to delete plugin folder in .obsidian directory  -  didn't work

I tried to find the reason from error log, but I don't know the log's location. Could you tell me the log's directory?

Thank you for any reply!

<img width="1089" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/28798206/634fb79e-ff8f-4666-b5e2-607818a3f054">

<img width="1028" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/28798206/64259c7f-e6b8-4f4e-b01c-064fcde5f6e0">

**Comment by aubreyz** [comment]
Similar here on updating to 1.7.3 see https://github.com/KosmosisDire/obsidian-webpage-export/issues/204#issuecomment-1751993629

**Comment by EasterFan** [comment]
@aubreyz Thank you for reply! 

I fixed this by downgrade  both obsidian and webpage-html-export plugin to :

obsidian version: 1.3.7  
webpage-html-export: 1.6.0
 
this is a really good plugin and waiting for author's good news

**Comment by aubreyz** [comment]
> this is a really good plugin and waiting for author's good news

Yup it's the best ever. Maybe we need small incremental changes in future!

**Comment by KosmosisDire** [comment]
Hi, this is likely due to a bug which does not prompt you to set the export option when you are using the command to export files. I will release a beta today that should fix this issue. In the mean time can you try exporting using the ribbon icon instead. Thanks.

**Comment by KosmosisDire** [comment]
> Yup it's the best ever. Maybe we need small incremental changes in future!
I am working on small incremental changes as well, but some features have to come in large batches just because of the stuff that needs to change in the plugin to support those changes as well as the time I have to work on the plugin usually being clumped together into small bursts. I am trying to find time to do incremental fixes though.

**Comment by aubreyz** [comment]
> > Yup it's the best ever. Maybe we need small incremental changes in future!
> 
> I am working on small incremental changes as well, but some features have to come in large batches just because of the stuff that needs to change in the plugin to support those changes as well as the time I have to work on the plugin usually being clumped together into small bursts. I am trying to find time to do incremental fixes though.

That's not what I meant in fact -- I meant you should do less work... and more slowly. Was meant as a sort of backhanded compliment.

**Comment by aubreyz** [comment]
> Hi, this is likely due to a bug which does not prompt you to set the export option when you are using the command to export files. I will release a beta today that should fix this issue. In the mean time can you try exporting using the ribbon icon instead. Thanks.

By export option do you mean not choosing as export path - I'm definitely setting that. However if I use the Ribbon I get the box to select the file, and then it does work just fine.

**Comment by KosmosisDire** [comment]
> That's not what I meant in fact -- I meant you should do less work... and more slowly. Was meant as a sort of backhanded compliment.

Oh haha, well in that case thank you😅 working slower does usually end up with less bugs which is what I thought you meant

**Comment by KosmosisDire** [comment]
> By export option do you mean not choosing as export path - I'm definitely setting that. However if I use the Ribbon I get the box to select the file, and then it does work just fine.

Curious, that is what I meant and it should work if it is set. Are you saving the file selection as well?

**Comment by aubreyz** [comment]
> > By export option do you mean not choosing as export path - I'm definitely setting that. However if I use the Ribbon I get the box to select the file, and then it does work just fine.
> 
> Curious, that is what I meant and it should work if it is set. Are you saving the file selection as well?

In the old version I get this via the 3dot menu

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/25100168/0839ff44-284a-4b31-b648-c4e627db8141)

In the new version I get this via the 3dot menu, ie. the same dialog as via the ribbon. However, mostly (but curiously not always) the left side popup box that I get via the ribbon is missing so not completed. 

![Clipboard-20231008](https://github.com/KosmosisDire/obsidian-webpage-export/assets/25100168/029d3ccf-3f40-4304-b6e5-3ea3b15fa2cc)

Either way the export path is completed (in my case downloads\test)

**Comment by KosmosisDire** [comment]
Hmm, can you take a screenshot of the log when the left box fails to come up? Are there any errors?

**Comment by aubreyz** [comment]
> Hmm, can you take a screenshot of the log when the left box fails to come up? Are there any errors?

See https://github.com/KosmosisDire/obsidian-webpage-export/issues/204#issuecomment-1751993629
For complete console log between starting up three dots, getting just right side of above dialog pair, and pressing "Export" (and getting a blank output with no HTML file)

**Comment by piyuranjan** [comment]
> Hi, this is likely due to a bug which does not prompt you to set the export option when you are using the command to export files. I will release a beta today that should fix this issue. In the mean time can you try exporting using the ribbon icon instead. Thanks.

Can confirm that exporting via the ribbon icon works until there's a fix for the command. The command export is more streamlined for single page exports though.
Thanks for making and continuously working on this wonderful plugin!

**Comment by KosmosisDire** [comment]
I actually have this problem fixed already in the code, the update should be coming soon

**Comment by pimony** [comment]
I created a sample note for export and a folder on my desktop to export the html page. I choosed single page html export. The export failed (folder empty). Using the latest version of the plug in, Windows 10 OS. Latest version of obsidian.

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
