### ISSUE TITLE
(1.7.3) Single page export - without folder structure

### ISSUE THREAD

**Issue by stefanpausch** [KosmosisDire/obsidian-webpage-export#254]
I would love to get the old behavior (pre 1.7.x), of exporting single pages, back:

if i export a single page with 1.7.x it is put in under a folder structure, reflecting the page structure. i would love to put the single page in the root directory (make this logic toggle able)

(optional) i would see the option to name a single exported page differently (f.e. index.html) 

thanks a lot

**Comment by KosmosisDire** [comment]
Hi this will be fixed in the next update

**Comment by danielo515** [comment]
I was also about mentioning the same. The convenience of export the current note is what I use the most

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
