### ISSUE TITLE
Load documents from the sidebar via AJAX instead of navigating to a new page

### ISSUE THREAD

**Issue by hannahildebrandt** [KosmosisDire/obsidian-webpage-export#257]
Building on https://github.com/KosmosisDire/obsidian-webpage-export/issues/210

When you navigate between documents, it always opens them on a new page, which means that you lose your position in the sidebar's outline. This can make navigating complex vaults extremely annoying.

One solution would be to have a single main index page that displays documents via AJAX requests, instead of reloading the entire page every time. This way the sidebar never needs to be reloaded, and would open up some options for further customization (you could inject custom HTML or CSS into that index page and it would affect everything, instead of having to do it to every documents that gets exported).

Another option would be to highlight the current document in the sidebar, and have the parent folders expanded by default so you can always see where the current document exists in the tree.

**Comment by KosmosisDire** [comment]
This is already how it works, however you cannot use ajax in local files so it falls back on navigating to the page instead when opened locally. Ajax / fetch only works on an http server

**Comment by hannahildebrandt** [comment]
Well, egg on my face. That's what I get for not actually trying it on a server first. Thanks for following up so quickly!
