### ISSUE TITLE
When I want to print out the html file, I can only display the first page

### ISSUE THREAD

**Issue by veryqun** [KosmosisDire/obsidian-webpage-export#258]
**Describe the bug**
When I want to print out the exported html file, I can only display the first page
And I noticed that the Sliding block in the exported html file is different from other pages

**Operating System**
macOs Sonoma 14.0

**To Reproduce**
1. open the html file in browser
2. Click on print (command + p)

**Screenshots**
https://res.cloudinary.com/ds2agvour/image/upload/v1696994018/cak3jbp9lew0wnvoho7g.png

### IMPORTANT: Error Log
Print in chrome so there is no log for Webpage-export

**Comment by KosmosisDire** [comment]
Thanks I am aware of this and it will be fixed in the next update
