### ISSUE TITLE
An option to disable animations

### ISSUE THREAD

**Issue by lowlight-ua** [KosmosisDire/obsidian-webpage-export#263]
It is jarring to have the sidebars slide in every time a link is clicked and the new page is opened.

The animations should be optional; perhaps, a toggle in the settings would be in order.

I considered tweaking the CSS of the exported vault manually, but the animations seem to be embedded pretty deep into the way the page is rendered.

**Comment by KosmosisDire** [comment]
Hi thanks, this is a duplicate of #210, so I will close it in favor of that issue. This problem only occurs on files opened locally, and not on a web server.

**Comment by lowlight-ua** [comment]
I _thought_ I searched for duplicates! Sorry for the noise and thanks.
