### ISSUE TITLE
canvas export fail

### ISSUE THREAD

**Issue by yuanzhimengbian** [KosmosisDire/obsidian-webpage-export#266]
##### [Error] Rendering k-means/k-means思维导图.canvas failed: 
```
TypeError: Cannot destructure property 'infoList' of 'bridgeEl' as it is null.
```

**Comment by KosmosisDire** [comment]
Hi you don't give any information about what is wrong and this error doesn't help me much. If you could fill out the issue template it would be helpful. Thanks

**Comment by KosmosisDire** [comment]
Will close unless more information is provided. Feel free to reopen
