### ISSUE TITLE
Graph view broken if document outline is disabled

### ISSUE THREAD

**Issue by otherstew** [KosmosisDire/obsidian-webpage-export#267]
**Describe the bug**
If you exported a Multi-File website with 'Document Outline' disabled, then clicking on nodes in the graph view results in an endless loading animation.

**Operating System**
- Kubuntu 22.04
- Obsidian 1.4.16 (snap)

**To Reproduce**
1. Create a vault, add some files
2. Disable Document Outline in the plugin settings
3. Export all files using the Multi-File website prefix
4. Serve files, navigate browser to wherever files were served
5. Click on a node on the grap
6. The loading animation (three dots) appears and doesn't go away, also you get a console error (see screenshot below for both)

**Screenshots**
![Screenshot_20231021_083210](https://github.com/KosmosisDire/obsidian-webpage-export/assets/135083158/c14dc5dc-506d-4f83-aef0-d79b725572e0)

**Comment by KosmosisDire** [comment]
Thank you, I think I know what's causing this and I'll try to fix it

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
