### ISSUE TITLE
Using back button causes endless loading

### ISSUE THREAD

**Issue by oldjove** [KosmosisDire/obsidian-webpage-export#268]
**Describe the bug**
HTML export works fine, but trying to navigate back using the browser button causes an endless loading animation.

**Operating System**
Windows 10.

**To Reproduce**

1. Open a page.
2. Navigate to next page.
3. Try to navigate back to first page.
4. Reloading the page will cause it to correctly render.

**Screenshots**
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/47560940/b505fac9-490e-471d-bd83-db3bb1da0be5)

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
