### ISSUE TITLE
No output html - v1.7.3 on Debian

### ISSUE THREAD

**Issue by mc0e** [KosmosisDire/obsidian-webpage-export#276]
**Describe the bug**

I'm getting no output, in a manner similar to what's described in #204, #218 and #251, but not identical.  I'm using LMDE 6 (roughly Debian), Obsidian  v1.4.16 installed from the .deb package, and Webpage HTML Export v1.7.3.

- If I try to export "Self-contained Documents", nothing is written.
- If I try to export "Multi-File Website", a `lib` folder is created with `scripts` and `styles` subfolders, and a bunch of files in there, but there is no html.

I get the export options, then when I click the `Export` button, I get a brief flash of a pop-up window.  It might be empty, but it's quick enough to be hard to tell.  In my case though the report in the top right of the window says that it's "Finished HTML" with a tick icon.

If I start obsidian from the command line, there's some output there before I export, but nothing from the export itself.  It looks normal except for this line, which is output at startup, before I try to export.

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

**Operating System**

LMDE 6 (a Linux Mint edition of Debian bookworm), with everything up to date.
Obsidian v1.4.16
Webpage HTML Export v1.7.3

**To Reproduce**
I've tried to export by right clicking on files/folder, using the three-dots menu, and using what I think is called the ribbon, on the far left of the obsidian window.  All do the same.  

**Screenshots**
The developer console shows just one line:

```
(2) failed to find render leaf     plugin:webpage-html-export:56581
```

**Comment by KosmosisDire** [comment]
Hi thank you, since linux is often the culprit behind weird behaviors is it possible for you to try and reproduce this on windows? Also please try to reproduce with a blank vault with no other plugins or files except a single very simple file. That will help me narrow down what the cause of this might be. Thanks!

**Comment by mc0e** [comment]
I've now also replicated this on a Windows 10 system.

- freshly downloaded and installed obsidian
- Created a single page, with just a page name and a single word of text.
- Installed the export plugin
- Attempted export of the page, with no settings changed except for choosing an export path, and enabling the option to open after writing.

Absolutely no other actions taken.

**Comment by mc0e** [comment]
On the Windows 10 system, I get this in the Obsidian Console log:

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1965393/78a0d9f2-2476-492d-a964-e57bf0db1e3f)

**Comment by KosmosisDire** [comment]
Did you select a file to export from the little sidebar thingy? The fact that it's non-finite makes me think that maybe there was a divide by zero?

**Comment by mc0e** [comment]
Yes, The above log output is from right clicking on the file, and exporting from that menu.

If I do it with the 'Export Vault to HTML' button on the far left, the log output indicates a slightly different call-stack leading to the error, but the 'non-finite'  bit is the same.

This is still on windows.  That error wasn't in the console log on Linux.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1965393/0c70e217-1a69-43b9-a501-7098b24e62f5)

**Comment by KosmosisDire** [comment]
This is quite strange, and I am unable to reproduce it. On windows does it still create the lib folder with all the files? I'll look into it more but I am not sure I can do anything without being able to reproduce it. It's possible that the next version will fix thiss since I have done a lot of cleanup of the code which tends to make it more stable. I'll update this when that is released if no other progress is made.

**Comment by mc0e** [comment]
Yes, the lib folder is still created on windows.

Both operating systems were running on the same hardware.  Is there any way that could be relevant?  There was that error there before the export on Linux:

```
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

It looks like libva relates to Video Acceleration.  Maybe it is related to my video hardware?  It's a "NVIDIA GeForce GTX 1050 Ti with Max-Q Design"

**Comment by mc0e** [comment]
I get the same thing in a VirtualBox machine that I created using vagrant.  See attached.

[obsidian_export_vagrant_test.tar.gz](https://github.com/KosmosisDire/obsidian-webpage-export/files/13438604/obsidian_export_vagrant_test.tar.gz)

**Comment by zeukterialpneumaion** [comment]
i am getting this on windows 10 ...
running obsidian ,1.5.3
and v1.7.3 of the plugin
... same thing produces the "lib" folder, and within it the "scripts" and "styles" folders with js and wasm but no html....

**Comment by zeukterialpneumaion** [comment]
these are the plugins i am using:



![Image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/160336/ba03a44b-1066-4d89-b5fc-d0c96204af8c)

**Comment by zeukterialpneumaion** [comment]
this is the error log:

![Image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/160336/8ef9d0c2-d1c2-4ce5-9138-d7c966766f41)

**Comment by mc0e** [comment]
> On the Windows 10 system, I get this in the Obsidian Console log:
> 
> ![image](https://private-user-images.githubusercontent.com/1965393/282258753-78a0d9f2-2476-492d-a964-e57bf0db1e3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNDM2ODUsIm5iZiI6MTcwNzE0MzM4NSwicGF0aCI6Ii8xOTY1MzkzLzI4MjI1ODc1My03OGEwZDlmMi0yNDc2LTQ5MmQtYTk2NC1lNTdiZjBkYjFlM2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDVUMTQyOTQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2Q0MDhiYTViNTQzNDk3NGIzNGFiOGNjM2YxMDFlZGQ5ZGNmMjRlYTRhY2Y0MDFiYjRiZjdlZTEwYWI3N2ZjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ZX59IFGJqx_YERlUlFUB_CMZc8O5XD34GpMhb__F3co)

Is there a way to get a more extended trace of how the error occurred with the values of the arguments passed to the functions at each level of the stack?

**Comment by mc0e** [comment]
I don't know what I've done differently, or if something has been changed upstream and automatically updated on my system, but I can get an export now.  If I start from the little 'export vault' icon on the strip down the left of the window. I get a widget that allows me to select pages (which I haven't seen previously), and after selecting a few and running the export, it now works.  Maybe what I had before was the result of an export with nothing selected?

What I'm testing with is very simple, but the only issue I currently see is that I have the plugin option selected to 'Add filename as title', but page headings generated from the file name are invisible.  Looks like it comes from this css:

```css
.mod-header {
  display: none !important;
}
```

**Comment by KosmosisDire** [comment]
Hi thanks, sounds like you hadn't updated to the latest version or something! The file picker has been there for a while.

The title is a known issue and it's fixed the betas (you can try the beta versions of you'd like)

**Comment by zeukterialpneumaion** [comment]
hi, sorry late to repond, ok, i am working on a think station p330 ...
 - Processor	Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, 3696 Mhz, 6 Core(s), 12 Logical Processor(s)
 no separate graphics card just the internal:	
- Intel(R) UHD Graphics 630
... it is now working i believe, have turned off the weighted graph implementation (which you say is experimental) which was i believe the cause in actuality.... the setting had been strangely kept in cache as being turned on previously and so was failing even though it was switched off and appeared so...after i deleted the previous files it had generated  and the html was generated with a few exceptions...
... so  thankyou ... i cleared all the caches and it sprang to life .... it hasd some issues about some pages not being generated... a few levels down in project structure, no exceptional content in them and simple names which is still a mystery ... but yes, thankyou for your work here...

**Comment by StarmanAkremis** [comment]
It's still happening to me on the latest version on linux
it says "no index.html found, website creation failed"
Only happens when exporting entire vault
