### ISSUE TITLE
Text selection inside code blocks in canvas

### ISSUE THREAD

**Issue by nitanmarcel** [KosmosisDire/obsidian-webpage-export#279]
**Is your feature request related to a problem? Please describe.**
I don't seem to be able to select and copy text inside a text card.

**Describe the solution you'd like**
Probably just make it act like in obsidian, or maybe it already does and is broken. On click it selects the card and then will allow you to select text in it

**Comment by KosmosisDire** [comment]
Hi, thank you. I don't want to follow the way obsidian does it exactly because obsidian's control scheme is designed for editing not just reading. However there are definetly a lot of interactions that I have not impemented yet. I will work on fixing these things in the future. Thanks

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
