### ISSUE TITLE
[FR]: Lost some lazy loaded plugins in 'Include Plugin CSS' picker

### ISSUE THREAD

**Issue by hustrjh** [KosmosisDire/obsidian-webpage-export#280]
## **Is your feature request related to a problem? Please describe.**
I've used [Plugin groups](https://github.com/Mocca101/obsidian-plugin-groups) plugin to load other plugins after a custom delay which is useful for shorter loading time. It seems that **`Obsidian webpage export`** couldn't detect all the plugins I've installed.
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/69783980/4896f3b7-3ea1-4baa-8510-20fd96809bad)

## **Describe the solution you'd like**
It'll be better to include all the plugins I've got in Obsidian in **`Include Plugin CSS`** picker.

## **Describe alternatives you've considered**
I've got two alternatives for the feature.
1. List all installed plugins.
Here's how I generate all installed plugins with templater. I hope this could help.
```
<% Object.values(app.plugins.manifests).map(p=>p.id).sort((a,b)=>a.localeCompare(b)).join('\n') %>
```
2. Allow users to type plugins manually.

Thanks for your excellent plugin! ❤️

**Comment by KosmosisDire** [comment]
Some plugins are intentionally hidden because I know they don't actually have css that can be included to any desirable effect. What plugins are missing?

**Comment by hustrjh** [comment]
Ah, I get it now. Actually I've installed 75 plugins and I could only see 9 plugins in **`Include Plugin CSS`** picker. But I still doubt that there might be some mistakes. Some plugins like buttons, colorful tag, supercharged-links are missing.
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/69783980/cf79a126-a020-41d3-8156-d2ad11cabe84)


I wish my suggestion for the feature could be adopted. Thanks for your quick reply. 🤝

**Comment by KosmosisDire** [comment]
The only plugins shown in the list are ones which are not blacklisted and also have a style.css in their plugin directory. this narrows it down quite a lot.  This is a list of the blacklisted plugins: [third-party-styles-blacklist.txt](https://github.com/KosmosisDire/obsidian-webpage-export/blob/master/assets/third-party-styles-blacklist.txt). The others probably do not have a styles.css file. Many plugins also frameworks like svelte which are included automatically and not shown in the list. And furthermore many plugins do not use custom styles.

Are there any plugins that you specifically are noticing you need the styles from and they are missing?

**Comment by hustrjh** [comment]
It sounds really complicated to handle. Thanks for your explanation. ❤️
I used to think that once I include specific plugin name I could export html file with its css style. 😂
I'll list plugins whose styles are missing here when I encounter such cases in the future.🤝

**Comment by KosmosisDire** [comment]
I will go ahead and close this, but feel free to open a new issue if you do encounter ssuch an issue. Thanks!

**Comment by hustrjh** [comment]
That's fine. Thanks.❤️
