### ISSUE TITLE
Please show the non  .md file extensions in the Selection Structure tree or do not list them at all.

### ISSUE THREAD

**Issue by vgyenge6** [KosmosisDire/obsidian-webpage-export#286]
Hi,

First of all, it is a great plugin. Thanks for it.

It would be good to see the non .md file extensions in the Selection Structure tree.

Thank you for considering.

![Selection_of_individual_files_2023-11-21](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/89e916c0-5da4-4d63-80b6-8eb0a466011e)

**Operating System**
WIN 10 Pro
Obsidian  v.1.4.16
your plugin v. 1.7.3

**Comment by KosmosisDire** [comment]
The extensions will be shown in the next update

**Comment by vgyenge6** [comment]
> The extensions will be shown in the next update

Thanks.

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!

**Comment by vgyenge6** [comment]
Hi,

Thank you, it works now. 👍

**Comment by vgyenge6** [comment]
Hi
Thank you, it works now well. 👍
