### ISSUE TITLE
Resizeable sidebars

### ISSUE THREAD

**Issue by vgyenge6** [KosmosisDire/obsidian-webpage-export#287]
Hi,

First of all, it is a great plugin. Thanks for it.

There is a possibility to set the layout ( document, content, sidebars) width in the settings.
However, it would be a great additional feature if the sidebars would be resizeable. 

Thank you for considering.

![Resizeable_sidebars_2023-11-21](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/ca852cb0-10e9-4d91-8bde-490afc503f4a)

**Operating System**
WIN 10 Pro
Obsidian  v.1.4.16
your plugin v. 1.7.3

**Comment by KosmosisDire** [comment]
I likely won't add this soon, but thank you for the suggestion!

**Comment by stojan97** [comment]
It's good to have at least some customization like changing the color or something.

**Comment by KosmosisDire** [comment]
Colors can all be changed via css snippets

What icons would you want?

Do you mean the 3 dots loading animation?

**Comment by vgyenge6** [comment]
> I likely won't add this soon, but thank you for the suggestion!

Thanks. It is really not so important, but it would be good. to have somewhen.

**Comment by vgyenge6** [comment]
> Colors can all be changed via css snippets

Could you give what CSS properties refer to make any change?

**Comment by stojan97** [comment]
> Colors can all be changed via css snippets
> 
> What icons would you want?
> 
> Do you mean the 3 dots loading animation?

Can you share the method to get to those CSS properties that we can alter?

**Comment by KosmosisDire** [comment]
If you're familiar with CSS you can scroll through the main.js file in the plugin directory to find the built in styles (not the styles.css in the plugin directory). I want to make a custom styling guide, however I will not do that until I am happy with the full design and organization of the styles.

**Comment by KosmosisDire** [comment]
You can also just use the inspector in the browser to look at the styles that can be changed on any given element

**Comment by stojan97** [comment]
Also why the default behavior is animation when switching between documents?

**Comment by KosmosisDire** [comment]
> Also why the default behavior is animation when switching between documents?

This is issue #210, it only happens when you are viewing the files locally

**Comment by zhoulonghao520** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/034b485c-0886-44be-bf2d-344ecd3746f0)
If you are familiar with CSS styles, you can modify the styles here to achieve the effect you want.
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/2c9022b0-3d1b-4136-83bc-d798cfa61159)

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!

**Comment by vgyenge6** [comment]
Hi,

Thank you, it works now. Great! 👍
