### ISSUE TITLE
Auto inject html to head

### ISSUE THREAD

**Issue by KristofKekesi** [KosmosisDire/obsidian-webpage-export#288]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
It would be helpful to have an option to auto inject html to all the generated pages. I find it frustrating to put google analytics tags to all of my pages whenever I recompile the html.

**Comment by aubreyz** [comment]
I'd far prefer just to have predefined comment labels in the code at various relevant points that can be searched and replaced (with Grep or whatever) in a single button press. There are plenty of tools to do that...

**Comment by KosmosisDire** [comment]
This will be in the next update

**Comment by GothLab** [comment]
> This will be in the next update

Thanks for your great plugin. Any timeframe for when this update is planning? Thanks a bunch.

**Comment by KosmosisDire** [comment]
I'm aiming for over the holidays, but I'm not promising anything :)

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
