### ISSUE TITLE
Allow custom fonts

### ISSUE THREAD

**Issue by mahmoodali-01** [KosmosisDire/obsidian-webpage-export#290]
### **Is your feature request related to a problem? Please describe.**
Responsiveness on different devices, by default the text is too big on mobile devices. 

### **Describe the solution you'd like**
Either Custom CSS insert, to be added to lib/generated-style.css - perhaps a box in the settings to allow for CSS to be typed and then inserted.
Or 
Integrate Bootstrap if possible, though it may be a bit longer.

### **Describe alternatives you've considered**
Currently, re-editing CSS each time. I'm adding secondary fonts as fonts that are available on my desktop aren't always available on mobile devices etc.  See below and also adjusting font size based on display.
```
/* Custom Secondary font added, initially was just Palatino Linotype based on Obsidian settings */
body {
    --line-width: 50em;
    --line-width-adaptive: 50em;
    --file-line-width: 50em;
    --content-width: 500em;
    --sidebar-width: calc(min(25em, 80vw));
    --collapse-arrow-size: 0.35em;
    --tree-horizontal-spacing: 0.6em;
    --tree-vertical-spacing: 0.6em;
    --sidebar-margin: 24px;
    --font-text-size: 16px; /* Default font size */
    --zoom-factor: 1!important;
    --font-text-override: 'Palatino Linotype', 'Book Antiqua', Palatino, serif!important;
    --font-print-override: 'Palatino Linotype', 'Book Antiqua', Palatino, serif!important;
}

/* Smaller screens (like mobile devices) */
@media screen and (max-width: 600px) {
    body {
        --font-text-size: 14px; /* Smaller font size for small screens */
    }
}

/* Medium-sized screens (like tablets) */
@media screen and (min-width: 601px) and (max-width: 1024px) {
    body {
        --font-text-size: 15px; /* Slightly larger font size for medium screens */
    }
}

/* Large screens (like desktops) */
@media screen and (min-width: 1025px) {
    body {
        --font-text-size: 16px; /* Default font size for large screens */
    }
}

```

**Additional context**
I understand choosing a secondary font for every font is not practical, so perhaps create a dropdown in settings for user to select?

**Comment by KosmosisDire** [comment]
The font size actually is responsive already and is made smaller on smaller screens. What resolution is your device and could you send a screenshot of what the font size looks like on that device?

**Comment by mahmoodali-01** [comment]
Ahh, looking back at it it is good by default. 

However, the font I use is a bit smaller than regular. I prefer a smaller sized font, which is why I added the secondary fonts in case the font I use for obsidian isn't there. What are your thoughts on implementing a secondary font option?

**Comment by KosmosisDire** [comment]
I mean the goal would be for it to automatically grab the font that was used in obsidian. In fact, I believe it already does this if the font is natively supported in the browser. However I will consider adding a feature to actually include a custom font file

**Comment by mahmoodali-01** [comment]
So it actually does grab whatever font obsidian uses, issue is the font isn't always supported on all browsers. E.g. the font I use, made by Microsoft, only works on Windows and I use the Edge browser. Not sure about Chrome, which is why I use the secondary font in the CSS as seen above.

Custom font file would be good, and very much appreciated. Thanks.

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!

(To clarify if you add a font via css the font should be automatically downloaded, however it needs to point to a URL, you can't just use a custom local font on your machine)
