### ISSUE TITLE
Allow for `~` in Export Path

### ISSUE THREAD

**Issue by lzilioli-prism** [KosmosisDire/obsidian-webpage-export#299]
**Is your feature request related to a problem? Please describe.**
I share my obsidian vault in a github repo with my team. We run webpage export, which writes to a `docs` folder within the vault, and when we push to github, the docs folder is published as a static webpage.

Right now, we are forced to hard code an absolute path to the export directory, which contains our mac username.

**Describe the solution you'd like**
Ideally we could enforce our developers all clone to the same location within their home folder (e.g. `~/Projects`), and we could configure this plugin with `~/Projects/our-shared-vault/docs` as the export path, so that running the export would work for all of our developers, without them needing to change the path prior to export.

If this plugin simply resolved `~` to `process.env.HOME` when resolving the export path, we could generalize and share this plugin config as part of our github repository.

Our current solution is to gitignore the data.json file for this plugin, and each configure it on our own. But this is not ideal, as everyone has to do at least one export before the "export using previously selected files and settings" will work properly.

**Comment by KosmosisDire** [comment]
Hmm I will look into supporting this since ~ is a very commonly used shortcut

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
