### ISSUE TITLE
Where is it?

### ISSUE THREAD

**Issue by MystreAqui** [KosmosisDire/obsidian-webpage-export#3]
Cant find ur plugin in the plugins list.  Im on Android.

**Comment by KosmosisDire** [comment]
This plugin is only for desktop. There are a number of technical limitations that make this plugin basically impossible on Android.

**Comment by KosmosisDire** [comment]
Additionally it is not yet published in the official plugins list, so must be installed manually for now. This will change soon though

**Comment by MystreAqui** [comment]
Ok, thanks for answering
