### ISSUE TITLE
Export using previously selected files and settings does not pick up new files within folders

### ISSUE THREAD

**Issue by lzilioli-prism** [KosmosisDire/obsidian-webpage-export#300]
**Describe the bug**
When I configure an export, and check off a folder, I am expressing an intent to "export all notes within this folder". Intuitively, I would expect that if I add a note to a folder that I checked off during my last export, the new note would automatically get included with the next export, since in my mind I had selected the entire folder, not each individual note therein at the time of export. Unfortunately, this is not how it works. If I create new notes since my last export, I must go through the full export wizard (re-selecting hundreds of notes and folders) in order to restore my previous configuration + the new notes. This is a suboptimal user experience that causes me to spend a lot more time exporting my notes than I would like.

**Comment by KosmosisDire** [comment]
This is already implemented in the 1.7.4 branch and will be released in the next update :)

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
