### ISSUE TITLE
Add an rss feed to the HTML output

### ISSUE THREAD

**Issue by scumola** [KosmosisDire/obsidian-webpage-export#301]
Needs an rss feed generator.  Can't use any 3rd party ones because only this tool knows the urls, etc.

**Comment by KosmosisDire** [comment]
I'm not sure how 3rd party ones even work, but would it help if the plugin was able to export a sitemap in some standard format?

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
