### ISSUE TITLE
Image scaling with "|" gets lost past the first page

### ISSUE THREAD

**Issue by nayutune** [KosmosisDire/obsidian-webpage-export#302]
**Describe the bug**
Images can be scaled by putting "|" and a number after the image path: [[image.jpg|160]]
It works perfectly when exporting a single page, but as soon as you try to export multiple pages that scale images - only 1 page ends up scaling images in the export.

It does not seem to be affected by any of the self-container options.

**Operating System**
Windows 10 22H2

**To Reproduce**
1. Create a page
2. Drop an image into the page.
3. Add "|160" to the end of your image path.
4. Create a second page
5. Drop the same or new image into the page.
6. Add "|160" to the end of your image path.
7. Export both pages.
8. Open both pages and compare.

**Screenshots**
![screenshot](https://github.com/KosmosisDire/obsidian-webpage-export/assets/74027819/01c3e42f-e3de-4fbf-b74e-9a25f5865104)

### IMPORTANT: Error Log
No warnings or errors.
Only the "info" that prints: Failed to find render leaf

**Comment by KosmosisDire** [comment]
Thanks, this should be fixed in the next release

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
