### ISSUE TITLE
Please change name and description

### ISSUE THREAD

**Issue by 7Mik** [KosmosisDire/obsidian-webpage-export#305]
First of all allow me to thank you again for your hard work.

Secondly, I want to bring to your attention that the current plugin name is redundant and not effective.
I was searching for a plugin like this and stumbled upon inferior alternatives before randomly deciding to search for "HTML" and finding this. My personal suggestion would be using buzzwords like "Publish" and "Digital Garden".

My proposal:

Plugin name: Static Garden
Plugin description: The fastest solution to export single files or whole vaults as static websites, directly on your system. Build your own digital garden like Publish, but get direct access to the HTML!

**Comment by KosmosisDire** [comment]
This is definitely something I have thought about a lot. I plan to change it eventually, but I want to cater to both the people wanting an HTML export, as well as people looking for publish alternatives. Thank you for the suggestions!

**Comment by 7Mik** [comment]
> This is definitely something I have thought about a lot. I plan to change it eventually, but I want to cater to both the people wanting an HTML export, as well as people looking for publish alternatives. Thank you for the suggestions!

That's what I want too! At the moment while searching for "publish" or "digital garden" your plugin doesn't show up. Just consider adding those buzzwords in the description somehow in the next release

**Comment by KosmosisDire** [comment]
Yes, what about the current short description I have in github?

>Webpage HTML Export lets you export single files or whole vaults as HTML websites or documents. It is similar to publish or a digital garden, but you get direct access to the exported HTML.

(I added the digital garden thing just now)

**Comment by katylava** [comment]
FWIW I searched for "export" and this is exactly what i was looking for.

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!

(I changed the description but not the name)
