### ISSUE TITLE
Can't go back to no custom header once you've set one once

### ISSUE THREAD

**Issue by 7Mik** [KosmosisDire/obsidian-webpage-export#309]
Removing the path after having set it once in the "custom head content path" field will cast the "Path must be a file" error and revert to last used header.

I will just add it here to remember to look into it after I'm done with the search

**Comment by KosmosisDire** [comment]
I have actually fixed this issue in the 1.7.4 branch but the commit has not been pushed yet, thanks for putting this here though!
