### ISSUE TITLE
"Page Not Found" error page generated when it is not justifed

### ISSUE THREAD

**Issue by iherman** [KosmosisDire/obsidian-webpage-export#310]
**Describe the bug**
When I navigate through the generated Web site (dumped from my vault), and I hit a "back" button on my browser, I get a "Page Not Found" error page instead of the generated HTML file. Unfortunately, it does not happen all the time (it would be too easy if it did... 😀

**Operating System**
MacOS 14.2.1 as well as IOS 17.2.1.

I opened the generated Web site on Chromium based browser (in my case Arc), on Firefox, as well as Safari. For Safari that was both on the Mac an on the iPhone. The behaviour is identical.

In all cases I see the html file coming up on the screen and then the screen is 'exchanged' to the error page. I tried to chase down the bug and got to the point that, in the `lib/scripts/webpage.js` file, where I found the trace of this generated page lined to a timeout function.

To make what follows clearer: my setup is that I dump my vault to a directory on my machine, which I then reach via a server running on it and serving the site on `localhost:8001/LocalData/Obsidian`. 

Looking at the console.log output in the developer's console of chromium (see the screen dump below), what I see is the message:

```
Page not found: /LocalData/Obsidian/index.html
```

which refers to the name of the file (which exists) and which I used to navigate from. However, the line above shows:

```
GET http://localhost:8001/LocalData/Obsidian/Obsidian/index.html webpage.js:1
404 (Not found)
```

where the URL for the GET _is indeed wrong_. Ie, the script seems to want to generate a fetch with a URL that (I presume) is constructed, but the construction is buggy.

That is as far as I got... maybe it helps locating the bug.

Here is the screen dump:

<img width="1873" alt="Screenshot 2024-01-06 at 18 20 14" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/520723/238f4b6c-84e4-44e7-a19b-b0c41ad140d3">

**To Reproduce**

I pretty much described what I did to get to the error, see also the screen dump above.

**Comment by KosmosisDire** [comment]
Hi thanks, this is a duplicate of issue #295. I have already fixed this in development and it will be fixed in the next release :)

**Comment by iherman** [comment]
Oh, rubbish, I forgot the basic steps in these circumstances, namely check the other issues. Basic github behaviour... My apologies.

I am happy it is fixed already, though.

Thanks for your work, @KosmosisDire.
