### ISSUE TITLE
TypeError: Path is not a constructor

### ISSUE THREAD

**Issue by KosmosisDire** [KosmosisDire/obsidian-webpage-export#313]
When running the merged 1.7.4 branch an error causes the plugin to fail to load. The definition of `Path` seems to be undefined.
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/39423700/a5792fdb-c8a4-42ae-8377-e5d6b6f16015)

**Comment by 7Mik** [comment]
Well it seems to be related to this line.

`Asset.libraryFolder = new Path("lib").makeUnixStyle();`

Is this the new asset management feature?

Moreover, you might wanna look at markdown-renderer.ts, at line 672, since the behavior "instant" was casting an error while building locally and I had to change it to smooth

**Comment by KosmosisDire** [comment]
Yes it's the new asset management feature, however both branches were working without error before the merge. And there was no problem with the path or asset management.

I noticed the "instant" error, but I forgot which options were valid haha, I'll go ahead and change that too.

**Comment by KosmosisDire** [comment]
BTW if you do `npm run dev` it will build automatically when files change and it will also give you Typescript error call stacks which is very useful. So that error actually corresponds to line 37 of assets.ts

**Comment by 7Mik** [comment]
Can't you just grab the path.ts from the 1.7.4 before the merge?

**Comment by KosmosisDire** [comment]
path.ts was identical before the merge and after, so was asset.ts. Idk what's wrong. I managed to fix it my not accessing Path in the static initializer. So the latest commit should now allow you to build and run it.

**Comment by 7Mik** [comment]
> path.ts was identical before the merge and after, so was asset.ts. Idk what's wrong. I managed to fix it by not accessing Path in the static initializer. So the latest commit should now allow you to build and run it.

But I saw in the commit history that path was actually changed while merging it into master

**Comment by KosmosisDire** [comment]
Where do you see that path was changed? There should no longer be any error related to this issue on the 1.7.4 branch.

**Comment by 7Mik** [comment]
> Where do you see that path.ts was changed? There should no longer be any error related to this issue on the 1.7.4 branch.

I saw it somewhere in the pull history but since it's fixed now it's all good :)

On that note... maybe it's better if you actually close all the solved issues, it's just cleaner to see what's still unsolved. Rn it's kinda hard since there are 107 open issues haha

**Comment by 7Mik** [comment]
> I don't like closing issues until they are solved in a release because then I am much more likely to end up with people submitting duplicates. I do keep track of it in a project though which may be easier to look at. https://github.com/users/KosmosisDire/projects/2/views/2

Oh ok makes sense.

btw I'm still getting this scripts/html-generation/markdown-renderer.ts:672:26 - error TS2322: Type '"instant"' is not assignable to type 'ScrollBehavior | undefined'.

Did you forget to push the fixed one? I'll just edit that to smooth in my local build to make it work

**Comment by KosmosisDire** [comment]
Smooth is actually incorrect, "instant" is a real option but it thinks it isn't. Just ass a `//@ts-ignore`

**Comment by KosmosisDire** [comment]
I just pushed a pretty large commit which fixes a bunch of issues incuding that one

**Comment by 7Mik** [comment]
> I just pushed a pretty large commit which fixes a bunch of issues incuding that one

Nice I'm grabbing that one and start working on the search features

**Comment by KosmosisDire** [comment]
Okay cool! I am working on testing the features we have so far to ensure stability

**Comment by 7Mik** [comment]
> Okay cool! I am working on testing the features we have so far to ensure stability

Html generation is unbearably slow now. Any idea why?

P.S. Is there any way we can conatct each other instead of using public thread as a chat haahah

**Comment by KosmosisDire** [comment]
Do you have discord? How slow are you talking? How many files are you trying to export?

**Comment by 7Mik** [comment]
> Do you have discord? How slow are you talking? How many files are you trying to export?

Yeah I do, what's your @?

I'm talking thousands of times slower than it used to be. Exporting a 350 notes vault took seconds now it's been 4min and it's at 50%.

**Comment by KosmosisDire** [comment]
`@KosmosisDire` is my @
I'll do a speed comparison on my end, but tbh I thought it was faster now lmao
