### ISSUE TITLE
Clicking on a note resets list of notes, closes open folders, doesn't display note name

### ISSUE THREAD

**Issue by TrianglesPCT** [KosmosisDire/obsidian-webpage-export#317]
In Obsidian if I click on a note to view it, this does not alter which folders are open/closed..

In the webpage if I click on any note it closes all the folders I had open, the sidebars flicker out, then animate back in.. 

It also isn't clear which note you clicked on because it resets every time you click, and the note that was clicked is not highlighted like in Obsidian.

(*it would also be really nice if there was a way to tell it to include the name of the note at top of page)

Am I doing something wrong with the way I'm exporting? I'm only viewing the page locally.

Maybe it is doing this because they are all separate pages? Is there a way to make it one page and get rid of the annoying animation?

**Comment by KosmosisDire** [comment]
This is an inherent problem with opening html files locally. The whole page has to be reloaded every time a new document is opened. If the files were served by a web server all these issues would go away.

I'd like to fix this at some point, but for now it just isn't worth it for all the trouble it causes.

**Comment by TrianglesPCT** [comment]
Oh thanks, I'm not a web dev so didn't know that! 

maybe add a note in FAQ?

**Comment by KosmosisDire** [comment]
Thanks, I will try and update some of the readme to make some of this clearer!
