### ISSUE TITLE
When hosting or using file:// protocol, the name of the file does not appear as the title of the site, even if the toggle is turned on. 

### ISSUE THREAD

**Issue by WinnerWind** [KosmosisDire/obsidian-webpage-export#320]
**Describe the bug**
Even though this toggle is on
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/71366717/b7a104b1-bda5-46da-8b5c-d78e69957ff7)
And the first heading is NOT a H1, or any heading at all, the heading does not display.
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/71366717/d6c60951-3c3d-4829-8524-8beac1121d61)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/71366717/00262483-e79a-4138-9abf-80e8561ac05a)
Here are the origin files
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/71366717/10c8bf38-e1ca-4603-9aa7-79d73d88ec43)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/71366717/3f4d6bc6-ae35-4d13-9ab5-d1776bc3cb6e)

**Operating System**
Windows 10

**To Reproduce**
Set the "Show title as file name" toggle in plugin settings
Export (I used Multi File)
Open the website (or host it, this bug happens in both cases)
See the headings not display

**Screenshots**
Uploaded above

### IMPORTANT: Error Log
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/71366717/d0f43907-ab5a-4d5f-b2ef-7c86c7f5846c)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/71366717/61780c8b-75eb-47d7-8878-246b4112467a)

**Comment by KosmosisDire** [comment]
Thanks, this will be fixed in the next release

**Comment by KosmosisDire** [comment]
If you'd like you can try the beta, as this is fixed there

**Comment by WinnerWind** [comment]
Thank you! I'll check out the beta version sometime.

**Comment by KosmosisDire** [comment]
This should be fixed in 1.8.0. Let me know if it still does not work as expected and reopen the issue. If you find any new issues please submit a new issue :)
Thanks!
