### ISSUE TITLE
1.7.4-3b Export Multiple files bug

### ISSUE THREAD

**Issue by GothLab** [KosmosisDire/obsidian-webpage-export#322]
**Describe the bug**
When exporting multiple files, it exports only the ones that were selected before - right click - export as html, even though I've clicked 'Select All

**Operating System**
Windows 10

**To Reproduce**
1. Go to filelist
2. Click on required folder to export 
3. Scroll down to Export as Html, select all
4. See Export without all files included

Video: https://youtu.be/0FMF0eJSLSs

**Comment by KosmosisDire** [comment]
Thanks for the report, this should be fixed if you use the ribbon icon rather than right clicking on a file. I will look into fixing it when a file is right clicked as well. Thanks!

**Comment by KosmosisDire** [comment]
I was able to reproduce and fix this error, it will be fixed in the next release
