### ISSUE TITLE
Invalid url characters make outline not go to header

### ISSUE THREAD

**Issue by ryran** [KosmosisDire/obsidian-webpage-export#328]
**Describe the bug**
With v1.8.0-2b, using styled quotation marks like `’` in H1, H2, H3, etc results in TOC anchor links that do nothing.

**Operating System**
Fedora Linux

**To Reproduce**
For an example, see [this page](https://b19.org/library-authoritative.html). You'll notice the single H1 TOC link doesn't work and neither do 3 of the H2 anchor links. Obviously in this context, this particular character _could_ be replaced with a standard apostrophe (though it would be technically incorrect to do so); however, I suspect the issue could likely affect other characters as well.

**Comment by KosmosisDire** [comment]
Yes it is likely some kind of encoding problem, not specific to this character. I will look into it

**Comment by KosmosisDire** [comment]
Test this on 1.8.0-3b and let me know how it works

**Comment by ryran** [comment]
> Test this on 1.8.0-3b and let me know how it works

Seems to be fixed, at least for all of my headings!!

**Comment by KosmosisDire** [comment]
I'll close this as I am farily sure this is fixed for everything else as well

**Comment by ryran** [comment]
Thank you Nathan!
