### ISSUE TITLE
Would it be possible to change the handling of YT videos embedded in a collapsed callout so that they aren't loaded until the callout is opened for the first time? 

### ISSUE THREAD

**Issue by ryran** [KosmosisDire/obsidian-webpage-export#331]
**Is your feature request related to a problem? Please describe.**
I experimented with embedding a bunch of youtube videos into pre-collapsed callouts, imagining that after exporting with your awesome plugin, perhaps the embedded videos wouldn't be loaded until/unless their callout was expanded. Turns out my assumption/hope was wrong -- this made loading of my page much slower and looking at the console in my web browser makes it clear that YES all of the embedded youtube videos are being loaded on page open, regardless of the starting state of their parent callout.

**Describe the solution you'd like**
If it is even possible, I'd love for the html/js/css (?) generated by your dope plugin to structure things such that embeds inside collapsed callouts aren't loaded unless the callout is expanded.

**Describe alternatives you've considered**
I'm completely ignorant of all this. If it's practically impossible, I assume you'll know Nathan. If you think it could be achieved by me using some custom snippets, I could pursue that elsewhere.

**Additional context**
I'll probably change it back soon (to remove the embeds), but you can see this issue in action in the current version of [b19.org](https://b19.org).

**Comment by KosmosisDire** [comment]
This should be easy to implement hopefully by just adding a lazy loading attribute to all the iframes. This would cause the videos to only load once they were in view. This may cause them to still load even if the user doesn't open the callout though. I am not sure. But since it is easy enough to implment I'll go ahead and try it

**Comment by KosmosisDire** [comment]
Although I will mention that firefox for android doesn't support this so people using firefox on android would still face the long loading times

**Comment by ryran** [comment]
> Test this on 1.8.0-3b and let me know how it works

DUDE it's brilliant! That fixes it!!
