### ISSUE TITLE
The file tree starts out invisible and seems to only show up after a hard refresh

### ISSUE THREAD

**Issue by ryran** [KosmosisDire/obsidian-webpage-export#333]
**Describe the bug**
The content on [b19.org](https://b19.org) was generated via v1.8.0-7b with file tree enabled and search bar disabled. Sometimes when the page loads, the file tree is visible; sometimes it's not. (The search bar option doesn't seem to make a difference as to whether this issue happens.)

In my experience, if the file tree is _NOT_ visible:
- Doing a full reload -- holding Shift while triggering reload -- always makes it show up

In my experience, if the file tree _IS_ visible:
- clicking things in the file tree works and switching between pages doesn't make the file tree disappear
- refreshing the page (or using the address bar to navigate to the page again) almost always makes the file tree disappear

PS: When opening the page via a fresh incognito session, it _almost_ always starts with the file tree invisible.

**Operating System**
Fedora Linux

**To Reproduce**
![settings](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/2ed6f04b-3001-4db4-86d5-62e9830f2a2a)

**Comment by KosmosisDire** [comment]
Try this again in 1.8.0-8b

**Comment by ryran** [comment]
> Try this again in 1.8.0-8b

Seems to be fixed! :partying_face: 
I love the way you reorganized the settings page too!
