### ISSUE TITLE
Allow explicitly setting light theme independently of dark theme

### ISSUE THREAD

**Issue by ryran** [KosmosisDire/obsidian-webpage-export#341]
**Is your feature request related to a problem? Please describe.**
This feels like an impossible ask, but when exporting, I wish I could use a particular theme for the light colorscheme and a totally different theme for the dark colorscheme.

**Describe the solution you'd like**
I could imagine nesting a couple new options under the "Theme toggle" feature, e.g., if you enable theme toggle, you get two new theme selection options, like:
```
Theme to use for dark    ____[theme selector]_____   [reset-to-default-button]
Theme to use for light   ____[theme selector]_____   [reset-to-default-button]
```
(Of course by default, both options would inherit the current theme.)

This way, I could mix and match -- use a particular low-contrast theme for dark and a totally different more boring high-contrast one for light. (For example.)

**Describe alternatives you've considered**
Obviously with enough time & perseverance, I could achieve anything I'm aiming for by tweaking css snippets and/or creating my own custom theme....

**Additional context**
None.
But the word "additional" makes me think of something even more preposterous than the above RFE: It would be so cool to export with more than two stylesheets, e.g., instead of the exported content having just a binary sun/moon toggle, what if it could have a drop-down that lets the visitor select from a few different themes? Man that would be awesome. (I have colorschemes that me and most of my peers love but which are hated by some colorblind friends and friends over 65 who complain about the contrast.)

**Comment by KosmosisDire** [comment]
Thanks! I don't think I will ever add this. The main problem is that this would require exporting two themes with the website which have to be BOTH loaded before the page will be displaed which is going to slow everything down. And then I have to load or unload them based on which theme we are in (this would both be slow and technically challenging). 

It would be much better to create your own theme by copying the colors from your two themes and making a mashup theme. Additionally, some themes have a lot of configuration if you use the Style Settings plugin. This allows you to change different colors for dark and light mode. This is the intended approach and I beleive adding support for two different themes would end up being a worse experience in the end.

Thank you for this idea though, don't stop them coming :)

**Comment by ryran** [comment]
> Thanks! I don't think I will ever add this. The main problem is that this would require exporting two themes with the website which have to be BOTH loaded before the page will be displaed which is going to slow everything down. And then I have to load or unload them based on which theme we are in (this would both be slow and technically challenging).

OH wow! I had no idea that was what happens under the hood. Yikes.

> It would be much better to create your own theme by copying the colors from your two themes and making a mashup theme. Additionally, some themes have a lot of configuration if you use the Style Settings plugin. This allows you to change different colors for dark and light mode. This is the intended approach and I beleive adding support for two different themes would end up being a worse experience in the end.

Gotcha. I've tried to play with style settings with no luck yet. I'll give it a try again soon.

> Thank you for this idea though, don't stop them coming

You rock!
