### ISSUE TITLE
nginx error when hosting the site

### ISSUE THREAD

**Issue by Ryuo1** [KosmosisDire/obsidian-webpage-export#343]
**Describe the bug**
Nginx fails to load the javascripts properly. It loads them as HTML files in the browser for some reason.

**Operating System**
Ubuntu-server

**To Reproduce**
1. Place the export available for nginx
2. Host it
3. See that the websites fails to load the javascripts, with errors in the console.

**Screenshots**
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/77712873/3f5cfc8b-0a06-4fd4-b00d-be9aed941b14)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/77712873/abc1f052-3dc1-4a86-a89a-f30ed8735f5c)

### IMPORTANT: Error Log

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
graph_wasm.js:1 Uncaught SyntaxError: Unexpected token '<'
tinycolor.js:1 Uncaught SyntaxError: Unexpected token '<'
```

### Nginx Configurations:

```
worker_processes auto;

events {
  worker_connections 1024;
}

http {
  default_type application/octet-stream;
	sendfile on;
	tcp_nopush on;
	types_hash_max_size 2048;

  include /etc/nginx/mime.types;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
  ssl_prefer_server_ciphers on;
  
  types {
      application/javascript js;
    }

include /etc/nginx/sites-enabled/*;

```

```
server {
  listen 443 ssl;
  listen [::]:443 ssl;
  server_name subdomain.domain.com;

  ssl_certificate /certificates/obsidian/fullchain.pem;
  ssl_certificate_key /certificates/obsidian/privkey.pem;

  location /webdev-tutorial {
    root /usr/share/nginx/html;
  }

  location ~ ^/webdev-tutorial/.*\.js$ {
    alias /usr/share/nginx/html/webdev-tutorial/;
    add_header Content-Type application/javascript;
  }
}

```

**Comment by KosmosisDire** [comment]
I am also hosting my own site using nginx on ubuntu. I have not had this issue. I am not super knowlagable with nginx though, and I don't think this is a problem with the plugin but rather with the server. I am not sure I can help much, sorry!

**Comment by Ryuo1** [comment]
I would *really* appreaciate it if you could send me your nginx config

**Comment by KosmosisDire** [comment]
My config is default other than SSL configurations. Nginx should send js mime types by default

**Comment by KosmosisDire** [comment]
```
server 
{
    server_name notes.nathang.dev;

    root /var/www/nathang.dev/notes;
    index index.html;
    
    gzip on;
    gzip_vary on;
    gzip_types text/plain text/css text/xml text/javascript application/x-javascript application/xml;
    gzip_min_length 1000;
    gzip_proxied no-cache no-store private expired auth;


    location / {
        try_files $uri $uri/ =404;
    }


    listen 443 ssl; # managed by Certbot
    # ssl info
}
```

I do have gzip enabled, which makes the client load the files faster but it orks ithout any of the gzip configs on.

**Comment by Ryuo1** [comment]
I used your gzip options and the issue was solved :sob:

**Comment by KosmosisDire** [comment]
That is weird since gzip doesn't change the mime type, so idk

**Comment by Ryuo1** [comment]
I changed the files and the issue is reoccuring.

**Comment by KosmosisDire** [comment]
Try setting the 
```
index index.html;
```
config?


I just tried on this config succesfully:
```
server 
{
    server_name notes.nathang.dev;
    root /var/www/nathang.dev/notes;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    listen 443 ssl; # managed by Certbot
    # ssl info
}
```

**Comment by Ryuo1** [comment]
I changed location from /webdev-tutorial to just / like in your config.
Now the console gives me new errors:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 's')
    at Module._malloc (graph_wasm.js:1:12777)
    at GraphAssembly.init (graph_view.js:1:912)
    at Object.initializeGraphView [as onRuntimeInitialized] (graph_view.js:1:7800)
    at graph_view.js:1:14446
```

**Comment by KosmosisDire** [comment]
You should be able to use subdirectories. Try having a default configc for the root directory and then override in the subdirectory. So, define the root in both the subdomain and domain for example. I am not really sure how it all works though or what would solve it. But probably could help to do some googling about mime types in multiple locations.

Or if using gzip solved it, you can use gzip. Since gzip is a good thing to have on anyways.

**Comment by KosmosisDire** [comment]
I am going to close this since you said using gzip solved it but feel free to reopen if you need
