### ISSUE TITLE
Be able to export file as single (View only without any side bar)

### ISSUE THREAD

**Issue by I2rys** [KosmosisDire/obsidian-webpage-export#344]
**Is your feature request related to a problem? Please describe.**
Yes like If you're making a custom blog or something for your personal project where you only want to export the file and It's content alone having this feature would be very useful. Thanksss u in advance!

**Describe the solution you'd like**
It would be very useful If you can export a file as single like It has no file explorer or anything but instead the only content of the file itself.

**Comment by KosmosisDire** [comment]
Hi this is possible already in the beta!

**Comment by I2rys** [comment]
> Hi this is possible already in the beta!

It still shows the navs panels on the left (Files explorer) and right.

**Comment by KosmosisDire** [comment]
You have to select the raw html export option :)

**Comment by I2rys** [comment]
> You have to select the raw html export option :)

Where is it located? I can't seem to find it huhu

**Comment by KosmosisDire** [comment]
It's one of the export presets on the main export screen. I can send you a screenshot in a bit. But it's basically the only option that shows on the export modal

**Comment by KosmosisDire** [comment]
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/39423700/5ef67a05-5b16-45ab-a038-f7a55752e6d4)

This html will still be a full html document including html and body tags, scripts, and styles. Because without those the document is completely broken. But you should be able to embed it as a document inside of a website if you would like.

You can also export it as the Online Web Server mode but hide all of the sidebar components. This will give you a more optimized output with multiple files, but it may be a bit trickier to embed.

**Comment by I2rys** [comment]
I can't seem to find it. How do you enable/install the beta version? 0-0

**Comment by KosmosisDire** [comment]
Hi this is the release for the latest beta, just download the .zip file and replace your plugin files with it's contents:
https://github.com/KosmosisDire/obsidian-webpage-export/releases/tag/1.8.0-9b

Or you can install the BRAT plugin then add a beta plugin using this url, which is probably easier and will receive beta updates:
https://github.com/KosmosisDire/obsidian-webpage-export

**Comment by I2rys** [comment]
> Hi this is the release for the latest beta, just download the .zip file and replace your plugin files with it's contents: https://github.com/KosmosisDire/obsidian-webpage-export/releases/tag/1.8.0-9b
> 
> Or you can install the BRAT plugin then add a beta plugin using this url, which is probably easier and will receive beta updates: https://github.com/KosmosisDire/obsidian-webpage-export

Thank you so much!
