### ISSUE TITLE
Exported pages use the Obsidian paths for embedded resources instead of converting them to full file paths

### ISSUE THREAD

**Issue by attilio-oliva** [KosmosisDire/obsidian-webpage-export#346]
I'm not sure if this should be flagged as a bug or a feature, in case it was not handled.

**Describe the bug**
In Obsidian, I usually refer to files not using their full path, but by just expressing their name even though they are not located on the same folder. In Obsidian this is legit and links/embeddings just work.
Let's say I have the vault organized this way:
```
- Topic
   ├──Attachments
   │  └── myfile.pdf
   └──Notes
       └── mynote: can embed the file just with ![myfile.pdf]
```   
But when you export using this plugin, it assumes you expressed the full path. So if you try to host and bring up the result, you'll end up with incorrect references and failing to load other embedded resources

**Environment**
```
  Obsidian version: v1.5.3
  Installer version: v1.4.13
  Operating system: Windows 10 Pro 10.0.19045
  Login status: not logged in
  Insider build toggle: off
  Live preview: on
  Base theme: adapt to system
  Community theme: none
  Snippets enabled: 0
  Restricted mode: off
  Plugins installed: 1
  Plugins enabled: 1
    1: Webpage HTML Export v1.7.3
```
**To Reproduce**
1. Create the vault as described or download this [sandboxed vault](https://github.com/KosmosisDire/obsidian-webpage-export/files/14214832/Obsidian.Sandbox.zip)
![image_2024-02-08_19-47-08](https://github.com/KosmosisDire/obsidian-webpage-export/assets/75045331/320a18c1-637f-42bb-a997-550e8c272c79)

2. Export as HTML the whole vault in multifile with the default settings (except for the web file name options, otherwise it will mess the names and the reference can't work, actually another problem by itself)
3. Use a simple web server in the root folder of the exported build (like `python -m http.server`) and navigate to a note file
4. Notice that it uses the literal path given by the source file, even thought it was not a full path to the file, but just its name (weird, it even fails to render even the text and title)
![image_2024-02-08_19-51-48](https://github.com/KosmosisDire/obsidian-webpage-export/assets/75045331/d5a4697a-7784-4acd-bcf9-af4e1b86f5fa)
5. If you use the full path by editing the HTML by hand, it will work (almost) as expected
![image_2024-02-08_19-53-14](https://github.com/KosmosisDire/obsidian-webpage-export/assets/75045331/d40eac66-5365-40df-86e8-5b6086917d3b)

**Comment by KosmosisDire** [comment]
This should be a bug, as this is already handled and should work. I will look into it though and thanks for the details!

**Comment by KosmosisDire** [comment]
Can you please test out the new beta 1.8.1-0b and let me know if this fixes the issue? Please also let me know if you find any new issues. Thanks!

**Comment by attilio-oliva** [comment]
If you use the new "Online Web Server" export mode it fixes the issue, but I can still reproduce this error using "HTML documents" export option and the sandboxed vault I shared (even thought it renders the note title this time)

I also found some other problems in the meanwhile:
1. The export process even on medium-sized vaults is painfully slow in case single notes are long and there are a lot of embeddings
2. "Open after export" option on export popup doesn't work on Windows. An error instead will be provided at the end of the export saying that windows couldn't find the file with the path provided
3. There is some regression around Excalidraw, since some (simple) drawings get the exporting process stuck forever. This is hard to reproduce, sometimes it works and sometimes doesn't. However, the latter case is the most frequent if I do stress tests on my personal vaults.
4. I'm not sure if it's related to the problem 3, but sometimes happens that the exporting windows get completely white meanwhile the obsidian window gets completely black and gets both gets stuck like this.

**Comment by KosmosisDire** [comment]
Hi, can you instead make anew issue for each of these problems searching for duplicated first? More details would be helpful since I need to be able to reproduce a problem to fix it. (although I can reproduce 2. just fine) Thanks.

**Comment by KosmosisDire** [comment]
As for it not loading PDFs in HTMLDocuments mode, this is because PDFs cannot be loaded in locally opened files. This is not something that I can fix it's just a limitation of opening an html file using the file:// protocol. PDF embeds also aren't supported on mobile.

**Comment by attilio-oliva** [comment]
For the other issues I'll create them once I find the specific cause so they can always be reproduced. 

This issue can be considered solved. Thank you for your hard work.
