### ISSUE TITLE
Add a graph view similar to obsidian's

### ISSUE THREAD

**Issue by KosmosisDire** [KosmosisDire/obsidian-webpage-export#35]
Add a graph view similar to obsidians that shows the relationship between all the files in the export. This should use a canvas, mimic the physics and draggable nature of the one in obsidian, and should base it's properties and visuals on the ones set in obsidian on export.

**Comment by gnd** [comment]
Hello, have you already started working on this ? I would be willing to help with this.

**Comment by KosmosisDire** [comment]
Hey, thanks for offering!

Yes I have started work on this already and have a working simulation. The next steps that need to be worked on are mostly optimization and exporting coloring and other settings from the obsidian version (I can already export the graph itself). I am planning on using WebAssembly for the optimization as well as trying some spatial partitioning methods. Right now the code for this is in a seperate project which I will add into the project when it is ready. At this point I don't think I can accept help on this feature until I get it to a point where it is actually unified into the codebase. However if you have ideas or suggestions I would be happy to accept them! :)

**Comment by KosmosisDire** [comment]
@gnd As an update to this, I have rewritten the whole simulation to run in WebAssembly, converted the rendering code to work on a seperate thread, made the simulation adapt if there is not enough processing power, and made it settle quite quickly.

Here is a little sample of what I have now using the Obsidian Hub vault for testing:

![image](https://user-images.githubusercontent.com/39423700/232738326-0bb3c0b3-39de-47d5-88be-4d539998e4e8.png)

**Comment by KosmosisDire** [comment]
Here is a live demo you can play around with as well (might not stay up forever, for future reference): 

https://nathang.dev/fileshare/misc/graph_view_demo/

**Comment by KosmosisDire** [comment]
This has been completed! YAY! Download the latest release to use it. It is now located in the experimental section under the settings.
