### ISSUE TITLE
Inline H1 titles not displayed in v1.8.0-10b

### ISSUE THREAD

**Issue by ryran** [KosmosisDire/obsidian-webpage-export#350]
**Describe the bug**
Just tried v1.8.0-10b and on export, my H1 titles don't show up. They're just missing. (Similar to what happened in #330 at one point, though I'm no longer using markdown to apply bold to headers.)

**Operating System**
Fedora Linux

**To Reproduce**
Here's the first few lines of my site's main page, whose filename is `index.md`:
```
---
title: A List of Resources on the Bahá’í Faith
---
# A List of Resources on the Bahá’í Faith

*Last updated: 2024-02-08*
{.h1-subtitle}
```
- How v1.8.0-9b exported that is available at [b19.org](https://b19.org/)
- How v1.8.0-10b exported that is available at [b19.org/junk2/](https://b19.org/junk2/)

**Screenshots**
![comparison](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/34d696ec-40b9-453d-bf2a-6720b37868f4)

### IMPORTANT: Error Log
![console](https://github.com/KosmosisDire/obsidian-webpage-export/assets/1092618/b5f508f3-2ba6-4caa-bd24-f086b4ea4540)

**Comment by KosmosisDire** [comment]
Ahh, thanks for catching this. I ill fix it in the next updated. In the mean time you can just fix this by adding this snippet:

```css
.page-title {
    display: block !important;
}
```

**Comment by KosmosisDire** [comment]
Can you verify this is fixed in 1.8.0-11b?

**Comment by ryran** [comment]
Looks good! Work-around snippet no longer needed.

**Comment by KosmosisDire** [comment]
Great, I'll close this then
