### ISSUE TITLE
Can't enable plugin...

### ISSUE THREAD

**Issue by zanodor** [KosmosisDire/obsidian-webpage-export#36]
...as the plugin is looking for the .obsidian folder which is non-existent as I had renamed to .pc before.  
I copied the plugin folder to .obsidian as well; still says "path doesn't exist."  
-- Win10

**Comment by KosmosisDire** [comment]
Hey thanks for this report. I'll see what I can do, should be relatively easy to fix.

**Comment by KosmosisDire** [comment]
Hello, this should be fixed in the latest update. Thanks for the report and let me know if you find any other problems! 😊
