### ISSUE TITLE
Windows 11 - Extra \ added to path after drive 

### ISSUE THREAD

**Issue by lavedon** [KosmosisDire/obsidian-webpage-export#360]
Hello!

Whenever I try to export an Obsidian note -- I get an error when selecting a path.  An extra \ is always inserted after C:
I am using Raw HTML Export.

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/5383938/253e1e9f-955f-43c5-be06-23db423ddf0b)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/5383938/0a1d82fd-8e52-41f1-9cf2-49987eac8cbe)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/5383938/572ab1b7-6604-4c74-aaf7-d528a182f34f)

There is no way to correct the extra \ 
It always gets auto inserted. If I don't try to use \ at all and just specify C:Users  etc. it won't export either.

Thank you very much!

**Comment by KosmosisDire** [comment]
This is how Windows normally formats paths, are you sure the path exists

**Comment by lavedon** [comment]
Sorry, should there not be just one \ after the drive? C:\  

If not this is highly embarrassing (for me). 

These paths exist:
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/5383938/2a38f49d-1375-4060-9922-f1f64c61b4a3)
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/5383938/c225a0c2-aef4-4ea0-a1cb-a8a47a749227)

Have I been confused about the basic facts of reality this entire time?  

Thanks, appreciate the quick response.

**Comment by KosmosisDire** [comment]
Both formats are valid, see this question for example: https://stackoverflow.com/questions/15969608/what-is-the-difference-between-and-in-file-path

So I think something else is wrong. Could use try using forward slashes instead?

**Comment by KosmosisDire** [comment]
Ohh wait do you have "open after export" enabled? I think file explorer might not like double backslashes, so maybe I should change it after all. Is the export succeeding? It should still succeed regardless

**Comment by KosmosisDire** [comment]
Okay I fixed that I will release it in 1.8.1. Idk why the whole of windows supports double backslash except for windows explorer lol
