### ISSUE TITLE
Embedded webpage in canvas doesn't render in HTML export.

### ISSUE THREAD

**Issue by vgyenge6** [KosmosisDire/obsidian-webpage-export#364]
Hi,

Embedded webpage in canvas doesn't render in HTML export.
![Canvas_webpageURL_embed_doesn't_render anything_2024-02-21](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/ad00f654-5694-48b3-94c3-1c168ef1c0c6)

Thank you for looking after.

Win 10 PRO
Firefox 122.01
Obsidian 1.5.3
your plugin version 1.8.0

**Comment by KosmosisDire** [comment]
What do you mean by embedded webpage? Do you mean just an iframe? Or are you using a plugin?

**Comment by vgyenge6** [comment]
here is a screenshot
![Embed_web_page_to_canvas](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/d433c889-96c9-4a86-a97c-3d6113460b74)

**Comment by KosmosisDire** [comment]
Ah, okay I will look into this

**Comment by KosmosisDire** [comment]
This should be added in 1.8.1-0b

**Comment by vgyenge6** [comment]
Hi,

It WORKS exactly as I expected. THANK YOU VERY MUCH 👍 🥇

**Comment by KosmosisDire** [comment]
Okay great I will close this
