### ISSUE TITLE
Export now shows "Web server exports must be hosted on an http / web server to be viewed correctly." on top of document

### ISSUE THREAD

**Issue by SuschNL** [KosmosisDire/obsidian-webpage-export#376]
**Describe the bug**
Text of "Web server exports must be hosted on an http / web server to be viewed correctly." shown over document

**Operating System**
Windows 10

**To Reproduce**
1. Export a note to HTML using the plugin

**Comment by aubreyz** [comment]
It seems completely reasonable for the pages to have a message if being viewed on a platform where they are not intended to be viewed. So not a bug. However it seems reasonable to enable the message to be turned off with a case of user beware.

**Comment by KosmosisDire** [comment]
You need to change the export mode to HTML documents rather than web server export if you want to open documents locally. Web Server exports will not load most content when opened locally, there is no reason to use them to open files locally since you can just use the HTML Documents export mode.

**Comment by SuschNL** [comment]
@aubreyz The plugin did not do this before, so it is some operational change in the latest update. Since I only ever export to HTML for offline viewing, this breaks my use case. I at first thought it was an issue/bug in the HTML creation.

@KosmosisDire Thank you, I adjusted this setting and it seems to resolve the issue, exporting files in the original format.
