### ISSUE TITLE
my search box and collapse button are shaped weird

### ISSUE THREAD

**Issue by hi-jin** [KosmosisDire/obsidian-webpage-export#378]
**Describe the bug**
My search box and collapse button are shaped weird.

**Operating System**
Mac OS (Sonoma 14.1.1)

**To Reproduce**
1. export
2. push to Git
3. publish on GitHub Pages

**Screenshots**
<img width="325" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/51053567/1dd3909d-79a3-45ad-9bef-92b6fb7177f9">

### IMPORTANT: Error Log
<img width="554" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/51053567/cdf95488-c820-4663-bcc7-051a7770dc8b">

**Comment by KosmosisDire** [comment]
Hi thanks this is a duplicate of #373. I am working on a fix. This issue is caused by the latest obsidian update. If you downgradee obsidian it will work fine.

**Comment by hi-jin** [comment]
Thank you for your really fast replying!
I downgrade it to 1.4.14 (Because it reproduced on 1.5.3).
But it makes same result.

Can you check if my downgrade is correct?



<img width="178" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/51053567/2246a61a-48c8-479c-bd62-450b06adc65a">

The image says,
"""
current version: v1.5.8
(installed version v1.4.14)

The app is the latest version!
"""

I just downloaded launcher of lower version on official github and installed it.

**Comment by hi-jin** [comment]
Oh it was not.
I downgraded it now.

I will close this issue because this is duplicated.

Thank you!

**Comment by KosmosisDire** [comment]
Okay great glad you got it fixed! I am working on the real fix as I am typing this, so it should be out soon!
