### ISSUE TITLE
After changing the File Navigation Settings I lost both the Graph and Search selections under Page Features

### ISSUE THREAD

**Issue by vgyenge6** [KosmosisDire/obsidian-webpage-export#383]
**Perhaps is it a bug?**
After changing the plugin Settings - changing between whether I want file tree navigation or not - I lost both the Graph and Search selections under Page Features. I did not restart Obsidian between the changing.

**Operating System**
Win 10 PRO
Obsidian 1.5.3.
your plugin version 1.8.1.0b

**To Reproduce**

1. Go to 'Settings'
2. Click on 'File navigation' unset
3. **When you go back to the Settings you will not see the possible Graph and Search selections settings again even when you set/allow back the File navigation.** 

It was already noticed in the previous version 1.8.0, but I focused on else issues, thus I did not report then.

Thanks for your looking after.

**Comment by KosmosisDire** [comment]
This is because you have selected html documents export preset which does not support the graph view or search.

**Comment by vgyenge6** [comment]
Hi, 

Thanks, understood. I tried to select the Online Web Server preset and got back both.
I close this issue.
