### ISSUE TITLE
Add style support for Canvas Style Menu and Colored Tags Wrangler

### ISSUE THREAD

**Issue by vgyenge6** [KosmosisDire/obsidian-webpage-export#384]
Hi, 

That's great the installed plugins and their styles can be selected. But I noticed that even though some of them are selected their look in Obsidian does not render in HTML.

It is not a big problem for me, but it would be good to see them working in HTML too. :)

Thanks for looking after when you have time for that.
![Some_plugins_styles_settings_does_not_work](https://github.com/KosmosisDire/obsidian-webpage-export/assets/100508773/3c6df121-8297-4804-91af-94e59d6f4e7b)

**Comment by KosmosisDire** [comment]
If that plugin's styles are actually being included, which by your description I beleive they are. Then those pluigns are probably managing their actual styles internally in which case it isn't easily possible to make their styles work. Especially with something like fold anywhere which is not just style based. Folding required scripts as well. 

I will look at Canvas Style Menu and Colored Tags Wrangler

**Comment by vgyenge6** [comment]
Thank you for looking after Canvas Style Menu and Colored Tags Wrangler plugins' styles, and opening a new issue for that enhancement.

Regarding
> Especially with something like fold anywhere which is not just style based. Folding required scripts as well.

Yes, surely requires at least onclick inline script or something similar to work. However, 'folding'
 in this case, hiding and showing some blocks in HTML may be quite a frequent claim. Obsidian has not any built-in function supporting this. There is 
 ```
<details>
<summary></summary>
Write something here
</details>
```
which can work for hiding showing content in obsidian (I'm using it and also works in the HTML export output), however, the SUMMARY HTML element inside can contain only HTML elements. Thus for example I can not involve e.g. tags, inline fields, and inline or any dataview query either. Thus if I want to show/hide such content I  thought to use the 'Fold Anywhere' plugin. 
If I use my own written script to show/hide that also requires the content to be involved in a HTML element e.g DIV what same problem as the SUMMARY which does not require any script written :))

Have you any suggestions how could I resolve this??

**Comment by KosmosisDire** [comment]
The fold anywhere plugin doesn't even work in reading mode. I would suggest finding your own solution for this as it is a very niche behavior. I cannot implement the fold anywhere plugin into this plugin, sorry.

**Comment by vgyenge6** [comment]
Hi,
You are right. It doesn't work in reading work. I did not notice until :(

> I cannot implement the fold anywhere plugin into this plugin, sorry.
Okay understood.

There is a harsh resolution, simply I do not plan to fold such contents, or if those are properties like (As in my case but not put on the frontmatter, however inline fields) I will simply delete them from the HTML file by hand.

**Comment by KosmosisDire** [comment]
The plugin Canvas Style Menu is not available in the community plugins so I will not add support for it (unless it becomes quite popular or is added to the market). However I was able to add support for colored tags

**Comment by KosmosisDire** [comment]
I would reccomend you just use the Advanced Canvas plugin which supports many canvas styling features and is already supported by this plugin.

**Comment by KosmosisDire** [comment]
I added this in 1.8.1-2b

**Comment by vgyenge6** [comment]
> The plugin Canvas Style Menu is not available in the community plugins

Yes, that is not. But, somehow interested me to try. I accept you won't deal with that until becoming popular. Okay.

> I would reccomend you just use the Advanced Canvas plugin... and is already supported by this plugin.

Thank you for your suggestion I will try it.

>However I was able to add support for colored tags

>I added this in 1.8.1-2b

Thank you! I will try this release and come back to react.

**Comment by vgyenge6** [comment]
Hi,

>However I was able to add support for colored tags

I tried. Supporting Colored Tags Wrangler works fine in the exported HTML. Thank you very much 👍 

>I would reccomend you just use the Advanced Canvas

I installed and tried it. Supporting Advanced Canvas works fine too in the exported HTML. Thank you very much 👍 

I short, supporting both plugins works fine now in the 1.8.1.2b Pre-release! 🥇
