### ISSUE TITLE
[Bug]: UNC paths no longer recognised in beta 

### ISSUE THREAD

**Issue by jrjdavidson** [KosmosisDire/obsidian-webpage-export#388]
### What happened?

kia ora, 
updated to the beta [1.8.1-1b](https://github.com/KosmosisDire/obsidian-webpage-export/releases/tag/1.8.1-1b) by copying over the files in the webpage-export folder in the plugins folrder of my vault.
Once update, I get an error message saying that the folder doesn't exist. The path to the folder is UNC path. 
Here are a couple of screenshots, first in 1.8.0: 
<img width="742" alt="UNC1" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/46798391/223307d8-4be8-408b-b65b-23f4273654c6">
in 1.8.1-1b
<img width="751" alt="UNC2" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/46798391/ae9b4f00-1402-4a97-9056-138ce767315a">

If I keep the data.json file intact in the folder, I am still able to export, despite the error message. If I delete the data.json file, the export button becomes grayed out.

### Reproduction

update to beta and try to export to a UNC path

### Version

1.8.1-1b

### Operating System

windows 10

### Obsidian Version

1.5.8

### Relevant log output

```yaml
Log:
[WARNING] Failed to load search-index.json. Creating new index.	{}
[WARNING] 	Creating an RSS feed requires a site url to be set in the export settings.
[INFO] 	Using "historic aerial imagery" header as title because it was H1 at the top of the page
[INFO] 	Closing render window


Settings:
	settingsVersion --------- 1.8.1-1b
	makeOfflineCompatible     false
	inlineAssets ------------ false
	includePluginCSS          []
	includeSvelteCSS -------- true
	titleProperty             title
	customHeadContentPath ---
	faviconPath              
	documentWidth ----------- 40em
	sidebarWidth              20em
	minOutlineCollapse ------ 2
	startOutlineCollapsed     false
	relativeOutlineLinks ---- false
	allowFoldingHeadings      true
	allowFoldingLists ------- true
	allowResizingSidebars     true
	logLevel ---------------- warning
	minifyHTML                true
	makeNamesWebStyle ------- true
	onlyExportModified        true
	deleteOldFiles ---------- true
	addThemeToggle            true
	addOutline -------------- true
	addFileNav                true
	addSearchBar ------------ true
	addGraphView              true
	addTitle ---------------- true
	addRSSFeed                true
	siteURL -----------------
	authorName               
	vaultTitle -------------- Crustal Geology and Modeling
	exportPreset              website
	openAfterExport --------- false
	graphAttractionForce      1
	graphLinkLength --------- 10
	graphRepulsionForce       150
	graphCentralForce ------- 3
	graphEdgePruning          100
	graphMinNodeSize -------- 3
	graphMaxNodeSize          7
	showDefaultTreeIcons ---- false
	emojiStyle                Native
	defaultFileIcon --------- lucide//file
	defaultFolderIcon         lucide//folder
	defaultMediaIcon -------- lucide//file-image
	exportPath                //seesalsdo1p/ALSDO/SEE/modeling
	filesToExport ----------- 0
	filePickerBlacklist       [
	filePickerWhitelist ----- [


Enabled Plugins:
	Pandoc Plugin
	Webpage HTML Export
```

**Comment by KosmosisDire** [comment]
Thanks for the report, I believe I know what's wrong, I'll try and get a fix out for this.

**Comment by KosmosisDire** [comment]
This is fixed in 1.8.1-2b, let me know if you still ahve issues

**Comment by jrjdavidson** [comment]
Export works, but there seems to be a relative path issue?
![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/46798391/7a992c7b-474e-41dc-967a-b9dad4d24d4b)

**Comment by jrjdavidson** [comment]
also, export button stays disabled, even if the path is set. IT is re-enabled if you edit the text.

**Comment by KosmosisDire** [comment]
> Export works, but there seems to be a relative path issue?
Is this actually causing an issue or are these just errors in the console?

**Comment by KosmosisDire** [comment]
> also, export button stays disabled, even if the path is set. IT is re-enabled if you edit the text.

I will look into this

**Comment by jrjdavidson** [comment]
> > Export works, but there seems to be a relative path issue?
> 
> Is this actually causing an issue or are these just errors in the console?

That's a chrome console screengrab, when trying to visit an exported page.

**Comment by KosmosisDire** [comment]
Oh okay, so it is breaking it to nothing will load. Are you exporting using the Online Web Server mode or the HTML Documents mode?

**Comment by jrjdavidson** [comment]
Online Web Server

**Comment by KosmosisDire** [comment]
Okay, I will look into it. I guess for some reason the paths aren't being remapped correctly

**Comment by jrjdavidson** [comment]
i had another go at exporting with the latest release, and the issue seems resolved.
