### ISSUE TITLE
[Bug]: Cannot select text on my page after uploading to webhost

### ISSUE THREAD

**Issue by ckrakou** [KosmosisDire/obsidian-webpage-export#393]
### What happened?

When exporting part as a vault in both Online Web Server mode and HTML Documents mode and uploading the resulting files to my webhost, I cannot select the text on the pages for copy-pasting. This functionality is present in other vaults exported to websites, including the documentation site for this plugin. 

So far I have tried exporting the files in the two modes mentioned above and disabling CSS for other community plugins, but the error persists. 

### Reproduction

Export part of a vault in one of the two mentioned modes. The part of the vault that is exported has an index.html file in the root. Zip the files, upload to a simply.com web host, and ask the upload wizard to unpack the zip file. 

The error is present on my page here: www.krakou.dk/undervisningsmateriale. I have attached the zip file with my exported vault. 
[export.zip](https://github.com/KosmosisDire/obsidian-webpage-export/files/14507178/export.zip)

### Version

1.8.0

### Operating System

MacOS/osX and Manjaro Linux

### Obsidian Version

1.5.8

### Which browsers can you reproduce this in?

Firefox

### Relevant log output

```yaml
N/A
```

**Comment by KosmosisDire** [comment]
Hi this is likely because of this bug which was caused by an obsidian update: #373 
To fix this update to the beta version or downgrade obsidian to something lower than 1.5.8

**Comment by ckrakou** [comment]
Thanks for the quick answer. I'm running an arch-based version of linux so there's no native beta version. I'll wait for a stable release, since my site is a nice-to-have, not a need to have. Good to know there's a fix out there.

**Comment by KosmosisDire** [comment]
By the beta version I meant the beta version of the plugin, which you should be able to install on linux. You can check out the readme for instructions on how to install it.

**Comment by KosmosisDire** [comment]
I actually just released a stable patch for this problem haha, so you should be able to update the plugin normally to get a stable release that fixes this problem. Let me know if it does the trick :)
