### ISSUE TITLE
[Bug]:1.5.8+1.8.0.1 There has been a change in the style upon export, and the documents and icons do not look normal.

### ISSUE THREAD

**Issue by zhoulonghao520** [KosmosisDire/obsidian-webpage-export#395]
### What happened?

![image](https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/20da0297-64b1-4b54-81e1-d589a50d36e0)

### Reproduction

Version 1.5.8
Version 1.8.0.1

There has been a change in the style upon export, and the documents and icons do not look normal.

### Version

V1.8.0.1

### Operating System

window11

### Obsidian Version

V1.5.8

### Relevant log output

```yaml
N/A
```

**Comment by KosmosisDire** [comment]
Hi, this is a bug with 1.8.0 that was fixed in 1.8.01. Can you try deleting your export and creating a new export, and also try restarting obsidian.

**Comment by zhoulonghao520** [comment]
<img width="1003" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/144794808/758f13d7-7f03-4678-bb66-0ec35fd7987a">


Is this the version you are referring to? Are you saying that OB 1.5.8 + 1.8.01 does not have this issue? I will try reinstalling it.

**Comment by KosmosisDire** [comment]
Yes that version should not have this issue with obsidian 1.5.8. It has fixed the issue for everyone who has tried it so far including me. If that does not work you can try using the beta version. Make sure you clear your browser's cache as well! It may have cached the corupted style sheets.

**Comment by zhoulonghao520** [comment]
I just tried it. It's great. The browsing speed is very fast, and after collapsing the panel, reading the document becomes much more convenient.

After managing for four months, I finally upgraded from OB version 1.3.5 to version 1.5.8.


Thank you very much for creating this plugin, it's amazing.

**Comment by KosmosisDire** [comment]
Okay awesome, I will close this issue then
