### ISSUE TITLE
[Bug]: sometimes data view queries render with empty fields in the exported HTML

### ISSUE THREAD

**Issue by klintusfang** [KosmosisDire/obsidian-webpage-export#397]
### What happened?

This won't be a surprise to you cause I see it has been posted multiple times before and never fully root caused.  I am filing this because I have noticed some absolutely pathological patterns in trying to root cause it on my end, that might be helpful in determining why this seems to sometimes happen.

- It doesn't seem to matter if its a TABLE or a LIST.  It can happen for both.
- it doesn't seem to matter if the queries are simple or complex.
- it doesn't seem to get better if i restrict the number of files the query has to search across by using FROM "directory_path".
- It doesn't seem to matter if its a note with lots of dataview queries, or just one.  I've seen it happen on small files that have only one very simple query, and i've seen it happen on notes with lots of dataview queries.  And i've also seen notes with dozens of complex dataview queries where it happens on none of them.
- If it does happen, it does appear to *always be the last* dataview query in the note that has the problem (so, i'm starting to work-around it by putting a dummy data view query that i don't care about at the end of any note that doesn't export properly :-0).  So its seems related to something that's going wrong near the end of the render of the note...
- Here is the most pathological thing though.  I had a note with 3 dataview queries where no matter what order i put the three data view queries in, the last of the three would fail to render and would just be blank on every row.  So i tried doing every dataview query twice in that note so that there were 6 dataview queries in the note, so see if it still would "just be the last of the 6" that had the problem.  And when i did that...  ALL 6 of the dataview queries rendered in the exorted HTML correctly!  I.e., i effectively doubled the amount of time it should have taken to process all the dataview queries and the problem disappeared for that note!

I could give you samples of the notes, but... you've not been able to reproduce this before when people have posted it...i'm sure the same will be true with my samples.

but i'm starting to wonder, if this is related to the processing power of the machine being used or if it is some multi-threading artifact/bug.  some failed syncronization across threads if threads are multi-threaded is the only thing I can think of that might be as random as this one seems to be.  do you know if there is any multi-threading going on here?  

I poked a little into that myself...   Obsidian itself is multi-threaded.  It has 4 processes running on my machine right now.  it doesn't fork any new threads when i invoke the HTML Export plugin, but more than one of its threads jump to high activity when I invoke the plugin.  so something about the plugin does appear to be running on multiple threads when it is invoked.

### Reproduction

Difficult to say.  read my description of what happened.  You'll understand.

### Last Working Version

none.  i've seen this problem intermittently on every version of the plugin since i started using it in January of 2023.

### Version

1.8.01

### Operating System

Windows 11

### Obsidian Version

1.5.8

### Relevant log output

```yaml
n/a
```

**Comment by KosmosisDire** [comment]
This is actually fixed in the beta version haha, try it out and let me know if it's fixed

**Comment by klintusfang** [comment]
let me try that.  this will require me to learn how to install a beta version of a plugin, which i tend to avoid, but this time...it'll be worth it.

**Comment by KosmosisDire** [comment]
The instructions for how to do that are in the readme of the plugin

**Comment by klintusfang** [comment]
i figured it out.  just used BRAT.  and for the ones i've tested, the beta version fixed the problem.  

Though when i tried to then test on my entire vault in one go.  the plugin crashed one of the obidian threads and killed obsidian.  So i can't say if it fixed everything yet.

**Comment by klintusfang** [comment]
the beta version of the plugin appears to have a memory leak that looks like it probably kicks in somewhere around the point where its total memory usage exceeds 4 GB.  

If i give it enough to work on that it's memory footprint grows beyond 4 GB before it finishes, it still usually finishes, and creates all the files though... after it shuts down 3 GB of the memory it allocated while it was rendering remaing allocated to the obsidian process indefinitely till i kill obsidian.

but...other than that, and that it crashes obsidian if i don't restrict how much it is exporting some...the original problem appears to be fixed in beta.

**Comment by klintusfang** [comment]
i do have one small minor issue with the rendering still.  i'll file a separate issue on it if it persists, but the only thing that doesn't render now, is notes that contain very simple inline dataview queries.  specifically this one:

`=this.alignments`

the alignments property in my note's YAML is an array, and the above line renders correctly if the array has one entry.  but it renders as 

=this.alignments

in plane text, whenever the alignments array has 2 entries in it.  This did happen before the beta version too, and seems separate from the other issue, so i'll post it separately later.

**Comment by klintusfang** [comment]
either way this item can be close because these new problems are...clearly something else.  and the one in the topic of this  post is...resolved in beta.

thanks!!
