### ISSUE TITLE
Failed to load plugin

### ISSUE THREAD

**Issue by Philogamous** [KosmosisDire/obsidian-webpage-export#4]
Hello!
This looks awesome, but I can't get it working on my end.
I'm on Windows 10 and Default theme.  I've installed manually to the plugins folder.  It shows up properly on the list of plugins in Obsidian, but when I go to enable the plugin I get a "Failed to load plugin" message.
Thanks for your time :-)

**Comment by KosmosisDire** [comment]
If you press Ctrl + Shift + i, then open the console and clear it. Then turn off the plugin and turn it back on could you give me a screen grab or copy of what is output there?

Also, could you try it in a clean vault without any other plugins installed, just to test if it is another plugin causing this?

Thanks for the report!

**Comment by Philogamous** [comment]
![Screenshot-2022-12-14-142702](https://user-images.githubusercontent.com/120601736/207719070-5317c8c3-cf6c-4ffc-930f-3f17233cb341.png)

Tried in a clean vault as well, same error.

**Comment by KosmosisDire** [comment]
It seems to not think that you have installed it correctly. It says it can't find main.js in the plugin's directory

**Comment by KosmosisDire** [comment]
Can you show a screenshot of the plugin's directory in explorer?

**Comment by KosmosisDire** [comment]
You have to download it from the releases page and then extract that into the plugins folder. Make sure to extract it into a folder called obsidian-webpage-export, and that it exports with all the main files directly under that folder.

(It should be plugin's/obsidian-webpage-export/main.js, etc...)

**Comment by Philogamous** [comment]
Oh wow, my bad.  Am new to GitHub and programming in general :-)
It seems to have worked now.  Is it meant to generate separate .html files for each .md file?  Or one .html file for the whole vault?

Also, out of curiosity, is this going to be added to the official Community Plugins list eventually?

**Comment by KosmosisDire** [comment]
It generates separate ones for each file. I might eventually add a feature to have a file list on the left side that shows the file system. But on a technical level it has to export one .html file per .MD file. You can tell it to export the whole vault but it will just export the whole file structure, not one file.

It will be added to the official plugins. I have it submitted and have to make some changes before it's accepted. But it will eventually be there

**Comment by Philogamous** [comment]
Very cool!
Well thanks for the help and the work you do, great plugin.
Cheers!
