### ISSUE TITLE
Special characters in links or file names cause export to fail

### ISSUE THREAD

**Issue by ZepDonald** [KosmosisDire/obsidian-webpage-export#40]
**Describe the bug**  
On one page, the export won't work. Instead nothing happens (with no error message popup shown) and an error gets logged at the console (see below).

With version 1.4.0 of the plugin everything was working fine.

**Operating System**  
macOS 13.2.1

**To Reproduce**  
I don't know how to reproduce the bug, because it happens on only one page.

The page has a Dataview part and a list of internal links (around 150 links, handled by the plugin Waypoint). I use the same "template" (Dataview part and list of internal links) on other pages where this isn't happening. 

**Screenshots**
If applicable, add screenshots here to help explain your problem (just copy paste)

### IMPORTANT: Error Log
```
Uncaught (in promise) URIError: URI malformed
    at decodeURI (<anonymous>)
    at Utils.makePathUnicodeCompatible (plugin:webpage-html-export:6158:12)
    at Utils.parsePath (plugin:webpage-html-export:6124:17)
    at HTMLAnchorElement.eval (plugin:webpage-html-export:7048:42)
    at Function.each (plugin:webpage-html-export:412:28)
    at jQuery2.fn.init.each (plugin:webpage-html-export:300:26)
    at HTMLGenerator.fixLinks (plugin:webpage-html-export:7025:35)
    at HTMLGenerator.getCurrentFileHTML (plugin:webpage-html-export:6845:10)
    at async HTMLExportPlugin.exportFile (plugin:webpage-html-export:7333:18)
    at async HTMLExportPlugin.exportFolder (plugin:webpage-html-export:7391:9)
makePathUnicodeCompatible @ plugin:webpage-html-export:6158
parsePath @ plugin:webpage-html-export:6124
eval @ plugin:webpage-html-export:7048
each @ plugin:webpage-html-export:412
each @ plugin:webpage-html-export:300
fixLinks @ plugin:webpage-html-export:7025
getCurrentFileHTML @ plugin:webpage-html-export:6845
```

**Comment by KosmosisDire** [comment]
Hey, thanks for the report. It is hard for me to do anything about this if I can't reproduce it. Are any of the links invalid by any chance? Do any of the links have non-latin characters? Could you try and mess around changing things until it stops happening (like moving the file to different folders, removing dataview, removing waypoint) and test after each change.

**Comment by ZepDonald** [comment]
Thanks for the reply. And by the way, thanks for the great plug-in.

The links shouldn‘t be invalid because they are created by the plug-in Waypoint. I can‘t even change them because Waypoint will directly change them back.
I also don‘t have non-Latin characters, but some non-English characters (like ä, ö, ü), but they are all over my vault and work without any issues on all of the other pages.

I can send you the part of my vault, that’s causing the problem. So you can try to reproduce the error, if that’s fine for you. Might be the easiest solution (I guess).

I will also try to play around with the installed plugins to see if any of them is the culprit after this weekend and report back.

**Comment by KosmosisDire** [comment]
If you could send that that would be helpful, thanks!

**Comment by ZepDonald** [comment]
I tried to deactivate Waypoint and Dataview but without success.

I also looked briefly through the file names/links and found a page with a title containing both a `>`and `%` character. After removing both of them, the export worked. It would be great, if these characters would also work, but I understand, that this might be much work.

You can still download the part of my vault [here](https://nx.von-au.net/s/CaawHXYt7As2ooF) and see for yourself. The file "Commerzbank- >50% Der Offenen Stellen Entfallen Auf Sofia, Prag Und Lodz.md" was making problems. The download doesn't contain any private information, therefore you can download right away.

**Comment by KosmosisDire** [comment]
Thanks for looking throught his, I figured it might be something like that. Theoretically it shouldn't be too hard to fix, but issues with special characters in links keep popping up. I'll see what I can do. Thanks again for the report!

**Comment by ZepDonald** [comment]
Thanks for your effort! The fix is not urgent in my opinion, because I know how to fix the root cause by myself. But still, it would be great, if it could be fixed somewhere in the future. 😊

**Comment by ThomasLudwig** [comment]
Hi,
I had the same issue, it was indeed due to a % in the title/filename

**Comment by KosmosisDire** [comment]
I think I have gotten rid of all these errors in the latest few updates, but let me know if there is still a problem!
