### ISSUE TITLE
Error: Path does not exist

### ISSUE THREAD

**Issue by zcysxy** [KosmosisDire/obsidian-webpage-export#41]
**Describe the bug**
When exporting a page, some errors occurs (see the screenshot attached). Seems like the plugin is referring to some non-exist CSS files. Those file did exist before, but I have already removed them.

**Operating System**
- macOS 12.6.1
- Obsidian 1.1.14

**To Reproduce**
Execute command `Export current file to HTML`.

**Screenshots**
<img width="309" alt="image" src="https://user-images.githubusercontent.com/48207708/219714447-dba3c60b-62f4-47a7-b075-abf19d8a28a6.png">

### IMPORTANT: Error Log
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/48207708/219714710-c1d5a827-6a01-4122-8b77-71b928ff5558.png">

**Comment by KosmosisDire** [comment]
Hello, if these are snippets that you deleted, then restarting obsidian should fix this I think, let me know if it doesn't. However, I will definetly try to fix this so it won't happen in the future. Thanks!

**Comment by zcysxy** [comment]
I restarted it several times but had no luck. The weirdest thing is that there are no such strings or files in the vault (including hidden folders). Maybe Obsidian itself keeps some log of it 😨. This doesn't happen in other vaults.

<img width="451" alt="image" src="https://user-images.githubusercontent.com/48207708/219845538-60a078f2-beb4-41af-bc09-417f595f71e3.png">
<img width="390" alt="image" src="https://user-images.githubusercontent.com/48207708/219845544-061d9524-00e6-4b88-ab09-838bda033efb.png">

**Comment by KosmosisDire** [comment]
The plugin uses the obsidian API to get the list of enabled snippets. It seems like maybe obsidian isn't updating the list correctly. Does the document still export or does this break it?

**Comment by zcysxy** [comment]
You are right! I tested in the console, and it's an Obsidian API problem. I'll report it on the forum. The exported HTML is blank.

**Comment by KosmosisDire** [comment]
Thanks! If I make another release before it has been fixed then I'll probably include a temporary fix for this.

**Comment by KosmosisDire** [comment]
I have made sure that this bug does not effect the functionality of the plugin, however the error persists as obsidian have not fixed it as of yet. But since it no longer causes issues I will close this. Thanks for the report, let me kow if you find any other problems! :)
