### ISSUE TITLE
[Bug]: firefox caret not opening

### ISSUE THREAD

**Issue by jrjdavidson** [KosmosisDire/obsidian-webpage-export#410]
### What happened?

once the page was exported with the latest release, I tried the exported page on firefox and found enexpected behaviour in the site map sidebae.  It looks like there is some selector issue, here is the firefox console output:

> Included file: lib/html/file-tree.html 2 [index.html:14:6773](https://alsdo.canterbury.ac.nz/SEE/modeling/historicimagery/index.html)
WebGL context was lost. [isWebGLSupported.ts:43:36](https://cdnjs.cloudflare.com/ajax/packages/utils/src/browser/isWebGLSupported.ts)
Module Ready [graph-view.js:1:8108](https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/graph-view.js)
Init called [graph-wasm.js:1:6971](https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/graph-wasm.js)
Error: SyntaxError: Document.querySelector: '.sidebar:has(#graph-canvas)' is not a valid selector
>
> Using fallback. [graph-view.js:1:3861](https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/graph-view.js)
Uncaught (in promise) DOMException: Document.querySelector: '.file-tree .tree-item:has(>.tree-link[href^="https://alsdo.canterbury.ac.nz/SEE/modeling/historicimagery/index.html"])' is not a valid selector
    setActiveDocument https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/webpage.js:1
    initializeGraphView https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/graph-view.js:1
    e https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/graph-wasm.js:1
    run https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/graph-wasm.js:1
    e https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/graph-wasm.js:1
    removeRunDependency https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/graph-wasm.js:1
    n https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/graph-wasm.js:1
    createWasm https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/graph-wasm.js:1
[webpage.js:1](https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/webpage.js)
Setting root path: ../ [webpage.js:1:18905](https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/webpage.js)
Uncaught (in promise) DOMException: Document.querySelectorAll: '.tree-container.file-tree .tree-item:has(.collapse-icon) > .tree-link' is not a valid selector
    setupTrees https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/webpage.js:1
    initializePageEvents https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/webpage.js:1
    onload https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/webpage.js:1
[webpage.js:1](https://alsdo.canterbury.ac.nz/SEE/modeling/lib/scripts/webpage.js)
WebGL context was lost.

No problems on Chrome

### Reproduction

export page with sitemap webpage, including subfolder, and try to open subfolders. On firefox

### Last Working Version

not sure if it ever did

### Version

 1.8.01 Latest

### Operating System

windows 10

### Obsidian Version

1.5.3

### Which browsers can you reproduce this in?

Firefox

### Relevant log output

```yaml
1.8.01 Latest
```

**Comment by KosmosisDire** [comment]
What version of firefox are you using? Firefox has only recently started to support the :has selector which may be causing the problem.

**Comment by jrjdavidson** [comment]
117.0

**Comment by KosmosisDire** [comment]
That is the problem, the has selector is only supported in firefox 121+

**Comment by jrjdavidson** [comment]
ok makes sense - i think we have firefox ESR so upgrades are slower!

**Comment by KosmosisDire** [comment]
If you want to and are able to you can enable it in this version of firefox manually by going to `about:config` in your firefox url bar and then enabling the `layout.css.has-selector.enabled` flag.
