### ISSUE TITLE
[Bug]: Mark names webstyle for new version

### ISSUE THREAD

**Issue by I2rys** [KosmosisDire/obsidian-webpage-export#418]
### What happened?

With the new version it seems like when exporting on "Online Web Server" the files doesn't show up in explorer and If I export on "HTML Documents" the files are exported non marked-names webstyle so my static server can't serve them unless they are all lowercase.

### Reproduction

Using the new version just export with the "HTML Documents" because "Online Web Server" doesn't work too.

### Last Working Version

1.73

### Version

latest

### Operating System

Windows 10

### Obsidian Version

1.5.3

### Which browsers can you reproduce this in?

Firefox, Chrome, Chrome IOS, Safari, Safari IOS, Microsoft Edge

### Relevant log output

```yaml
N/A
```

### Additional Info

N/A

**Comment by KosmosisDire** [comment]
When you say that the online web server export doesn't show in the file explorer what do you mean?

**Comment by I2rys** [comment]
> When you say that the online web server export doesn't show in the file explorer what do you mean?

The files doesn't load on the explorer.

**Comment by I2rys** [comment]
Oh It's fixed now. Thank you!
