### ISSUE TITLE
Add support for the leaflet plugin

### ISSUE THREAD

**Issue by yarell1972** [KosmosisDire/obsidian-webpage-export#422]
When exporting a vault, any notes that use the leaflet plugin to display interactive maps with pins just show as an off-centered static image with no interactivity.

**Comment by KosmosisDire** [comment]
There is no easy way for me to add interactivity from plugins. If plugins change the look of the page or add content the plugin can handle that, however if you want functionality I would literally have to rewrite the leaflet plugin and embed it into the webpage, which is obviously not worth it. So unfortunately I am not able to do anything about this, sorry! 

Thank you for using the plugin though and for the request :)
