### ISSUE TITLE
Insert <meta charset="utf-8"> by default on generating html.

### ISSUE THREAD

**Issue by R4wd0g** [KosmosisDire/obsidian-webpage-export#43]
**Is your feature request related to a problem? Please describe.**
Depending on the host, the special characters isn't showing properly. 

**Describe the solution you'd like**
On generating .html file, please, add the charset utft8 meta tag on the header section to support all languages: 

```html
<meta charset="utf-8">
```

**Additional context**

**Comment by KosmosisDire** [comment]
Thank you! I hadn't thought of this but you are totally right. This is a pretty easy fix so I'll add it right away

**Comment by KosmosisDire** [comment]
This should be fixed in the latest update. Thanks for the report and let me know if you find any other problems! 😊

**Comment by Chupakabra0** [comment]
<meta charset="utf-8"> doesn't generating in html doc if custom html/js option is enabled on [1.9.0-3b](https://github.com/KosmosisDire/obsidian-webpage-export/releases/tag/1.9.0-3b) version.
