### ISSUE TITLE
[BUG]: Exports are empty when files are opened in editing view by default

### ISSUE THREAD

**Issue by kelco-chan** [KosmosisDire/obsidian-webpage-export#44]
Hello,

# Expected Behavior
The resulting HTML file when exporting a page is not empty

# Actual Behavior
HTML file only has empty content tree and dark mode toggle button
![image](https://user-images.githubusercontent.com/60736592/222951423-4f1f0fd7-0d2b-458d-8056-a20dd6fccc3e.png)

# Occurs when
Default view for new tabs is set to `editing view`; the problem goes away once this setting is changed to `reading view`.
![image](https://user-images.githubusercontent.com/60736592/222951343-9c17ea78-716d-4562-9c6a-274272c02fae.png)

# Possible ways to patch this bug
1) remind new users to set their new tabs to open in reading view by default
2) When a file is exported, a tab is temporarily opened and closed for that page. Perhaps code in something to make it automatically

# Additional comments
This was very confusing for me to figure out which was why I uninstalled it at first because it didn't work but then I saw that it did work for some people; I think this plugin will be much better appreciated by newcomers given that a decent chunk of people use editing mode by default.

Best Regards,
kelco-chan

**Comment by KosmosisDire** [comment]
Hmm, the plugin does currently open a new tab and then automatically changes that tab into reading mode even if it is in edit mode. So I am not sure why this is. I'll certainly look into this and try to fix it. Thanks for the report!

**Comment by KosmosisDire** [comment]
This should be fixed in the latest update due to the new background export feature! Thanks for the report and let me know if you find any other problems! 😊
