### ISSUE TITLE
[Bug]: media files are not updated when exporting

### ISSUE THREAD

**Issue by hcgilje** [KosmosisDire/obsidian-webpage-export#448]
### What happened?

in obsidian I have image and video files in a media folder inside the vault. When I export (with only modified files selected as option) a document with images these imagea are not placed in the media folder in the exported material.
Also it seems the relevant content in the bin folder is not updated, as only the last document appears in the left column.
Search only works within the last exported document.

### Reproduction

export mode: online server.
I already have exported a number of documents so there already exists several html documents, a media folder and the lib folder. When I export another document I discover that the image files are missing when testing the html file in a browser. Also I am not able to access the other documents, as only the latest exported document appears in the left column.
Workaround is to delete the media and bin folder before export, but this is very cumbersome when just doing incremental exports.
### Last Working Version

this is the first version I use

### Version

1.8.01

### Operating System

macOS

### Obsidian Version

1.5.12

### Which browsers can you reproduce this in?

Firefox

### Relevant log output

```yaml
Log:
[WARNING] 	No existing export metadata found. All files will be exported.
[WARNING] 	No existing search index found. All files will be exported.
[WARNING] 	No existing RSS feed found. All files will be exported.
[INFO] 	Closing render window
[INFO] 	Closing render window
[INFO] 	Closing render window
[INFO] 	Closing render window
[INFO] 	Closing render window


Settings:
	settingsVersion --------- 1.8.01
	makeOfflineCompatible     false
	inlineAssets ------------ false
	includePluginCSS          1 plugins included
	includeSvelteCSS -------- true
	titleProperty             title
	customHeadContentPath ---
	faviconPath              
	documentWidth ----------- 40em
	sidebarWidth              20em
	minOutlineCollapse ------ 2
	startOutlineCollapsed     false
	allowFoldingHeadings ---- true
	allowFoldingLists         true
	allowResizingSidebars --- true
	logLevel                  warning
	minifyHTML -------------- true
	makeNamesWebStyle         true
	onlyExportModified ------ true
	deleteOldFiles            false
	addThemeToggle ---------- true
	addOutline                true
	addFileNav -------------- true
	addSearchBar              true
	addGraphView ------------ true
	addTitle                  true
	addRSSFeed -------------- true
	siteURL                   http://localhost:3000/
	authorName --------------
	vaultTitle                testvault
	exportPreset ------------ website
	openAfterExport           false
	graphAttractionForce ---- 1
	graphLinkLength           10
	graphRepulsionForce ----- 150
	graphCentralForce         3
	graphEdgePruning -------- 100
	graphMinNodeSize          3
	graphMaxNodeSize -------- 7
	showDefaultTreeIcons      false
	emojiStyle -------------- Native
	defaultFileIcon           lucide//file
	defaultFolderIcon ------- lucide//folder
	defaultMediaIcon          lucide//file-image
	exportPath -------------- /Users/hcg/lab/localserver
	filesToExport             1


Enabled Plugins:
	Webpage HTML Export
	Templater
	Dataview
	Update modified date
```

### Additional Info
<img width="235" alt="Skjermbilde 2024-06-05 kl  13 04 23" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/1252621/8cce2bdd-8c62-4bf6-852c-fada5b0665fb">

This is the structure of my folder:  html files + media folder and bin folder. Media folder is not being updated when exporting

<img width="218" alt="Skjermbilde 2024-06-05 kl  13 59 14" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/1252621/20a264ab-4997-4f17-b03b-78029b2dc597">

this is the structure of my vault

**Comment by KosmosisDire** [comment]
How are you selecting files to export? You should always have all the files you wish to have in your export selected in the left hand file selector. That selector should always represent every file you want to exist in the exported vault, not just new files! It will figure out which ones need to be updated for you.

**Comment by hcgilje** [comment]
I did it wrong first by only selecting the new file, but then I did it again with everything selected (except the templates folder) but still the media folder is not updated with new content

**Comment by KosmosisDire** [comment]
Can you first delete everything that was ahead exported (especially the lib folder) and try again?

**Comment by hcgilje** [comment]
I did this now, but get the same result. 

The new html file is showing up, but it is missing the image.
<img width="715" alt="Skjermbilde 2024-06-05 kl  15 44 28" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/1252621/9e6506db-7c6f-4fc9-b597-b3042121cd91">

**Comment by KosmosisDire** [comment]
Hmmm, so, you could try the beta version. I have fixed a bunch of bugs like this in the betas. It's likely that you're not doing anything wrong and it's just a bug.

**Comment by hcgilje** [comment]
This is what it looks like in obsidian before export
<img width="946" alt="Skjermbilde 2024-06-05 kl  15 49 27" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/1252621/25dfd1c3-8118-46dc-a280-dbfbe49d3aad">

**Comment by hcgilje** [comment]
ok, will try to install the beta later today

**Comment by hcgilje** [comment]
I am happy to say that with the beta version it works as it should, the media content is included when exporting
