### ISSUE TITLE
SVGs linked as the src for an img do not export correctly

### ISSUE THREAD

**Issue by Giovy27072** [KosmosisDire/obsidian-webpage-export#45]
When i export my file the svg file are not showed, i think the problem is the tag `<img>` , for the svg the tag should be `<svg>`

**Comment by KosmosisDire** [comment]
This is very undeatiled. SVGs work fine for me so I will need more info about the issue to be able to reproduce it.

**Comment by Giovy27072** [comment]
> This is very undetailed. SVGs work fine for me so I will need more info about the issue to be able to reproduce it.

Link to video (uploaded on google drive) : https://drive.google.com/file/d/13XxTz9veuan5kAWzjba2OI3GKw_iTkRJ/view?usp=sharing

I recorded a video , in this video i show that when i try to convert my file in html using png and jpg images all works, but if i try to convert the same file using SVG images this images aren't showed.

**Comment by KosmosisDire** [comment]
Ah okay, this makes more sense. This should work but I will look into it and make a fix if I can. Thank you for the report!

**Comment by KosmosisDire** [comment]
In the mean time, a workaround may be to go into settings and disable inline images. This will export the svgs outside of the html file and I think that is likely to work. However, it will then not all be in one single file.

**Comment by Giovy27072** [comment]
> In the mean time, a workaround may be to go into settings and disable inline images. This will export the svgs outside of the html file and I think that is likely to work. However, it will then not all be in one single file.

Disabled inline images, it works!

**Comment by KosmosisDire** [comment]
Hello, this should be fixed in the latest update. Thanks for the report and let me know if you find any other problems! 😊
