### ISSUE TITLE
Support for Obsidian JS plugins that don't use CSS.

### ISSUE THREAD

**Issue by WinnerWind** [KosmosisDire/obsidian-webpage-export#461]
**Is your feature request related to a problem? Please describe.**
Hi there!
There are many plugins out there that don't use CSS to show their output. For example, [This colour cycler plugin](https://github.com/tjbrennan/obsidian-color-cycler) simply cycles the accent colour. It is not listed in the "add CSS for plugins" section of this plugin, because it changes the colour without any CSS work. This makes this plugin, and many others, simply impossible to run on the exported website. The plugin I mentioned can be configured to make a "disco" website, where the colours cycle every second. 

**Describe the solution you'd like**
Support for running JS plugins within the website. It probably won't be a one size fits all solution though, because obsidian plugins are vast.

**Additional context**
N/A

**Comment by KosmosisDire** [comment]
This is basically impossible unless the plugin in question never uses ANY obsidian API calls (which is basically no plugin). The plugin developer would need to specifically support some way to embed the same functionality into a browser based obsidian-independent environment.

**Comment by KosmosisDire** [comment]
It is possible some very small subset of plugins could be automatically converted somehow, but I think it is unlikely to be worth it and would probably be very buggy, messy, and extremely difficult.

**Comment by WinnerWind** [comment]
I see. I'll close this enhancement request then. I thought that the exporter just "emulated" an obsidian environment, allowing plugins like Kanban to work.

**Comment by KosmosisDire** [comment]
Kanban works because it outputs html which can be exported. So it is easy to make it work. Same with dataview. Thanks for the suggestions though :)
