### ISSUE TITLE
[Bug] [1.8.01]: Dataview LIST do not render correctly

### ISSUE THREAD

**Issue by tdaron** [KosmosisDire/obsidian-webpage-export#470]
### What happened?

```
```dataview
LIST date
WHERE date
```⠀
```

is not rendered correctly.

I can try to fix it myself, but i thought you might be faster than me if it's trivial to fix :)

### Reproduction

Simply create a vault with two files, one with a file containing 
```
```dataview
LIST date
WHERE date
```⠀
```

And the other containing

```


---
date: 2024-10-20
---
```

The export will show this: (missing a link to the list item)
<img width="157" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/34960023/af30a091-274f-410f-9cb3-7e5092712f38">
Instead of 
<img width="216" alt="image" src="https://github.com/KosmosisDire/obsidian-webpage-export/assets/34960023/debb1131-2b36-42b5-8442-3c7700988efe">

[sample-vault.zip](https://github.com/user-attachments/files/16119377/sample-vault.zip)

### Version

1.8.01

### Operating System

Linux (Endavour OS)

### Obsidian Version

Installer: 1.5.8 - Current: 1.6.5

### Which browsers can you reproduce this in?

Firefox

### Relevant log output

```yaml
Log:
[WARNING] 	Creating an RSS feed requires a site url to be set in the export settings.
[INFO] 	Closing render window


Settings:
	settingsVersion --------- 1.8.01
	makeOfflineCompatible     false
	inlineAssets ------------ false
	includePluginCSS          1 plugins included
	includeSvelteCSS -------- true
	titleProperty             title
	customHeadContentPath ---
	faviconPath              
	documentWidth ----------- 40em
	sidebarWidth              20em
	minOutlineCollapse ------ 2
	startOutlineCollapsed     false
	allowFoldingHeadings ---- true
	allowFoldingLists         true
	allowResizingSidebars --- true
	logLevel                  warning
	minifyHTML -------------- true
	makeNamesWebStyle         true
	onlyExportModified ------ true
	deleteOldFiles            true
	addThemeToggle ---------- true
	addOutline                true
	addFileNav -------------- true
	addSearchBar              true
	addGraphView ------------ true
	addTitle                  true
	addRSSFeed -------------- true
	siteURL                  
	authorName --------------
	vaultTitle                test
	exportPreset ------------ website
	openAfterExport           false
	graphAttractionForce ---- 1
	graphLinkLength           10
	graphRepulsionForce ----- 150
	graphCentralForce         3
	graphEdgePruning -------- 100
	graphMinNodeSize          3
	graphMaxNodeSize -------- 7
	showDefaultTreeIcons      false
	emojiStyle -------------- Native
	defaultFileIcon           lucide//file
	defaultFolderIcon ------- lucide//folder
	defaultMediaIcon          lucide//file-image
	exportPath -------------- /tmp/t
	filesToExport             0


Enabled Plugins:
	Webpage HTML Export
	Dataview
```

**Comment by KosmosisDire** [comment]
Thanks, this is very similar to some other issues that have already been reported, but I will try to reproduce it with the instructions you gave 

Thanks!

**Comment by KosmosisDire** [comment]
Hey, I just released a beta version that might fix this. If you could try it out and let me know if his issue is fixed and if you find any other issues. There are instructions for installing the beta in the readme :)
Thanks!

**Comment by tdaron** [comment]
Hello, sorry completely forgot to answer this :sweat_smile: 

It's working absolutely fine ! Thanks a lot :)
