### ISSUE TITLE
[Bug]: Graph view does not work in beta

### ISSUE THREAD

**Issue by Seudonym** [KosmosisDire/obsidian-webpage-export#481]
### What happened?

When selected from the file tree, everything works fine. But when any node is clicked in the graph view, it results in page not found. 
![image](https://github.com/user-attachments/assets/8b2d221d-f3c2-47fe-943a-3e38794bcf42)
To be clear, my vault has a `computers` folder, which has all of my notes. 

I do not know if this might be relevant but -
Using `1.8.01`, the web server export results in two folders - `lib`, and `computers` with the HTML. 

Using `1.8.1-2b`, the web server export results in a `lib` folder, and all the HTML on the same level (there is no `computers` folder).

### Reproduction

- Install plugin from BRAT
- Select files to export and save
- Export using the Online web server option

### Last Working Version

1.8.01

### Version

1.8.1-2b

### Operating System

Ubuntu 22.04

### Obsidian Version

1.6.7

### Which browsers can you reproduce this in?

Chrome

### Relevant log output

```yaml
Log:
[INFO] 	Including stylesheet: css-settings-manager
[INFO] 	Including stylesheet: ADMONITIONS_CUSTOM_STYLE_SHEET
[INFO] 	Including stylesheet: css-settings-manager
[INFO] 	Including stylesheet: ADMONITIONS_CUSTOM_STYLE_SHEET
[WARNING] 	Creating an RSS feed requires a site url to be set in the export settings.
[INFO] 	Closing render window
[INFO] 	Including stylesheet: css-settings-manager
[INFO] 	Including stylesheet: ADMONITIONS_CUSTOM_STYLE_SHEET
[WARNING] 	Creating an RSS feed requires a site url to be set in the export settings.
[INFO] 	Closing render window


Settings:
	settingsVersion --------- 1.8.1-2b
	makeOfflineCompatible     false
	inlineAssets ------------ false
	includePluginCSS          []
	includeSvelteCSS -------- true
	titleProperty             title
	customHeadContentPath ---
	faviconPath              
	documentWidth ----------- 40em
	sidebarWidth              20em
	minOutlineCollapse ------ 2
	startOutlineCollapsed     false
	relativeOutlineLinks ---- false
	allowFoldingHeadings      true
	allowFoldingLists ------- true
	allowResizingSidebars     true
	logLevel ---------------- warning
	minifyHTML                true
	makeNamesWebStyle ------- true
	onlyExportModified        true
	deleteOldFiles ---------- true
	addThemeToggle            true
	addOutline -------------- true
	addFileNav                true
	addSearchBar ------------ true
	addGraphView              true
	addTitle ---------------- true
	addRSSFeed                true
	siteURL -----------------
	authorName               
	vaultTitle -------------- obsidian-vault
	exportPreset              website
	openAfterExport --------- false
	graphAttractionForce      1
	graphLinkLength --------- 10
	graphRepulsionForce       150
	graphCentralForce ------- 3
	graphEdgePruning          100
	graphMinNodeSize -------- 3
	graphMaxNodeSize          7
	showDefaultTreeIcons ---- false
	emojiStyle                Native
	defaultFileIcon --------- lucide//file
	defaultFolderIcon         lucide//folder
	defaultMediaIcon -------- lucide//file-image
	exportPath                /home/wahid/Documents/blog
	filesToExport ----------- 18
	filePickerBlacklist       [
	filePickerWhitelist ----- [


Enabled Plugins:
	Admonition
	Advanced Tables
	Omnisearch
	Style Settings
	Editing Toolbar
	Execute Code
	BRAT
	Webpage HTML Export
```

### Additional Info

When files are accessed through the file tree:
![image](https://github.com/user-attachments/assets/eacc2a84-9075-4468-82e1-69334f9bf72b)

When files are accessed via graph:
![image](https://github.com/user-attachments/assets/aa585438-33cd-43fd-a2ba-e5d57d87fe5e)

**Comment by KosmosisDire** [comment]
Ahh, I must not have updated the graph view to grab the correct path. Because as you noticed it is cutting off excess parts of the path (so you don't have a bunch of nested folders with only other folders in them). It is very likely this is fixed already in my development branch which hasn't been released, but thanks for the report and I'll make sure it works properly in the next release :)

**Comment by Seudonym** [comment]
Could you please include the option to allow nested folders if that is possible? That would be pretty useful as my vault has a lot of folders and I'd like to keep it that way. Thanks!

**Comment by KosmosisDire** [comment]
> Could you please include the option to allow nested folders if that is possible? That would be pretty useful as my vault has a lot of folders and I'd like to keep it that way. Thanks!

I think you may misunderstand what I mean. It doesn't remove all the folders. It only removes folders which are not selected for export and are redundant. It still keeps folders as expected. You see that the folders are still there when you look at the file picker :)

**Comment by KosmosisDire** [comment]
Hey, I just released a beta version that should address this. If you could try it out and let me know if his issue is fixed and if you find any other issues. There are instructions for installing the beta in the readme :)
Thanks!
