### ISSUE TITLE
When exporting canvas, hover preview of linked note not supported

### ISSUE THREAD

**Issue by simenkva** [KosmosisDire/obsidian-webpage-export#482]
In the Obsidian app canvas view, if a card has a link to a note, hovering over the link will present a tooltip preview of the note. This is very useful, but is not exported with the plugin in its current version.

I would like to have the same functionality in the HTML export plugin.

https://github.com/user-attachments/assets/e1806260-b38b-4070-b391-5381f7dffcc9

**Comment by KosmosisDire** [comment]
This is actually the case with any link to a markdown note anywhere in obsidian, and there is already an issue tracking this feature request. I do plan to implement this feature soon though, so keep an eye out :)

Since this is a duplicate I will go ahead and close it

**Comment by simenkva** [comment]
Thanks!
