### ISSUE TITLE
Add an index.html to export

### ISSUE THREAD

**Issue by samolukadjo** [KosmosisDire/obsidian-webpage-export#484]
**Is your feature request related to a problem? Please describe.**
When a link to the site my Vault is hosted on is visited, on it's own, a 404 error is returned.

**Describe the solution you'd like**
I propose making it so that if there is a note in the Vault root called "index" have it's title be hidden or customised some other way in the exported file when the web server export option is used. This would allow the user to customise the contents of their Vaults "homepage".

**Describe alternatives you've considered**
Have the plugin decide what should be in the index.html automatically with potential customisation in settings, hopefully offering easy access to the rest of the notes.

**Additional context**
N/A

**Comment by KosmosisDire** [comment]
Just create a file called index. It will become index.html in your export

The title property can be added to a file to change its display name if you want it to look like it's named something other than index :)

I do want to make this a bit easier in the future haha

**Comment by samolukadjo** [comment]
Thanks 👍

**Comment by KosmosisDire** [comment]
I'll go ahead and close this

**Comment by KillyMXI** [comment]
I'm facing this as I'm publishing a demo vault to GitHub.

GitHub convention: `README.md` is the entry point.
Web convention, including GitHub Pages: `index.html` is the entry point.

To keep the demo vault as simple as possible, I can't have separate Readme and index.

Working around this by adding `index.html` with following content:

```html
<!DOCTYPE HTML>
<html lang="en-US">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="0; url=readme.html">
    <script type="text/javascript">
      window.location.replace("readme.html")
    </script>
    <title>Page Redirection</title>
  </head>
  <body>
    If you are not redirected automatically, follow <a href='readme.html'>this link</a>.
  </body>
</html>
```
