### ISSUE TITLE
[Bug]: Collapse buttons appear blank until clicked

### ISSUE THREAD

**Issue by Seudonym** [KosmosisDire/obsidian-webpage-export#485]
### What happened?

The collapse buttons for the file tree and file outline (left and right panels) appear blank until they are clicked. Even after they are clicked, they are way too big than expected.

Before clicking (on site load)
![image](https://github.com/user-attachments/assets/ca93bc50-1aa7-4883-b9d8-c13295409a96)

After clicking
![image](https://github.com/user-attachments/assets/52f6d07f-38b3-41b2-a00a-3bcfd33a9e29)

The show/hide panel buttons also have a larger stroke width than expected.
![image](https://github.com/user-attachments/assets/d0713920-91eb-4b2a-a626-987aa51da314)

### Reproduction

1. Download the plugin from Obsidian.
2. Download the pink topaz theme and export as webserver.

### Version

1.8.01

### Operating System

Ubuntu

### Obsidian Version

1.6.7

### Relevant log output

```yaml
N/A
```

**Comment by KosmosisDire** [comment]
Thanks, I am working on fixing this :)

**Comment by KosmosisDire** [comment]
Hey, I just released a beta version that should address this. If you could try it out and let me know if his issue is fixed and if you find any other issues. There are instructions for installing the beta in the readme :)
Thanks!
