### ISSUE TITLE
[Bug]: Canvas export is broken in 1.9.0-2b

### ISSUE THREAD

**Issue by simenkva** [KosmosisDire/obsidian-webpage-export#491]
### What happened?

Exporting a fresh vault using newest beta version, with a very simple canvas. Beta plugin 1.9.0-2b. Canvas shows up in html, but does not respond to interaction. Also no file explorer in the export.

### Reproduction

Just export any obsidian vault with canvases.

### Last Working Version

1.8.1-2b

### Version

1.9.0-2b

### Operating System

MacOS

### Obsidian Version

Version 1.6.7 (Installer 1.4.13)

### Which browsers can you reproduce this in?

Firefox, Safari, Safari IOS

### Relevant log output

```yaml
Log:


Settings:
	settingsVersion --------- 1.9.0-2b
	makeOfflineCompatible     false
	inlineAssets ------------ false
	includePluginCSS          []
	includeSvelteCSS -------- true
	titleProperty             title
	customHeadContentPath ---
	faviconPath              
	documentWidth ----------- 40em
	sidebarWidth              20em
	minOutlineCollapse ------ 2
	startOutlineCollapsed     false
	relativeOutlineLinks ---- false
	allowFoldingHeadings      true
	allowFoldingLists ------- true
	allowResizingSidebars     true
	logLevel ---------------- warning
	minifyHTML                true
	makeNamesWebStyle ------- true
	onlyExportModified        true
	deleteOldFiles ---------- true
	addThemeToggle            true
	addOutline -------------- true
	addFileNav                true
	addSearchBar ------------ true
	addGraphView              true
	addTitle ---------------- true
	addRSSFeed                true
	siteURL -----------------
	authorName               
	vaultTitle -------------- asdfsdf
	exportPreset              website
	openAfterExport --------- false
	graphAttractionForce      1
	graphLinkLength --------- 10
	graphRepulsionForce       150
	graphCentralForce ------- 3
	graphEdgePruning          100
	graphMinNodeSize -------- 3
	graphMaxNodeSize          7
	showDefaultTreeIcons ---- false
	emojiStyle                Native
	defaultFileIcon --------- lucide//file
	defaultFolderIcon         lucide//folder
	defaultMediaIcon -------- lucide//file-image
	exportPath                /Users/simenkva/Code/html-export
	filesToExport ----------- 0
	filePickerBlacklist       [
	filePickerWhitelist ----- [


Enabled Plugins:
	BRAT
	Webpage HTML Export
```

**Comment by KosmosisDire** [comment]
This is very strange, I am not able to reproduce. How are you opening the export? Is it being hosted on a web server?

**Comment by simenkva** [comment]
This is very strange. I now tried again, and now it works! The reason why I reported this, is that BRAT had suddenly updated the plugin from the previous beta, and now website export was definitely broken on my main vault. I tried in a new vault, and it *still* did not work. That is why I reported it. I must have slipped and hit my head. But now it works again, *also* on my main vault that I export. You can view it here, https://simenkva.github.io/esqc_material/index.html . The plugin is getting better and better, I believe.

I apologize for confusion. I still believe there is *something* wrong with cached files, left-over settings, something ... I tried many times, spent a lot of time before I made it work by reverting to the previous beta.

**Comment by KosmosisDire** [comment]
I don't understand why it wouldn't work in the new vault. But as far as your main vault goes it is possible it was caused by trying to  export the website on top of the old export. Like you said, left over settings. My suggestion is to completely uninstall and reinstall the plugin after every major update, because migrating settings properly between versions is extremely hard. Right now I think it _should_ reset most of the settings after every update though. So I am not sure.

I am glad it is working now though! As a side note it looks like your main vault is still using the old version of the plugin. I am always happy to see what people are doing with the plugin :) Let me know if you update the main site to the new version I'd like to see how it is working.

Thanks!
