### ISSUE TITLE
[Bug] [1.9.0-2b]: 1.9.0-2b / Cannot drag inside the canvas

### ISSUE THREAD

**Issue by Nydid** [KosmosisDire/obsidian-webpage-export#501]
### What happened?

I am currently having this issue, where on version 1.9.2-2b, the canvas cannot be "grabbed" and moved, but you can double-click on a note to zoom in on it.

On 1.9.0-2b:
![floorp_laQSzNzJWZ](https://github.com/user-attachments/assets/8ea86293-4c44-4038-adb8-54a2bd8bc5b1)

#491

### Reproduction

1. Create a new vault
2. Install BRAT
3. Install 1.9.0-1b or 1.9.0-2b
4. Create a canvas with a note
5. Export canvas as Local Website
6. Cannot move not on canvas, cannot zoom

### Last Working Version

1.8.01

### Version

1.9.0-2b

### Operating System

Windows 11

### Obsidian Version

1.6.7

### Which browsers can you reproduce this in?

Firefox

### Relevant log output

```yaml
Cannot export log output due to console error when pressing the Debug Copy button
```

### Additional Info

![image](https://github.com/user-attachments/assets/0a99e260-e607-4105-95fd-025f33388a65)

**Comment by KosmosisDire** [comment]
This is very strange, are you using Firefox on all 3 devices? If you use chrome or edge on the non-functional device does it work?

**Comment by KosmosisDire** [comment]
Oh did you edit your answer to include the things I just asked or am I blind? Lmao

I will take a look at specifically reproducing it in Firefox. I do most of my testing in chrome. I did test this in Firefox, but it's good to know where I should look to reproduce

**Comment by KosmosisDire** [comment]
So to clarify, Firefox desktop on any device doesn't work? Not just on the one device?

**Comment by KosmosisDire** [comment]
I was able to reproduce and fix this, it has to do with touch screens. If your device has a touch screen it will work. The fix will be out in the next release
