### ISSUE TITLE
Allow CSS to add content on the side of the markdown-sizer

### ISSUE THREAD

**Issue by Nydid** [KosmosisDire/obsidian-webpage-export#502]
**Is your feature request related to a problem? Please describe.**
I've been trying to make a Wikipedia like page and tried using [Wikipedia Infoboxes](https://publish.obsidian.md/slrvb-docs/ITS+Theme/Callouts/Callout+-+Infoboxes).

They render fine in Obsidian but upon export, the CSSed Callout gets pushed in by what seems to be a markdown-sizer in the exporter.

Obsidian:
![image](https://github.com/user-attachments/assets/53e75ecc-537c-40c6-a5d0-7320b9c95cae)

HTML:
![image](https://github.com/user-attachments/assets/e49d45da-bf01-450c-bdfd-940e9e5dbec7)

**Describe the solution you'd like**
A way to bypass the resizer so we can add information outside the default resizer

**Describe alternatives you've considered**
Looking into bypassing the resizer using the "Feature Placement" included in the settings.
Somehow bypassing sizerElement from webpage.ts

**Additional context**

**Comment by KosmosisDire** [comment]
This kind of css very much relies on assumptions about the html and css of obsidian. I try to mimic that as closely as possible but it's impossible to get it perfect. If you can send me a small reproduction vault (or instructions to create this exact setup) I will take a look and see if there is an easy tweak to the css I can make that will allow this to work.

**Comment by KosmosisDire** [comment]
You can change the line width in the plugin settings (although not in the beta since I am still finishing the new settings page)
