### ISSUE TITLE
Option to make external  link open with target self

### ISSUE THREAD

**Issue by ZeroKun265** [KosmosisDire/obsidian-webpage-export#513]
**Is your feature request related to a problem? Please describe.**
I'd like a way to make it so when clicking on any external link, instead of opening a new tab, it will open in the current tab

**Describe the solution you'd like**
A toggle in the settings would be nice, which would then make all links have terget="_self" instead of target="_blank" like they do now

**Describe alternatives you've considered**
I tried loading custom scripts at the top of the body, i must say i'm not a js expert but while i could make it run on first load, the moment the content changed the links were back to having target="_blank".
A polling method could be used, but would be very inefficient

**Additional context**
None

**Comment by KosmosisDire** [comment]
Hello! In the beta versions your custom script should be easier to implement as there is a frontend API you can use to modify documents using a function that is run on all document's HTML. However since it is a beta it is probably missing some features you are using. Either way this will be easier when the next stable release comes out

**Comment by KosmosisDire** [comment]
Actually I noticed you might be using the beta version. 
`ObsidianSite.onDocumentLoad((d) => d.documentEl.querySelectorAll("a").forEach(a => a.target = "_blank"));`

This custom script should work I think. Let me know if it does work

**Comment by ZeroKun265** [comment]
I was not using the beta, but I have it installed in a demo vault, it's worth a shot
If anything I can just wait for the beta to become a release, I'll update this once I can try out a few things

**Comment by ZeroKun265** [comment]
Sorry i never got back at you.. it seems that the beta opens links in the same tab even without the added code..
I'll stick to the stable release for now, and since once the beta is done this should be a feature (either with the added code or by default) i guess i can mark this as closed
