### ISSUE TITLE
[Bug] [1.8.01]: Indents in Lists

### ISSUE THREAD

**Issue by arefdehooei** [KosmosisDire/obsidian-webpage-export#515]
### What happened?

Obsidian
<img width="178" alt="Screenshot 1403-06-31 at 10 40 43" src="https://github.com/user-attachments/assets/fe9116c0-f096-4992-b168-346ba575f34c">
export
<img width="206" alt="Screenshot 1403-06-31 at 10 37 24" src="https://github.com/user-attachments/assets/cbc3615a-9c69-44ce-bccf-045bc5a929f2">

### Reproduction

Just try to export

### Version

1.8.01

### Operating System

macOS 15.0

### Obsidian Version

1.6.7

### Which browsers can you reproduce this in?

Chrome, Microsoft Edge

### Relevant log output

```yaml
N/A
```

**Comment by KosmosisDire** [comment]
Hi, this is fixed in the beta version
