### ISSUE TITLE
UTF-16 encoding may be causing pages to not render sometimes

### ISSUE THREAD

**Issue by dgudim** [KosmosisDire/obsidian-webpage-export#52]
I tried opening exported pages in github pages, but they didn't render.
After some investigation i found out that the exported files are saved in UTF-16BE

![image](https://user-images.githubusercontent.com/34401005/226121116-b5986319-6112-43b1-b137-22bdeb386382.png)

I converted them to UTF-8 and now everything works.
Is there a reason to save in UTF-16?

**Comment by KosmosisDire** [comment]
I have not intentionally set UTF-16 as the encoding. I can try changing the encoding to UTF-8 though. This doen't seem to be a problem most of the time so not sure why it is possing up on github pages specifically. Thanks for the report

**Comment by dgudim** [comment]
I have tested it further
| | |
|-|-|
|Utf16BE          | renders fine locally, renders as text on gh pages|
|Utf16BE with BOM | same as Utf16BE but with with 2 question mark symbols at the beginning|
|Utf16LE          | does not render anywhere|
|Utf16LE with BOM | renders as text locally, question marks on gh pages|
|Utf8| renders fine everywhere |

Seems like gh pages don't like utf16 very much

**Comment by KosmosisDire** [comment]
Huh interesting. I am not sure if there is any benefit to using UTF-16 but as far as I know it is not needed so I will go ahead and change it. Thanks for taking the time to test that and giving a clear report, I appreciate it a lot!

**Comment by KosmosisDire** [comment]
This should be fixed in the latest update! Thanks for the report and let me know if you find any other problems. :)
