### ISSUE TITLE
[Bug] [1.8.01]: Please do not handle image files as text file

### ISSUE THREAD

**Issue by dsgler** [KosmosisDire/obsidian-webpage-export#524]
### What happened?

My article includes some images in the same dir, and export them at the sametime.
It turn out that the image was opened as text and was then saved, making it unable to be open as image.
I hope it can copy the image straightly, without handling it. 

### Reproduction

-

### Version

1.8.01

### Operating System

windows

### Obsidian Version

-

### Relevant log output

```yaml
-
```

**Comment by dsgler** [comment]
Well, after reading the source code, I find the code has made a judgment about whether the variable's type is Buffer or string, but it doesn't work as it's supposed to be, and I don't know why.
So, I make minor changes to the code `utils/downloadable.ts` the function `async download(downloadDirectory) ` , use `this.isConvertable` to judge the way to copy it.
It now loos like this, and it works on my computer:
```js
  async download(downloadDirectory) {
    if (!this.isConvertable){
      let writePath = this.getAbsoluteDownloadDirectory(downloadDirectory).joinString(this.filename);
      let data=this.content;
      await writePath.writeFile(data);
    }else{
      let writePath = this.getAbsoluteDownloadDirectory(downloadDirectory).joinString(this.filename);
      let data = Buffer.from(this.content.toString(), this.encoding);
      await writePath.writeFile(data, this.encoding);
    }
  }
  ```

**Comment by KosmosisDire** [comment]
Hi please try the beta version, I am almost certain this will work there :)

**Comment by dsgler** [comment]
> Hi please try the beta version, I am almost certain this will work there :)

Thanks, it works.
But it would delete the older files.
Could you give a option not to delete the old file , or check the old file automatically , so that I don't need to check them every time I update my notes.

**Comment by KosmosisDire** [comment]
Just click the save button after selecting your files to save the selection :) haha

**Comment by KosmosisDire** [comment]
You have to select all the files you want in your site, not only the new ones. Then click save. When you export it will only export updated or new files and not old ones

**Comment by dsgler** [comment]
> You have to select all the files you want in your site, not only the new ones. Then click save. When you export it will only export updated or new files and not old ones

Thank you for the reminder, I just sometimes feel lazy to select again.

**Comment by KosmosisDire** [comment]
> > You have to select all the files you want in your site, not only the new ones. Then click save. When you export it will only export updated or new files and not old ones
> 
> Thank you for the reminder, I just sometimes feel lazy to select again.

You never have to reselect everything, it should keep your selection so you don't have to re-check all the checkboxes every time.
