### ISSUE TITLE
Add some navigation (scrolling) to exported canvas.

### ISSUE THREAD

**Issue by vyhyb** [KosmosisDire/obsidian-webpage-export#54]
Thanks for this great plugin. Adding a possibility to export larger canvas with some navigation would be great.

**Comment by KosmosisDire** [comment]
Hey thanks, this is planned but it will probably be a while. There are a lot of hurdles to overcome with exporting canvases, and I hope to address them all eventually.

**Comment by KosmosisDire** [comment]
As of v1.6.0 canvas exports have been disabled until they can be exported cleanly so I am closing this for now.
