### ISSUE TITLE
[Bug] [1.8.01]: Checkbox disappear when inline math is used

### ISSUE THREAD

**Issue by Kuhjuice** [KosmosisDire/obsidian-webpage-export#546]
### What happened?

Checkboxes will not show up, when inline math is used in the text after a checkbox.

### Reproduction

#Use a list with checkboxes and in one of them write 
"Just test"
and in the other
"Text with $\frac{inline}{math}$"
maybe one more with
"Text Again"

### Version

1.8.01

### Operating System

MacOS

### Obsidian Version

1.7.7 (Installer 1.4.16)

### Relevant log output

```yaml
Log:
CANT BE DISCLOSED
[INFO] 	Closing render window


Settings:
	settingsVersion --------- 1.8.01
	makeOfflineCompatible     true
	inlineAssets ------------ true
	includePluginCSS          3 plugins included
	includeSvelteCSS -------- false
	titleProperty             title
	customHeadContentPath ---
	faviconPath              
	documentWidth ----------- 40em
	sidebarWidth              20em
	minOutlineCollapse ------ 2
	startOutlineCollapsed     false
	allowFoldingHeadings ---- true
	allowFoldingLists         true
	allowResizingSidebars --- true
	logLevel                  warning
	minifyHTML -------------- true
	makeNamesWebStyle         false
	onlyExportModified ------ false
	deleteOldFiles            true
	addThemeToggle ---------- true
	addOutline                true
	addFileNav -------------- true
	addSearchBar              false
	addGraphView ------------ false
	addTitle                  true
	addRSSFeed -------------- true
	siteURL                  
	authorName --------------
	vaultTitle                XXXXXXX
	exportPreset ------------ documents
	openAfterExport           false
	graphAttractionForce ---- 1
	graphLinkLength           10
	graphRepulsionForce ----- 150
	graphCentralForce         3
	graphEdgePruning -------- 100
	graphMinNodeSize          3
	graphMaxNodeSize -------- 7
	showDefaultTreeIcons      true
	emojiStyle -------------- Native
	defaultFileIcon           lucide//file
	defaultFolderIcon ------- lucide//folder
	defaultMediaIcon          lucide//file-image
	exportPath -------------- /Users/anon/Documents/XXXXXX
	filesToExport             1


Enabled Plugins:
	Advanced Tables
	Better Export PDF
	Iconize
	Advanced Canvas
	Numerals
	Badges
	Live Variables
	Webpage HTML Export
```

### Additional Info

The fault is due to this line:
 margin-inline-start: calc(var(--checkbox-size) * -1.5);

--checkbox-size is defined like this (Order resambles order of the css.

112:
  --checkbox-size:var(--font-text-size);
856:
  --font-text-size:16px;
2968:
ul>li.task-list-item .task-list-item-checkbox {
  margin-inline-start:calc(var(--checkbox-size) * -1.5)
}

There seems to be an overflow issue.

**Comment by KosmosisDire** [comment]
Hi, I believe this has been reported before I don't remember where but I know I fixed it at some point. It is either fixed in the current beta or it will be fixed in the next release. Test the beta and let me know if it is working there

**Comment by Kuhjuice** [comment]
> Hi, I believe this has been reported before I don't remember where but I know I fixed it at some point. It is either fixed in the current beta or it will be fixed in the next release. Test the beta and let me know if it is working there

Okay! Thats amazing to hear.
How did you fix it? (Maybe the pull request is enough)

Thank you!
