### ISSUE TITLE
Error: Path does not exist - (css theme file)

### ISSUE THREAD

**Issue by Oskiator** [KosmosisDire/obsidian-webpage-export#58]
Hi,

**Describe the bug**
When exporting, I see this error and the css of my theme is not taken into account. 
![image](https://user-images.githubusercontent.com/96892939/230791976-15fe12ec-bcaa-4046-8c1a-9d7047c4a7e9.png)
![image](https://user-images.githubusercontent.com/96892939/230792050-60a21c6f-8848-418b-a778-6d4479448e00.png)

The bug happens because the plugin looks for the path 
"D:/Michaël/Documents/Perso/VDLV/zsku6-exgno/Leader du changement/.obsidian/themes/Monokai_adapted/theme.css" 
instead of 
"D:/Michaël/Documents/Perso/VDLV/zsku6-exgno/Leader du changement/.obsidian/themes/Monokai_adapted.css"

**Operating System**
Windows 10

**To Reproduce**
1. Simply export any file in HTML

**Workaround**
Copy the css file according to the path checked by the plugin.
In my case, creating the folder Monokai_adapted and rename the css file by "theme.css"

### IMPORTANT: Error Log
Path does not exist: D:/Michaël/Documents/Perso/VDLV/zsku6-exgno/Leader du changement/.obsidian/themes/Monokai_adapted/theme.css
pathExists @ plugin:webpage-html-export:6144
getAbsolutePath @ plugin:webpage-html-export:6203
getThemeContent @ plugin:webpage-html-export:6365
generateHead @ plugin:webpage-html-export:6982
await in generateHead (async)
getCurrentFileHTML @ plugin:webpage-html-export:6864

🙏 Many thanks for your work !

**Comment by KosmosisDire** [comment]
All officially supported themes as far as I know are located inside a folder with the themes name when you download them so the only reason this might not work is if you manually placed that file there. I don't think the API gives a way to get the path to the current theme for any arbitrary theme, however I will look into improving how this is handled. Thanks for the report!

**Comment by Oskiator** [comment]
Thank you. It was a them I've downloaded on the forum and adapted one year ago. I imagined what you said so I tried to make a folder with the name of the theme and change the name of the css file by theme.css but it didn't appear in the list of themes in obsidian. Maybe there is something I don't know about how the themes work.  
At least the workaround is simple so it's really not a urgent thing.
