### ISSUE TITLE
Code copy button does not work on export

### ISSUE THREAD

**Issue by JasonAizkalns-Zoetis** [KosmosisDire/obsidian-webpage-export#6]
I cannot get the `copy` button to work for code snippets. I have tried both inline and not inline options.

**Comment by KosmosisDire** [comment]
Can you clarify what you mean? What do you mean it doesn't work for code snippets?

**Comment by JasonAizkalns-Zoetis** [comment]
Of course. Here's a simple note in edit mode:

![image](https://user-images.githubusercontent.com/99889394/208523408-bd20c0ae-2f74-4f1b-b318-6ca29bb4590e.png)

Clicking the `JavaScript` badge allows you to copy/paste the code snippet elsewhere. In preview mode, this changes to ` Copy` button.

![image](https://user-images.githubusercontent.com/99889394/208523523-b83f5a8f-a853-45d3-9f32-3fe592e25af2.png)

Likewise, it says `Copy` when exported via this plugin:

![image](https://user-images.githubusercontent.com/99889394/208523697-ab819fb9-62ca-4a17-9d5a-a9f4b6c1bc0f.png)

...but it does not work as expected.

**Comment by KosmosisDire** [comment]
Ah, you mean that it does not actually copy the snippet? That is a good point and I will add this in the future. Thanks for reporting that

**Comment by KosmosisDire** [comment]
This has been added in release 1.3.1
