### ISSUE TITLE
Add support for opening vaults on a UNC network path

### ISSUE THREAD

**Issue by bernardb2010** [KosmosisDire/obsidian-webpage-export#60]
**Describe the bug**
Plugin not loading for vault stored on network drive. When clicking enable, error message pops up:
Error: Path does not exist:
//path/to/vault/Obsidian_notebook/Notes/path/to/vault/Obsidian_notebook/Notes/.obsidian/plugins/

Failed to load plugin webpage-html-export

It seems like the path to the vault is being (including subfolder for notes) is being listed twice before looking for a plugins folder.

**Operating System**
Windows 10

**To Reproduce**
1. Open Obsidian Vault on network location
2. Settings
3. Community plugins
4. Click switch to enable Webpage HTML Export

### IMPORTANT: Error Log
plugin:webpage-html-export:6144 Path does not exist: //path/to/vault/Obsidian_notebook/Notes/path/to/vault/Obsidian_notebook/Notes/.obsidian/plugins/
pathExists @ plugin:webpage-html-export:6144

Plugin failure: webpage-html-export TypeError: The "path" argument must be of type string. Received undefined
    at __node_internal_captureLargerStackTrace (node:internal/errors:465:5)
    at new NodeError (node:internal/errors:372:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:429:7)
    at Object.eval [as join] (plugin:webpage-html-export:82:38)
    at Utils.joinPaths (plugin:webpage-html-export:6137:53)
    at new HTMLGenerator (plugin:webpage-html-export:6695:55)
    at new HTMLExportPlugin (plugin:webpage-html-export:7230:26)
    at e.<anonymous> (app.js:1:1072160)
    at app.js:1:235836
    at Object.next (app.js:1:235941)
    at a (app.js:1:234680)

**Comment by KosmosisDire** [comment]
Huh, interesting how have you mounted the network drive? Is it mounted through file explorer or do you have a 3rd party app that is mounting it for you? This seems like a pretty simple bug when generating a path, so hopefully I can reproduce and fix this. Thanks for the report!

**Comment by bernardb2010** [comment]
Interesting...

I believe it's not currently mounted, it's just a path to the network drive.

I can try mounting the drive and see if that works in the morning.

**Comment by KosmosisDire** [comment]
Well if the drive is not mounted then that is definetly a problem, but I am not sure if that is what you mean. Because if the drive was not mounted you couldn't access anything on it at all.

**Comment by bernardb2010** [comment]
Another point of data:

Opening the vault using the UNC path \\path\to\vault does not work.

Using a mapped drive in Windows to the same location: Y:\path\to\vault allows the plugin to open as expected. Given this piece of information, probably not a bug, more likely an enhancement to be able to use UNC path (if it is something you want to do), or maybe just a note on the information page.

Thanks for the help!

**Comment by KosmosisDire** [comment]
Ah okay that makes more sense, adding this isn't high on my list but I will certainly keep it open for the future. Thanks for the report and info! :)

**Comment by bernardb2010** [comment]
Looks like this was fixed in 1.6.0!

**Comment by KosmosisDire** [comment]
Oh nice! It wasn't intentional but I guess my refactor of the path system must have fixed this. Thanks for letting me know, and for reporting the issue :)
