### ISSUE TITLE
Audio support.

### ISSUE THREAD

**Issue by thehirou** [KosmosisDire/obsidian-webpage-export#62]
I'm not sure if this could be considered an error because in the html file you can see that the audio is there but it's linked to a local path, obviously inaccessible from a website (Actually, not even accessible locally). Any plans on taking the audio attachments from the projects and add them to the files when exporting or am I asking for something impossible?

Thanks.
![Untitled-5](https://user-images.githubusercontent.com/82706798/232322615-3e74b165-0e68-4c65-991e-37f2c21fd38c.png)

**Comment by KosmosisDire** [comment]
Hey! Thanks for the suggestion and this is already implemented and will come in the next update! So stay tuned for the next release :)

**Comment by KosmosisDire** [comment]
Hey, this should be added in the latest update. Thanks for the suggestion and let me know if you have any other ideas! 😊
