### ISSUE TITLE
Plugin crash with 100+ images

### ISSUE THREAD

**Issue by ironhak** [KosmosisDire/obsidian-webpage-export#63]
**Describe the bug**
This is a clear and concise description of what the bug is.
When trying to export a note that contains more than ~100/200 images the plugin will crash:
<img width="1798" alt="image" src="https://user-images.githubusercontent.com/62611612/233774525-48739cfc-0fc9-42f0-adad-ba6eb8df75b5.png">

**Comment by KosmosisDire** [comment]
Thanks for the report, does this occur if they are all the same image or do they have to be unique?

**Comment by ironhak** [comment]
> Thanks for the report, does this occur if they are all the same image or do they have to be unique?

Hello. I did not tried with a single image repeated many times, my issue come from a note containing 200+ different unique images. 

Let me know if I can give any help in replicating the bug. 

Have a nice one.

**Comment by ironhak** [comment]
Hello, with the new version it works perfectly. Awesome job, awesome plugin. Keep up the good work.
