### ISSUE TITLE
Incompatibility with Border theme

### ISSUE THREAD

**Issue by Aeases** [KosmosisDire/obsidian-webpage-export#65]
**Describe the bug**
When Exporting from a note using the '[Border](https://github.com/Akifyss/obsidian-border)' or 'Maple' themes (possibly others, **I tested on Border but have had the issue with maple before**),
the export does not work and instead the following shows up; 
![image](https://user-images.githubusercontent.com/96164686/235282943-dd6891b2-ab78-42cc-b5ac-da8c51c96b7d.png)

**Operating System**
Windows 11 - 22621.1555
Windows 10 - Unknown

**To Reproduce**
1. Enable the **border** or **maple** theme
2. Export a note
3. See the exported note does not render and instead looks like the image above.

**Screenshots**
Examples of anote pre and post export in a sandbox vault.
<details>
<summary>
Note pre-export 
</summary>

![image](https://user-images.githubusercontent.com/96164686/234540333-d3d05fed-7dd2-4612-bb13-8bb2a6bf507f.png)
</details>

<details>
<summary>
Note post-export 
</summary>

![image](https://user-images.githubusercontent.com/96164686/234540803-ae4eb02d-4aed-47b2-a947-a0b0e434b631.png)
</details>

### IMPORTANT: Error Log
The console of both obsidian and the exported webpage show nothing of note. however resizing the view of the webpage by expanding the Dev Console I did notice more text on the webpage

![image](https://user-images.githubusercontent.com/96164686/235283173-154a8661-8408-4917-9b2f-8eab3f7c1374.png)

**Comment by KosmosisDire** [comment]
Hello, thanks for the report. I am not sure what is wrong but I have just tested with the release that I am about to put out and the border theme works. It is a pretty big update and should come out in an hour or two. I'll update you here once I have released it, and let me know if it works after the update. Thanks!

**Comment by KosmosisDire** [comment]
Okay, I was actually able to recreate this issue. If you go into the main settings and turn off `Inline CSS` then it should work with these themes. I will look into what is causing them to break when inlined. Thanks again for reporting this!

**Comment by KosmosisDire** [comment]
Update on this: I think this is a problem with the theme itself and the way they embed svgs so I am not sure there is anything I can do about it other than tell you to export as Multi-file instead of as self-contained documents.

**Comment by Manukineko** [comment]
Ping-pong time ? XD
I got the same issue.
https://github.com/Akifyss/obsidian-border/issues/66#issuecomment-1523446108

**Comment by KosmosisDire** [comment]
This may be fixed in the latest beta by using a css parser to fix any syntax errors in themes, if it is not then again there's unfortunately nothing I can really do to support these themes.
