### ISSUE TITLE
Graph View: Show file names even on nodes that aren't hovered

### ISSUE THREAD

**Issue by KosmosisDire** [KosmosisDire/obsidian-webpage-export#68]

**Comment by 1143221614** [comment]
Is this feature complete?

**Comment by KosmosisDire** [comment]
No, not yet. There are a lot of features to work on and I just started a full time job, so it will probably be a while.

**Comment by KosmosisDire** [comment]
This should be implemented in v1.7.1!

**Comment by 1143221614** [comment]
Yes! Thank you for your development!
