### ISSUE TITLE
Hitting cancel on `Export Vault to HTML` still runs the script

### ISSUE THREAD

**Issue by JasonAizkalns-Zoetis** [KosmosisDire/obsidian-webpage-export#7]
If I click the `Export Vault to HTML`  in the ribbon, I receive a modal popup / dialogue (as expected). 

However, it appears you cannot "cancel" this action:

1. Clicking on the "X" still sends you through to the "Choose the folder dialogue"
2. Hitting cancel on the "Choose the folder (modal) dialogue" still fires the script. 

From what I can tell, the script still runs (opens a tab for every note in the vault), but does not write the files anywhere.

Windows machine.

![Example of Error](https://user-images.githubusercontent.com/99889394/208525919-1d212e19-dfbb-47fb-b565-4abfa62301ee.gif)

**Comment by KosmosisDire** [comment]
Thank you for this as well! This should probably be an easy fix if I can reproduce it

**Comment by KosmosisDire** [comment]
The files that don't seem to be exported anywhere here are actually being exported at "C:\Users\{username}\AppData\Local\Obsidian\null\" on Windows. Or the equivalent Obsidian working directory on Linux or Mac (not familiar with what that path would be).

**Comment by JasonAizkalns-Zoetis** [comment]
> The files that don't seem to be exported anywhere here are actually being exported at "C:/Users/{username}/AppData/Local/Obsidian/null/" on Windows. Or the equivalent Obsidian working directory on Linux or Mac (not familiar with what that path would be).

Correct. Confirmed. Either way, I believe both the "X" on the context menu and "cancel" on the modal pop-up should do a proper exit.

**Comment by KosmosisDire** [comment]
Yes of course, I have actually already fixed it, but I'm going to fix a few other things before I create a new release.

**Comment by KosmosisDire** [comment]
This should be fixed in release 1.3.1
