### ISSUE TITLE
Incompatibility with Banners Plugin

### ISSUE THREAD

**Issue by Aeases** [KosmosisDire/obsidian-webpage-export#74]
**Describe the bug**
If a note has a banner from the [Obsidian Banners](https://github.com/noatpad/obsidian-banners) plugin then the note does not render, even if banners is disabled in the "Include Plugin CSS" section with Inline CSS disabled.

**Operating System**
Windows 11

**To Reproduce**
1. Install Banners Plugin
2. Add a banner to a note
3. attempt to export the note with a banner
4. See the exported note which says "Failed to render file, check obsidian log for details and report an issue on GitHub: [Github Issues](https://github.com/KosmosisDire/obsidian-webpage-export/issues)"

**Screenshots**
![image](https://user-images.githubusercontent.com/96164686/235342654-c09259f6-a610-4fdd-bc27-db1cac8c8679.png)

### IMPORTANT: Error Log
![image](https://user-images.githubusercontent.com/96164686/235342676-c0635f10-dd61-4b1a-b601-1a216f51d838.png)

**Comment by KosmosisDire** [comment]
Thanks for the report, it seems a number of issues are being caused that throw this same error so it is probably one underlying problem. I'll start work on this.

**Comment by KosmosisDire** [comment]
Can you check if this works when you turn of the background exporter in the settings? Thanks

**Comment by Aeases** [comment]
It does not occur if I turn off the background exporter, instead the banner is at the top of the file which works 👍

**Comment by KosmosisDire** [comment]
This should be fixed in version 1.5.1. Thanks for the report!
