### ISSUE TITLE
Internal Links do not work

### ISSUE THREAD

**Issue by corvusdeinanis** [KosmosisDire/obsidian-webpage-export#79]
When exported, internal links do not seem to work. The link leads to `chosen_folder/users/x/appdata/local/obsidian/linked_file` instead of `/linked_file`. 

As the linked file does not exist, it leads to a "File Not Found" page.

Using Obsidian 1.1.16 and Obsidian Web Export 1.5.1 (the latest one at the time of writing)

**Comment by corvusdeinanis** [comment]
Hi! You seem to be right! this only happens to files in the root folder. If the file in inside a different folder, say `root\inbox` , then it works perfectly. 

No errors or warnings in the log file when this happens

Windows 10 (tested on two different computers)
Obsidian 1.1.16 and Obsidian Web Export 1.5.1

Love this plugin by the way, can't believe I found it so late! Cheers

**Comment by KosmosisDire** [comment]
I should have a fix for this soon. I beleive I found the culprit bug. 

I am glad you are enjoying the plugin :)

**Comment by KosmosisDire** [comment]
This should be fixed in the latest version, let me know if it is not! Thanks for the report! :)
