### ISSUE TITLE
Feature Request: Add command palette 

### ISSUE THREAD

**Issue by JasonAizkalns-Zoetis** [KosmosisDire/obsidian-webpage-export#8]
...because this is awesome, it should have a proper home in the [command palette](https://marcus.se.net/obsidian-plugin-docs/user-interface/commands). Maybe two options: one for "this note" and another for "this folder" or vault.

**Comment by KosmosisDire** [comment]
I will probably add commands in the future, thanks for your interest

**Comment by KosmosisDire** [comment]
Added in latest release 1.3.1. I didn't add an option for "this folder" as what "this folder" means is ambiguous of nested folders, and can just be performed by right clicking a folder, which is unambiguous.
