### ISSUE TITLE
Installing via Obsidian Community Plugins does not work

### ISSUE THREAD

**Issue by corvusdeinanis** [KosmosisDire/obsidian-webpage-export#80]
Using version 1.5.1 of Obsidian Webpage Export.

**the error**

Installing via the community marketplace does not seem to be working. I get an `Error: Could not read text file at path` and an `Error: ENOENT no such file or directory`
![image](https://user-images.githubusercontent.com/25402014/235864106-1b77e426-0f92-4bbf-9ee1-c0792a50f14e.png)

**cause**
the scripts folder, the assets folder, and the other files don't seem to be downloaded whilst downloading the plugin from the marketplace. Manually downloading the files and putting it into the `\plugins\webpage-html-export` folder makes it work! 

Manual installation still works, just the marketplace one doesn't due to missing files for some reason. I've tried this on an empty test vault with no other plugin enabled, and two computers both running Windows 10 and Obsidian 1.1.16

**Comment by KosmosisDire** [comment]
Thanks for reporting this, I will fix this immediately!

**Comment by KosmosisDire** [comment]
Let me know if this is fixed in the latest version. Thanks again for reporting this!

**Comment by Torphedo** [comment]
I had the same issue. Seems fixed now, no errors.

**Comment by KosmosisDire** [comment]
Okay great, thanks!
