### ISSUE TITLE
Math styles break

### ISSUE THREAD

**Issue by dgudim** [KosmosisDire/obsidian-webpage-export#81]
After exporting, LaTeX equations break, and in the export too, this happens randomly, I can't consistently reproduce this 

![image](https://user-images.githubusercontent.com/34401005/235982122-0d796c49-9585-4274-8a05-0174e6a626af.png)

Another example: 

![image](https://user-images.githubusercontent.com/34401005/235982202-2161eaae-1fe2-4deb-a31d-e8c38668ee1b.png)

**Comment by KosmosisDire** [comment]
Hey, I have also had this happen. It is so difficult to consistently load the math styles! I'll work on making it more reliable, thanks!

**Comment by dgudim** [comment]
Update on this issue:
Now I can't render them correctly at all, I don't what I changed, but now they always break, in the sandbox too :(

**Comment by KosmosisDire** [comment]
Huh that is strange, when is the last time it worked? I assume you reinstalled the plugin since you tried it in sandbox. Are there any errors thrown either in the dev console or the render log?

**Comment by dgudim** [comment]
It worked when I first submitted the issue, tried exporting today, didn't work. I can send you part of my vault to test. No errors in the console 

https://user-images.githubusercontent.com/34401005/236791799-d104f363-a77b-4595-9abd-755fffccb47e.mp4

**Comment by dgudim** [comment]
I think I am gona use the old version without the background renderer for now

**Comment by dgudim** [comment]
I have a proposal though, can the math styles be bundled with the plugin or maybe obtained from where obsidian gets them (I am not familiar with mathjax so don't know if this makes sense)

**Comment by dgudim** [comment]
Or maybe don't load styles at all and instead use mathjax loader script?
```
<script type="text/javascript" id="MathJax-script" async
  src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
</script>
```

**Comment by KosmosisDire** [comment]
> I have a proposal though, can the math styles be bundled with the plugin or maybe obtained from where obsidian gets them (I am not familiar with mathjax so don't know if this makes sense)?

I tried to do this, but unfortunately it did not work. Obsidian loads them with the `MathJax.chtmlStylesheet()` which returns a `<style>` element containing the styles. Unfortunately, when I used this, although it returned the stylesheet correctly, it caused obsidian to not be able to load the stylesheet correctly. So I switched back to the method I was using before, which for some reason isn't working anymore lol. 

As far as just bundling the styles, I tried that a while back and it didn't work either, although I don't remember all the details of why. I think the problem may have been that obsidian loads only the styles that are used per file so each file has different styles. But I might be wrong about that.

> Or maybe don't load styles at all and instead use mathjax loader script?
> 
> ```js
> <script type="text/javascript" id="MathJax-script" async
>   src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js">
> </script>
> ```

I hadn't considered this, I will certainly give that a shot! Thanks

**Comment by KosmosisDire** [comment]
> So they were good in the export and broken in obsidian? You can just restart obsidian after the export, it's still better than no styles at all

Yes I beleive so. I'd rather find something that works than implement a new method that I know is also broken, even if it is better than what is currently happening (Especially since this bug isn't happening for everyone, but that solution I tried would have been broken for everyone).

I am still working on it though, hopefully I can get it fixed.

**Comment by KosmosisDire** [comment]
This latest update should fix this! I actually found the cause. Let me know if you still have problems.

**Comment by dgudim** [comment]
Nice. It's indeed fixed, big thank you
