### ISSUE TITLE
Table of contents doesn't show folders

### ISSUE THREAD

**Issue by berthelemy** [KosmosisDire/obsidian-webpage-export#82]
**Describe the bug**

I have a vault structured with several folders (directories). I was expecting those directories to show up in the table of contents. (Sorry if this is actually a feature request...)

[Edit: Table of contents only shows the current page in the list]

**Operating System**
MacOS

**To Reproduce**
1. Create a vault with 2 folders
2. Add a note to each folder
3. Export to HTML

**Comment by KosmosisDire** [comment]
The table of contents is the table of contents of the currently open file. If you look at the pinned issues I believe what you are wanting is the first pinned issue.
