### ISSUE TITLE
Add custom view support (Kanban, etc.)

### ISSUE THREAD

**Issue by KosmosisDire** [KosmosisDire/obsidian-webpage-export#83]
Add support for documents that use custom views. Like the Kanban plugin and others.

**Comment by nonsciencemark** [comment]
Hello! Very cool plugin, but I can't get the Kanban export to do anything- I just get a blank page with "Page Not Found" and the TOC and light/dark toggle. What exactly are the settings required to get a Kanban to export?

**Comment by nonsciencemark** [comment]
@KosmosisDire My bad, misunderstood! Thanks for letting me know :)

**Comment by KosmosisDire** [comment]
@nonsciencemark This has been added in the latest update :)

**Comment by nonsciencemark** [comment]
Yaaay! It works perfectly, great job!
