### ISSUE TITLE
Table of Contents does not behave correctly

### ISSUE THREAD

**Issue by silverfs** [KosmosisDire/obsidian-webpage-export#84]
**Describe the bug**
After the most recent update (1.5.2), when viewing an exported document, it appears that pages not in the root folder have trouble with the table of contents provided by webpage-export. Clicking on them often scrolls the page to the top and navigation doesn't work. 

**Operating System and versions**
Windows 10/11, 
Firefox 112.0.2, 
Obsidian 1.2.7,
Tried using `file://` and `http://`,
Tried exporting self-contained documents and multi-file website. 

**To Reproduce**
1. Export the entire vault vault.
2. Click on 'a page not located in the root folder' or 'go to a page through a page link in the root folder' (results are the same).
3. Click on a link at the generated 'table of contents' in a file that's not in the root folder.
4. See the page glitching to the top of the screen or not working at all.

**Comment by KosmosisDire** [comment]
Hmm yes I can reproduce this easily. Let me see if I can fix that! Thanks for the report! :)

**Comment by KosmosisDire** [comment]
Okay if you reload obsidian and re-export you should find this issue fixed assuming obsidian doesn't cache the scripts. If is still doesn't work try reloading obsidian a rouple more times. (There is a command to reload obsidian without having to close it btw)

**Comment by silverfs** [comment]
I did a reload in Obsidian and the problem seems to be fixed. I've checked both root and non-root files, and tested both `file://` and `http://`. Thank you for the quick response and fix! Really appreciate the effort. Love your work <3

**Comment by silverfs** [comment]
Awesome! I'll continue using this flow here. This issue can be marked as closed.
