### ISSUE TITLE
Add button to hide sidebars / focus document

### ISSUE THREAD

**Issue by ouzf** [KosmosisDire/obsidian-webpage-export#87]
Great plugin for exporting obsidian notes to html files.

**But will you add hidden button of outline bar?**

Looking forward to the new features of this plugin.

**Comment by KosmosisDire** [comment]
Can you clarify what you mean? I am not sure I understand what you are wanting me to add thanks!

**Comment by ouzf** [comment]
I mean that, ...

Can you add a button on the exported webpage? And this button can swich on/off the outline-sidebar. Just like the theme toggle.

I think this is a good feature. Thanks!

**Comment by KosmosisDire** [comment]
Do you mean like this button in obsidian that opens and closes the sidebar?
![image](https://user-images.githubusercontent.com/39423700/236391217-f2cfba1b-61b9-4417-b83d-6667d584aee6.png)

**Comment by ouzf** [comment]
Yes, this is what I mean.

![动画](https://user-images.githubusercontent.com/36063943/236399491-93110943-d9e0-4c8f-8b97-babfef485992.gif)

**Comment by KosmosisDire** [comment]
Okay, I will consider this. Is the reason you want this for support on mobile? Or are you wanting to be able to hide them for use on desktop? There should be enough space to show the sidebars as well as the document on most all computer screens, and the sidebars are hidden on mobile. Or is it more of just a visual clutter problem? Thanks for the suggestion!

**Comment by ouzf** [comment]
I wish it would work on desktop. When the sidebar is visible, the body part is not centered in the browser window. This is not good for presentation. So I hope the sidebar can hide when I do presentation, and can quickly switch on when I want to use outline.
![image](https://user-images.githubusercontent.com/36063943/236430584-f6e41ab2-2292-4afd-a098-a8df34b4cfcb.png)

**Comment by ouzf** [comment]
It's better if the plugin can force the body part to be centered.

**Comment by KosmosisDire** [comment]
I have already added a feature (which is not released yet so you cannot access it yet) which will allow you to push the sidebars to the edges, and set the width of the sidebars leaving the document exactly centered. So as far as centering the document, that is a feature that is coming!

So it sounds like you are actually presenting these documents and want to reduce the visual clutter as much as possible. I will definetly conisder adding a collapse button for the sidebars. 

Do you think it would be better to have one button for each sidebar, or would it maybe be better to have one "fullscreen" button that would hide both sidebars leaving the document to take up the whole page?

Thank you for taking the time to suggest this, and explaining your idea! :)

**Comment by ouzf** [comment]
It  will be better to have a "fullscreen" button. By the way, I think the two sidebars can be combined, because the theme toggle (left sidebar) is just a button that doesn't show any text.

Thank you for your positive response, and I look forward to the better version being released soon.

**Comment by KosmosisDire** [comment]
The left sidebar is planned to have the whole vault outline in the future. See issue #30.

**Comment by benjitusk** [comment]
This is definitely a welcome addition to this amazing plugin. +1 request for this.

**Comment by KosmosisDire** [comment]
This should be implemented in v1.7.1! :) Let me know if you have any problems with it
