### ISSUE TITLE
Export to PDF doesn’t work when this plugin is enabled

### ISSUE THREAD

**Issue by Fastidious** [KosmosisDire/obsidian-webpage-export#88]
The built-in “Export to PDF” on Obsidian doesn’t do anything when this plugin is enabled. To export to PDF I have to disable this plugin first.

**Comment by KosmosisDire** [comment]
I am not able to reproduce this. Can you try opening a sandbox vault (there is a command for it) and then install the plugin and see if the PDF export works there? Thanks!

**Comment by Fastidious** [comment]
I re-installed the plugin, and now works. Not sure what happened, as I tried a few times before coming to fill the issue. Closing now, sorry about the noise. Cheers!
