### ISSUE TITLE
List folding on exported pages

### ISSUE THREAD

**Issue by ObviousNonsense** [KosmosisDire/obsidian-webpage-export#91]
**Is your feature request related to a problem? Please describe.**
Lists with sub-items cannot be folded (collapsed) or unfolded in the exported html. Subitems of list elements that were folded when the page is exported are not visible, but inspecting the html shows that they are there.

**Describe the solution you'd like**
List folding/unfolding should work. 

**Additional context**
Folding/unfolding already works for headings, so presumably this should be possible.

**Comment by KosmosisDire** [comment]
Yes this is on my list, thanks for letting me know that it would be useful :)

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0! :)
If you find any issues please create a new issue
Thanks!
