### ISSUE TITLE
Make tags show a list of all pages with that tag

### ISSUE THREAD

**Issue by berthelemy** [KosmosisDire/obsidian-webpage-export#93]
**Is your feature request related to a problem? Please describe.**
As a user, I would like tags to open a page that contains a list of all the notes with that tag, so I can create some structure in the exported website

**Describe the solution you'd like**
When I create a tag using '#tag', that tag should be a hyperlink that then opens a new page (in the same window). That page should contain:

- A title: The tag name
- A list of links in alphabetical order, each of which is labelled with the name of the page, and the href URL is the URL of the page

The list only contains the pages that contain the tag.

**Comment by KosmosisDire** [comment]
This is something I have been thinking about adding, thanks for the suggestion!

**Comment by KosmosisDire** [comment]
(This is also related to issue #67)

**Comment by KosmosisDire** [comment]
Note for future: Once search support is added (#120) clicking on a tag could instead bring up a list of notes in the sidebar as a search for that tag rather than loading a whole new page.

**Comment by KosmosisDire** [comment]
This feature has been added in 1.8.0 as long as you have the search bar enabled. (it will simply search the vault for that tag). I may improve this behavior in the future, but I will close this issue for now. If you have ideas for improvments on this create a new issue or open a disscusion in the discussions tab.
Thanks! :)
