### ISSUE TITLE
Include embedded files in export (pdf, or attachments)

### ISSUE THREAD

**Issue by silverfs** [KosmosisDire/obsidian-webpage-export#95]
**Is your feature request related to a problem? Please describe.**
When I'm exporting my vault, there can be other files in my directory that are not included in the export, like PDFs (obviously). However, as I'm linking to PDFs within my .md files, but the PDF files don't get included in the exported result, I have to manually copy-paste them in the export-folder.
Might be an addition to #13. I'm not sure.

**Describe the solution you'd like**
It would be cool if we came up with a solution for this problem. Perhaps we could add an option to select certain kinds of files or whole folders / by extension that would be included in the export-result without being converted into anything. 

**Describe alternatives you've considered**
Currently, the only alternative is to manually copy-paste certain documents into the right folders, to ensure the linking to the files work. This will be considerably more difficult however, when there are a lot of different files/folders you want to include.

Please let me know if anything is unclear. I am happy to help.

**Comment by KosmosisDire** [comment]
Thanks, this is not supported because I have not done anything to specifically support embedded PDFs. How are you including the PDF's? Are they just direct links to the PDFs or are they embedded? Direct links would be easy to implement.

**Comment by silverfs** [comment]
Yeah. Currently, the links are direct links like this: `[file.pdf](/folder/file.pdf)`. Embedding PDFs is cool, but that's not the scope of this question, as I know you haven't implemented anything in regards to that. 
I hope this is more clear.

**Comment by aubreyz** [comment]
Direct links would be very nice if easy to do.
Also links (not embeds) of form [[filename]] without the ! Where file path needs handling as per images as can exist anywhere in vault.

**Comment by silverfs** [comment]
I'd like to make an addition to the implementation of this enhancement. 
Let's say I have a PDF file in my directory. The most ideal would be the following:
- I'd export my vault.
- The PDF would be copied/inserted into the export location with the rest of my vault. Links in my files pointing to the PDF file should work.
- The PDF would get an entry in the left sidebar as a clickable file.

**Comment by KosmosisDire** [comment]
Thanks for the clarification, this is planned! :)

**Comment by ZyphenVisuals** [comment]
> I'd like to make an addition to the implementation of this enhancement. Let's say I have a PDF file in my directory. The most ideal would be the following:
> 
> * I'd export my vault.
> * The PDF would be copied/inserted into the export location with the rest of my vault. Links in my files pointing to the PDF file should work.
> * The PDF would get an entry in the left sidebar as a clickable file.
> 
> With this example, my request should be easier to read.

Thumbs up to this method of handling it!
I've recently used this to publish my studying vault for my friends to use, but the fact that PDFs are completely missing breaks a lot of the materials. 

Ideally I'd love to have the same built-in PDF viewer that Obsidian now has, but simply including the files and linking them would also be amazing! As long as they get a sidebar entry.

**Comment by KosmosisDire** [comment]
I am increasing the scope of this request to include both embedded and linked files since they both require the same solution and I will implement them together.

**Comment by KosmosisDire** [comment]
This should be implemented in v1.7.1! :) Let me know if you have any problems with it
