### ISSUE TITLE
dataviewjs is not rendered 

### ISSUE THREAD

**Issue by dgudim** [KosmosisDire/obsidian-webpage-export#96]
Even with the "dataview block render wait time" set to 1000ms, dataviewjs blocks are not properly rendered (no errors in the console)

In obsidian:
![image](https://user-images.githubusercontent.com/34401005/236804201-aca951ce-8795-4d1d-9edc-903b2b23921e.png)

In the export:
![image](https://user-images.githubusercontent.com/34401005/236804290-72f4c62c-183d-40bf-a65c-ee65a1d6e2a9.png)

Here is my dataview code:
```js
const folderlist = ['Computer architecture', 'Discrete math', 'Presentations']

for (let folder of folderlist) {
    dv.header(2, folder);
	for (let group of dv.pages(`"uni/${folder}"`).groupBy(p => p.file.folder)) {
		const header = group.key.substring(4);
		if(header.contains('/')) {
			dv.header(3, header.substring(header.lastIndexOf('/') + 1));
		}
		dv.table(["Name ", "Modified"],
		group.rows.map(k => [k.file.link, k.file.mtime]))
	}
}
```

Funny enough, it renders fine in the old renderer

**Comment by KosmosisDire** [comment]
Hmm, I cannot reproduce this. I am not sure what is causing it in your case, but hopefully I will be able to fix it in the next update.

**Comment by KosmosisDire** [comment]
This _should_ be fixed in the latest update, but let me know if it isn't. Thanks!

**Comment by KosmosisDire** [comment]
@dgudim This was actually a bug that I fixed haha (It was really very messy). If you could create a new feature request to add an option for this, I will implement it as an intentional feature that works the correct way. Thanks!

**Comment by KosmosisDire** [comment]
I am also noticing that your title is duplicated, which may be a bug with the feature to add an inline title if it is missing. You can fix that by turning off the option in settings, and I'll look into why that it happening.

**Comment by dgudim** [comment]
That was because I didn't RTFM and didn't delete the `assets` folder after reinstalling, 🤦. I am still gona open a request for the table of contents though
