### ISSUE TITLE
Transcluded notes work differently in export

### ISSUE THREAD

**Issue by efrec** [KosmosisDire/obsidian-webpage-export#97]
**Describe the bug**

I expect some differences between the HTML document structure in Obsidian vs the export. But the following broke some layout, in my case, and I couldn't find a reason for it.

In Obsidian, my internal embeds are a div>p>span:

![image](https://user-images.githubusercontent.com/103912894/236950328-c79aa532-84e6-48af-97e0-063a45864664.png)

vs the exported file, which is a div>p+div:

![image](https://user-images.githubusercontent.com/103912894/236950436-65e9b8c0-dccf-484f-aff0-29d113d7d38b.png)

and also ends with another empty p:

![image](https://user-images.githubusercontent.com/103912894/236950784-bbb946f2-d24e-4668-9ae0-3e4f6fc9f385.png)

Also, I use selectors for different types of embedded content, e.g. selecting on `.internal-embed`. My exported files don't include these classes (they were on the `span`), so I can't uniquely identify different cases for embeds. I relied on that to set `--file-margins: 0;` on transclusions, for example.

**Operating System**

Windows 11

**To Reproduce**

Create a couple of notes. Transclude one into the other. The note I transcluded used a section heading instead of the entire note, e.g. `![[Note name#Heading label]]` instead of `![[Note name]]`.

### Error Log

No errors; just logs.

[obsidian.md-1683585876491.log](https://github.com/KosmosisDire/obsidian-webpage-export/files/11425717/obsidian.md-1683585876491.log)

**Comment by KosmosisDire** [comment]
Transclusions are not officially supported by the plugin and if they work then it is a byproduct of generalized code. If I am understanding you correctly the problem is not that transclusions don't work, but just that the selectors are different and so your snippets don't work? Or is there more that is going wrong?

**Comment by efrec** [comment]
I see. They're pretty close, then -- all that's really missing is the top-level span, which contains the src and a class for the embed type.

**Comment by KosmosisDire** [comment]
I will modify it to make sure the transclusions have the same structure in the export as in obsidian's rendered view. Thanks for the report!

**Comment by KosmosisDire** [comment]
This is fixed in update 1.6.0, let me know if you have any more problems! And thanks for the report :)
